### ISSUE TITLE
Should decode HTML entities

### ISSUE THREAD

**Issue by wooorm** [remarkjs/remark#1]
Such as, `&amp;` in `AT&amp;T`.

**Comment by NullVoxPopuli** [comment]
Is there an option to turn this off in today's Remark?

I'm running in to an issue where I'm doing markdown -> components -> html, and when converting `&lt;example&gt;` to `<example>`, this breaks the validity of the output document as `<example>` is an unclosed tag

**Comment by wooorm** [comment]
This sounds like an XY problem: https://xyproblem.info.
And maybe more of a question. Could you either open a discussion, or a new issue, and fill in the template?
