### ISSUE TITLE
In Japanese, Emphasis and Strong have a bug

### ISSUE THREAD

**Issue by Neos21** [remarkjs/remark#1107]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

remark-parse@7.0.1, remark-rehype@8.0.0

### Steps to reproduce

I use Node.js v18.12.1 and npm v8.19.2. I wrote vanilla Node.js script.

- `package.json` : `devDependencies`

```json
{
  "rehype-stringify": "9.0.3",
  "remark-parse": "10.0.1",
  "remark-rehype": "10.1.0",
  "unified": "10.1.2"
}
```

- Code:

```javascript
import { unified } from 'unified';
import remarkParse from 'remark-parse';
import remarkRehype from 'remark-rehype';
import rehypeStringify from 'rehype-stringify';

const processor = unified()
  .use(remarkParse)
  .use(remarkRehype)
  .use(rehypeStringify);
const result = processor.processSync(`
1. 日本語*強調*、日本語
2. 日本語*強調*。日本語
3. 日本語*強調、*日本語
4. 日本語*強調。*日本語
5. 日本語**強調**、日本語
6. 日本語**強調**。日本語
7. 日本語**強調、**日本語
8. 日本語**強調。**日本語
`);
console.log(result.value);
```

- 8 examples.
- The first 4 examples are wanted to convert to `<em>`
- The last 4 examples are wanted to convert to `<strong>`
- But, No. 3, 4, and 7, 8 were not converted.
    - I think a regexp has a bug with the character `、` and `。` maybe...?

### Expected behavior

```html
<ol>
<li>日本語<em>強調</em>、日本語</li>
<li>日本語<em>強調</em>。日本語</li>
<li>日本語<em>強調、</em>日本語</li>
<li>日本語<em>強調。</em>日本語</li>
<li>日本語<strong>強調</strong>、日本語</li>
<li>日本語<strong>強調</strong>。日本語</li>
<li>日本語<strong>強調、</strong>日本語</li>
<li>日本語<strong>強調。</strong>日本語</li>
</ol>
```

### Actual behavior

```html
<ol>
<li>日本語<em>強調</em>、日本語</li>
<li>日本語<em>強調</em>。日本語</li>
<li>日本語*強調、*日本語</li>
<li>日本語*強調。*日本語</li>
<li>日本語<strong>強調</strong>、日本語</li>
<li>日本語<strong>強調</strong>。日本語</li>
<li>日本語**強調、**日本語</li>
<li>日本語**強調。**日本語</li>
</ol>
```

### Runtime

Node v17, Other (please specify in steps to reproduce)

### Package manager

npm 8

### OS

Windows

### Build and bundle tools

Other (please specify in steps to reproduce)

**Comment by Neos21** [comment]
I found other bug with the character `「` and `」`. Maybe more characters have same bug.

**Comment by ChristianMurphy** [comment]
Welcome @Neos21! 👋 
Sorry you ran into a spot of trouble.

Some background, `remark` implements commonmark (https://commonmark.org/) or with `remark-gfm` implements GFM (https://github.github.com/gfm/).
The output you are currently seeing from `remark` is expected, it is how emphasis works in commonmark and GFM.


example of rendering in the commonmark reference implementation: https://spec.commonmark.org/dingus/?text=1.%20%E6%97%A5%E6%9C%AC%E8%AA%9E*%E5%BC%B7%E8%AA%BF*%E3%80%81%E6%97%A5%E6%9C%AC%E8%AA%9E%0A2.%20%E6%97%A5%E6%9C%AC%E8%AA%9E*%E5%BC%B7%E8%AA%BF*%E3%80%82%E6%97%A5%E6%9C%AC%E8%AA%9E%0A3.%20%E6%97%A5%E6%9C%AC%E8%AA%9E*%E5%BC%B7%E8%AA%BF%E3%80%81*%E6%97%A5%E6%9C%AC%E8%AA%9E%0A4.%20%E6%97%A5%E6%9C%AC%E8%AA%9E*%E5%BC%B7%E8%AA%BF%E3%80%82*%E6%97%A5%E6%9C%AC%E8%AA%9E%0A5.%20%E6%97%A5%E6%9C%AC%E8%AA%9E**%E5%BC%B7%E8%AA%BF**%E3%80%81%E6%97%A5%E6%9C%AC%E8%AA%9E%0A6.%20%E6%97%A5%E6%9C%AC%E8%AA%9E**%E5%BC%B7%E8%AA%BF**%E3%80%82%E6%97%A5%E6%9C%AC%E8%AA%9E%0A7.%20%E6%97%A5%E6%9C%AC%E8%AA%9E**%E5%BC%B7%E8%AA%BF%E3%80%81**%E6%97%A5%E6%9C%AC%E8%AA%9E%0A8.%20%E6%97%A5%E6%9C%AC%E8%AA%9E**%E5%BC%B7%E8%AA%BF%E3%80%82**%E6%97%A5%E6%9C%AC%E8%AA%9E

and example gfm rendering the content here on GitHub itself:

---

1. 日本語*強調*、日本語
2. 日本語*強調*。日本語
3. 日本語*強調、*日本語
4. 日本語*強調。*日本語
5. 日本語**強調**、日本語
6. 日本語**強調**。日本語
7. 日本語**強調、**日本語
8. 日本語**強調。**日本語

---

`remark` implements commonmark to spec, the implementation as is matches the behavior, differing would be a bug.

The way to make a change would be to have the commonmark standard change.
If you'd like to nudge commonmark towards better supporting more languages, feel free to reach out in the specification discussion forum (https://talk.commonmark.org/)
In particular this thread https://talk.commonmark.org/t/emphasis-and-east-asian-text/2491
