### ISSUE TITLE
Error "document is not defined" when running in browser extension background

### ISSUE THREAD

**Issue by phuctm97** [remarkjs/remark#1165]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

remark-stringify

### Steps to reproduce

Import `remark-stringify` into a browser extension's background service worker script. The script initialization will fail immediately with error "document is not defined".

I checked the code, it seems like there is a use of `document.createElement("i")`, I'm not sure what it's for.

### Expected behavior

It should work fine in service worker environment and does not depend on DOM API.

### Actual behavior

It depends on `document` and fails in non-DOM environment.

### Runtime

Node v16

### Package manager

yarn 1

### OS

macOS

### Build and bundle tools

esbuild

**Comment by wooorm** [comment]
You can configure your bundler. It only does this if you say it is running in a browser (browsers have a document), it doesn't do so in places that have no document (node, deno, worker, react-native).

If you run in a browser but without document, configure your tools: https://github.com/wooorm/parse-entities/issues/19
