### ISSUE TITLE
A stringifier option to control escaping

### ISSUE THREAD

**Issue by djmcgreal-cc** [remarkjs/remark#1168]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

The stringifier is escaping in a way I find overzealous.

Is it for portability? I don't need portability for my case and find `_SOME\_ITALICS\_WITH\_SPACES_` less readable and natural.

### Solution

An option to control when things are escaped. I'd be happy with turning it off entirely but others might want more control for escaping in different scenarios.

### Alternatives

Not sure?

**Comment by wooorm** [comment]
Hi!

What you want (breaking all markdown) is not possible.

There is already control in options: the [`Unsafe` patterns](https://github.com/syntax-tree/mdast-util-to-markdown/tree/main#unsafe).

If you want to improve how things are escaped and want to put in the work to do so, feel free to open a discussion and share your throughs on how to achieve that: https://github.com/syntax-tree/.github/blob/main/support.md

**Comment by Murderlon** [comment]
The easiest way to get rid of them if you must if to run [Prettier](https://prettier.io/) after remark on the files. They have custom remark logic to undo the escapes.

**Comment by djmcgreal-cc** [comment]
Is it possible to use `Join`, `Unsafe` etc with a .remarkrc.yaml? Or is this only configurable from JS?

**Comment by wooorm** [comment]
JS, and it’s all complex. See the thread I linked.

**Comment by djmcgreal-cc** [comment]
Thanks for the help :)
PS I hope my small use case doesn't break all markdown, that would definitely be an unintended side-effect!

**Comment by wooorm** [comment]
> PS I hope my small use case doesn't break all markdown, that would definitely be an unintended side-effect!

It’s like asking a JavaScript formatter to emit the string `"` unescaped. You’d get `const x = """` for example. That breaks JavaScript. Same with markdown.

**Comment by HananoshikaYomaru** [comment]
> The easiest way to get rid of them if you must is to run [Prettier](https://prettier.io/) after remark on the files. They have custom remark logic to undo the escapes.

I don't see how, can you explain?
