### ISSUE TITLE
Ampersand in link query strings unexpectedly escaped with backslash

### ISSUE THREAD

**Issue by delucis** [remarkjs/remark#1196]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

remark@14.0.3 — also tested with 13.0.0, 14.0.0, and 14.0.2 with the same results.

### Link to runnable example

https://codesandbox.io/s/remark-ampersand-escaping-repro-6mm6xg

### Steps to reproduce

1. Create a Markdown string, containing a link with a query string. For example:

   ```js
   const md = '[label](https://github.com/search?type=code&q=remark)';
   ```

2. Process the string with remark:

   ```js
   const file = await remark().process(md);
   ```
   
3. Inspect the result:

   ```js
   console.log(String(file));
   // [label](https://github.com/search?type=code\&q=remark)
   ```

### Expected behavior

The original link and query string should remain unchanged.

### Actual behavior

The `&` in the link’s query string is escaped with a `\`, breaking the link. (Perhaps this is intentional for a reason I don’t understand, but it was unexpected to me.)

### Runtime

Node v16, v18, v20

### Package manager

npm 8, pnpm

### OS

Linux, macOS

### Build and bundle tools

Rollup, esbuild, Parcel, Vite — tried a bunch of different environments to confirm behaviour.

**Comment by wooorm** [comment]
Hey!

This is intentional. `&`, depending on what comes after it, could turn into a character reference. E.g., when `copy;` comes after it, it turns into something else.

> breaking the link

The link is not broken. Markdown parsers support escapes.

---

For more info, see for example https://github.com/syntax-tree/mdast-util-to-markdown/issues/53.

**Comment by delucis** [comment]
Thanks for the response! My rehype pipeline is still ending up with the bad link in the rendered content, but I’ll dig a bit deeper to figure out that bit. 🙌

**Comment by wooorm** [comment]
No worries!

Could you share the actual problem with me? I'd appreciate hearing your root cause for future strugglers!

**Comment by delucis** [comment]
Mostly human error! 😅 

We have a pipeline that pulls in some Markdown, processes with remark and a bunch of plugins, and then stores the resulting Markdown for rendering later. We were struggling with migrating some links where the search parameter syntax had changed and noticed “Oh there’s this `\` in some of them after processing.” This led us to misattribute that as the cause for some link breaking (because naively copying a link like that _does_ break) and debug to work out what was introducing the `\` (assuming it to be one of our plugins, but later realising it was `remark` itself). You mentioned “Markdown parsers support escapes”, so that made me double check and realise this was the wrong rabbit hole and the final `<a>` in our rendered content was correct 😁 

Anyway — appreciate your fast response. Helped get us back on track 💜
