### ISSUE TITLE
Footnotes do not work within mermaid diagrams

### ISSUE THREAD

**Issue by lschierer** [remarkjs/remark#1208]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

"remark-rehype": "^10.0.0",     "rehype-mermaidjs": "^1.0.1",     "remark-gfm": "^3.0.1",

### Link to runnable example

https://stackblitz.com/edit/github-3bxwan

### Steps to reproduce

See the runnable example in stackblitz, however I initially hit this in a project using astro with tsc to build the typescript. 

### Expected behavior

the footnotes should work globally, because the gfm plugin should have processed first. 

### Actual behavior

the footnotes only work outside the mermaid diagram. 

### Runtime

Node v17, Node v16

### Package manager

npm 8, pnpm

### OS

macOS

### Build and bundle tools

Vite, Other (please specify in steps to reproduce)

**Comment by ChristianMurphy** [comment]
Welcome @lschierer! 👋 
Codeblocks including mermaid do cannot have inner markdown.
Including references and footnotes.
This is by design, and how GFM works.
