### ISSUE TITLE
How to display incomplete PHP code outside of a code block

### ISSUE THREAD

**Issue by charliematters** [remarkjs/remark#1213]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

Remark@10, Rehype@9

### Link to runnable example

https://stackblitz.com/edit/github-uzm7cu?file=src%2Fmain.ts

### Steps to reproduce

We have some users unfamiliar with markdown who are adding snippets of code in without code blocks. In one case, they are adding an incomplete php section:
```
Before
<?php
// PHP code
After
```
And reporting that it is not working as expected:
```
Before
```

I realise this is an education issue, however the first google result for a markdown editor (StackEdit) handles this case in a more expected way, outputting this:
```
Before

<?php // PHP code After
```

### Expected behavior

The valid markdown after the PHP tag should still be shown, along with the incomplete PHP

### Actual behavior

The PHP start tag stops any further output

### Runtime

Node v17

### Package manager

npm 8

### OS

Windows

### Build and bundle tools

Webpack

**Comment by wooorm** [comment]
Also: we support plugins. If you write a plugin, you can turn html into text, making it visible.

react-markdown at least has an option for it.

Perhaps you can share your actual setup so that we can practically help you.
