### ISSUE TITLE
New release with updated dependencies

### ISSUE THREAD

**Issue by tobiasdiez** [remarkjs/remark#1231]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

Using this package via nuxt/content results in some issues since the last released version depends on older version of dependencies, see https://github.com/nuxt/content/issues/1562.

### Solution

Should be resolved by https://github.com/remarkjs/remark/commit/943f6ac94bfb29e101a1dceee9ca5b3191420261, so only thing needed is a new release 😄

### Alternatives

Couldn't find a workaround.

**Comment by wooorm** [comment]
Hey! Working on it, as you saw. Working on 100s of repos. I’ll close this for now, it’s not beneficial to have separate issues in some repos open.

I don’t understand why Nuxt results in an error. With semver, you shouldn’t get a newer micromark that doesn’t work with current remark.

**Comment by tobiasdiez** [comment]
I thought a new release might be easy to do - so sorry for the added noise.

The problem in the context of nuxt/content is that some other packages depend on micromark 4 while this package here still uses v3, and nuxt has some troubles with these double versions.

**Comment by wooorm** [comment]
no problem about the issue/“noise”, it’s just easier for me to not try and track a couple issues scattered across different projects!

The release is ready, it’s just that I also want to release a couple remark plugins that deeply integrate with this at the same time. And that I don’t have much time this weekend. Should be monday.

> and nuxt has some troubles with these double versions.

Ah. Hmm. Weird!

**Comment by lucgagan** [comment]
@wooorm Is this related to the issue I am getting here?

```
src/routines/formatMarkdown.ts:10:10 - error TS2769: No overload matches this call.
  Overload 1 of 3, '(preset?: Preset | null | undefined): Processor<Root, undefined, undefined, Root, string>', gave the following error.
    Argument of type 'import("/Users/gajus/Developer/rayrun/blog/node_modules/.pnpm/unified@10.1.2/node_modules/unified/index").Preset' is not assignable to parameter of type 'import("/Users/gajus/Developer/rayrun/blog/node_modules/.pnpm/unified@11.0.3/node_modules/unified/lib/index").Preset'.
  Overload 2 of 3, '(list: PluggableList): Processor<Root, undefined, undefined, Root, string>', gave the following error.
    Argument of type 'Preset' is not assignable to parameter of type 'PluggableList'.
  Overload 3 of 3, '(plugin: Plugin<[], undefined, undefined>, ...parameters: [] | [boolean]): Processor<Root, undefined, undefined, Root, string>', gave the following error.
    Argument of type 'Preset' is not assignable to parameter of type 'Plugin<[], undefined, undefined>'.

10     .use(remarkPresetLintMarkdownStyleGuide)
```

```
import { remark } from 'remark';
import remarkLintListItemBulletIndent from 'remark-lint-list-item-bullet-indent';
import remarkLintListItemIndent from 'remark-lint-list-item-indent';
import remarkPresetLintMarkdownStyleGuide from 'remark-preset-lint-markdown-style-guide';
import remarkPresetLintRecommended from 'remark-preset-lint-recommended';

export const formatMarkdown = async (markdown: string): Promise<string> => {
  const file = await remark()
    .use(remarkPresetLintRecommended)
    .use(remarkPresetLintMarkdownStyleGuide)
    .use(remarkLintListItemIndent, 'space')
    .use(remarkLintListItemBulletIndent, 'space')
    .process(markdown);

  return file.value.toString();
};
```

**Comment by lucgagan** [comment]
I am getting it for seemingly every plugin.

**Comment by wooorm** [comment]
Yes, it is related. Wait a bit for me to update everything. Should be done in 2 weeks.
