### ISSUE TITLE
`Compile` not set when used as a unified plugin

### ISSUE THREAD

**Issue by siefkenj** [remarkjs/remark#1236]
It appears that `remark-stringify` sets `this.compiler` rather than `this.Compiler`, which prevents this plugin from working in Unifiedjs 10.

**Comment by ChristianMurphy** [comment]
Welcome @siefkenj!
Sorry you ran into some confusion.
The latest version of `remark-stringify` v11, is compatible with `unified` v11.
The change to lowercase `compiler` is explained here https://github.com/unifiedjs/unified/commit/8e574788d7c6a44b6b2fe884bd42c89580ef4643

The solution is the match your version of remark to your version of unified.
10 with 10, or 11 with 11, not mixing incompatible versions.

Also for future reference, please do not skip or erase the issue template, it has information which helps maintainers and community members better support you.

**Comment by siefkenj** [comment]
Thank you for the information :-).

Would you be open to supporting both versions 10 and 11 of unified? It seems like it would not cause an issue to add `this.Compiler = ...` as well.

**Comment by ChristianMurphy** [comment]
Would you be open to upgrade to unified v11? 🙂 
The `unified`/`remark` upgrade cleaned up unused and deprecated APIs, re-adding those deprecated APIs for no discernible reason, is a no for me.
If there is a particular reason why you do not want to upgrade, or a roadblock to upgrading, please share.
