### ISSUE TITLE
HTML entity is mangled

### ISSUE THREAD

**Issue by Porges** [remarkjs/remark#1251]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

at least 15.0.1, 14.0.2

### Link to runnable example

- Markdown–HTML: https://codesandbox.io/p/sandbox/github/remarkjs/.github/tree/main/sandbox-templates/remark-rehype-with-vite
- Markdown–Markdown: https://codesandbox.io/p/sandbox/github/remarkjs/.github/tree/main/sandbox-templates/remark-with-vite

### Steps to reproduce

Create a Markdown file:

```md
# test

片&#xE0103;
```

Run remark on it.

### Expected behavior

Output should preserve the HTML entity or change it to non-entity form.

### Actual behavior

HTML entity is changed to a completely different character:

```md
# test

片ă
```

Note that I don't recall this happening with past versions, so it might have been introduced (fairly) recently.

This will be a bug in `mdast-util-{from,to}-markdown`, but I’m not sure which.

### Runtime

Node v16

### Package manager

npm 8

### OS

Windows, Linux

**Comment by Porges** [comment]
This is also present when just using micromark:

```mjs
import {micromark} from 'micromark';
console.log(micromark('片&#xE0103;'));
```

**Comment by Porges** [comment]
Sent a PR fixing this to the micromark repo: https://github.com/micromark/micromark/pull/158

**Comment by wooorm** [comment]
Thanks!
