### ISSUE TITLE
remark-cli no longer allows using multiple plugins via the `--use` parameter

### ISSUE THREAD

**Issue by Xunnamius** [remarkjs/remark#1265]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

12 (didn't seem to happen with version 11)

### Steps to reproduce

> Using latest Node.js (20.9.0) and npm (10.2.3) via the CLI (no build tools or bundlers).

1. Navigate to https://stackblitz.com/edit/github-r8bday?file=package.json

2. Using the above stackblitz environment, the following will succeed (note the bad `--use` argument):

`npx --no-install remark --use remark-gfm --use x README.md`

Yet the following will fail:

`npx --no-install remark --use x --use remark-gfm README.md`

This seems to happen because only the very first appearance of `--use` is  honored, confirmed by:

`npx --no-install remark --use remark-remove-url-trailing-slash --use remark-gfm README.md`

Which fails to properly parse the GitHub-flavored Markdown; compare that to:

`npx --no-install remark --use remark-remove-url-trailing-slash --use remark-gfm README.md`

Which fails to remove the trailing slash from the url. Further, debug output only ever says "1 plugin" loaded regardless of how many `--use` arguments I supply.

### Expected behavior

Debug output should indicate that two plugins are being loaded, and the actual output should reflect that both plugins were loaded.

### Actual behavior

Debug output indicates that one plugin was loaded regardless of how many `--use` arguments are provided. remark's actual output confirms that only the very first `--use` argument is acknowledged.

### Runtime

Other (please specify in steps to reproduce)

### Package manager

Other (please specify in steps to reproduce)

### OS

Linux

### Build and bundle tools

Other (please specify in steps to reproduce)

---

This issue cropped up while upgrading some remark packages: https://github.com/Xunnamius/unified-utils/issues/96#issuecomment-1831480696. Specifically, several of my [integration tests](https://github.com/Xunnamius/unified-utils/blob/fe98b3c7f06f4356bed713d2edb7d6f7f749617b/packages/remark-remove-url-trailing-slash/test/integration-node.test.ts#L108-L116) started failing.

**Comment by wooorm** [comment]
Thanks Bernard! Released!

**Comment by Xunnamius** [comment]
Confirmed it works. Thank you for the speedy resolution, as always :)
