### ISSUE TITLE
Underline feature is not working with remark

### ISSUE THREAD

**Issue by Risini1998** [remarkjs/remark#1279]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

I am using the `"remark": "15.0.1"` version and I tried to display markdown content as follows.
```
import { remark } from 'remark'
import html from 'remark-html'
import RemarkGfm from 'remark-gfm'

const content = `
 **Hello World**
 
 _Hello World_
 
 <u>Hello World</u>
 
 ~~Hello World~~`

const processedContent = await remark()
      .use(html)
      .use(RemarkGfm)
      .process(content)
    const contentHtml = processedContent.toString()
```

But underline feature is not working. I have tried `remark-underline`. But `remark-underline` requires remark v12. How can I do this?

### Solution

According to above example it shows as below.

**Hello World**

_Hello World_

Hello World

~~Hello World~~

underline is not working.

### Alternatives

This can be achieved by` react-remark `package. But I want to know the way to do with `remark` package.

**Comment by wooorm** [comment]
What doesn’t work? Please show the exact output you get, and the exact output you want, in **code blocks**

**Comment by Risini1998** [comment]
I get the output as,
```
**Hello World**

_Hello World_

Hello World

Hello World
```
![image](https://github.com/remarkjs/remark/assets/62292463/aca10dbf-7cfe-4f51-98d2-f4042f6d83ae)
underline tag was removed and not underlined the 3rd 'Hello World'. I need this output by replacing underlined Hello World in 3rd line.

**Comment by wooorm** [comment]
Take some time to read the readme of `html`. There are options. Practically you need the `sanitize` option: https://github.com/remarkjs/remark-html#options.

But also take some time to read the rest of the readme. When you should or shouldn’t use it.
