### ISSUE TITLE
Module not found: Can't resolve 'devlop' in '/app/node_modules/remark/node_modules/unified/lib'

### ISSUE THREAD

**Issue by UsmanShafaqat007** [remarkjs/remark#1284]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

15.0.1

### Steps to reproduce

just add it via yarn and got the above error

### Expected behavior

no error

### Actual behavior

got error

### Runtime

Node v17

### Package manager

yarn 1

### OS

Linux

### Build and bundle tools

Create React App

**Comment by ChristianMurphy** [comment]
Welcome @UsmanShafaqat007! 👋 
Sorry you ran into a spot of trouble.

This isn't a bug in remark or unified. It is a bug in `create-react-app`.
See https://github.com/orgs/unifiedjs/discussions/233, https://github.com/remarkjs/react-markdown/issues/801, and https://github.com/remarkjs/react-markdown/issues/798

Note that `create-react-app` is deprecated https://github.com/reactjs/react.dev/pull/5487#issuecomment-1409720741, consider moving to a build tool which still has support like https://vitejs.dev/, https://nextjs.org/, or https://remix.run/ (among others)

A guide to help get started https://dev.to/henriquejensen/migrating-from-create-react-app-to-vite-a-quick-and-easy-guide-5e72
