### ISSUE TITLE
Incorrect Parsing of Markdown with Special Characters Adjacent to Strong Tags in Non-English Contexts

### ISSUE THREAD

**Issue by YvesRijckaert** [remarkjs/remark#1288]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

"remark-gfm": "^4.0.0", "remark-parse": "^11.0.0", "unified": "^11.0.4"

### Steps to reproduce

- Use `remark-parse`, `remark-gfm`, and `unified` packages to parse markdown content.
```
const processor = unified().use(remarkParse).use(remarkGfm);
const tree = processor.parse(md);
console.log(tree.children);
```
- Parse these two strings to see the different behaviour:
```
const markdownWithSpecialCharacter = '**test:**如李施德林';
const markdownWithoutSpecialCharacter = '**test**如李施德林';
```
- Observe that the raw markdown (`**`) is displayed instead of actual bold/strong text in the output, when there is a special character (here: `:`).

markdownWithSpecialCharacter:
```
[
  {
    "type": "paragraph",
    "children": [
      {
        "type": "text",
        "value": "**test:**如李施德林",
        "position": {
          "start": { "line": 1, "column": 1, "offset": 0 },
          "end": { "line": 1, "column": 15, "offset": 14 }
        }
      }
    ],
    "position": {
      "start": { "line": 1, "column": 1, "offset": 0 },
      "end": { "line": 1, "column": 15, "offset": 14 }
    }
  }
]
```

markdownWithoutSpecialCharacter:
```
[
  {
    "type": "paragraph",
    "children": [
      {
        "type": "strong",
        "children": [
          {
            "type": "text",
            "value": "test",
            "position": {
              "start": { "line": 1, "column": 3, "offset": 2 },
              "end": { "line": 1, "column": 7, "offset": 6 }
            }
          }
        ],
        "position": {
          "start": { "line": 1, "column": 1, "offset": 0 },
          "end": { "line": 1, "column": 9, "offset": 8 }
        }
      },
      {
        "type": "text",
        "value": "如李施德林",
        "position": {
          "start": { "line": 1, "column": 9, "offset": 8 },
          "end": { "line": 1, "column": 14, "offset": 13 }
        }
      }
    ],
    "position": {
      "start": { "line": 1, "column": 1, "offset": 0 },
      "end": { "line": 1, "column": 14, "offset": 13 }
    }
  }
]
```

### Expected behavior

The markdown content should be parsed correctly, with the strong tag (**) properly converting text to bold, regardless of the presence of special characters or non-English text adjacent to the tags.

### Actual behavior

- When a colon character is present next to a strong tag with non-English text following it, the markdown syntax is not correctly parsed, and the raw markdown is displayed.
- When non-English text is directly next to a strong tag without any special characters, the markdown is parsed correctly, and the text is bolded as expected.

### Runtime

Node v17

### Package manager

npm 8

### OS

macOS

### Build and bundle tools

Rollup

**Comment by wooorm** [comment]
https://spec.commonmark.org/dingus/?text=**test%3A**如李施德林

https://github.com/commonmark/commonmark-spec/issues/650

**Comment by tats-u** [comment]
@YvesRijckaert Could you try https://www.npmjs.com/package/remark-cjk-friendly for the time being?
