### ISSUE TITLE
Code fenced blocks are not processed properly

### ISSUE THREAD

**Issue by fourdim** [remarkjs/remark#1330]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

15.0.1

### Link to runnable example

https://stackblitz.com/edit/github-dbrz8s?file=src%2Fmain.ts

### Steps to reproduce

// https://spec.commonmark.org/0.31.2/#example-138
````
const sourceMarkdown = `
~~~ ~~~
aaa
`;
````

### Expected behavior

Code fences (opening and closing) cannot contain internal spaces or tabs.

### Actual behavior

Parsing ~~~ as language.

**Comment by wooorm** [comment]
The CM example you reference is different, it uses backticks.
Backticks and tildes are different. Because backticks are resused for “inline” code as well.

https://spec.commonmark.org/dingus/?text=~~~%20~~~%0Aaaa
