### ISSUE TITLE
Incorrect escaping behavior

### ISSUE THREAD

**Issue by franckchen** [remarkjs/remark#1382]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

remark-parse@11.0.0

### Link to runnable example

https://stackblitz.com/edit/github-orec8z?file=src%2Fmain.ts

### Steps to reproduce

https://stackblitz.com/edit/github-orec8z?file=src%2Fmain.ts

When multiple escape characters appear, the escape characters are lost.

For example, if the markdown content is \\[, the result is [, and a \ is missing.

Even when the input is \\\[, the output is still [

### Expected behavior

 Output \[

### Actual behavior

Output [

### Affected runtime and version

node>18

**Comment by wooorm** [comment]
Please take some time to understand the language (JavaScript) you are using.

You are using a string.

That character in strings has a certain meaning.
