### ISSUE TITLE
Suggestions on integrating smartypants?

### ISSUE THREAD

**Issue by KyleAMathews** [remarkjs/remark#224]
Playing around with https://github.com/wooorm/retext-smartypants and Remark where I visit every text node and run it through smartypants. This works more-or-less but it'll miss converting quotes that are split into separate text nodes...

Thoughts?

**Comment by KyleAMathews** [comment]
Also it's not crazy performant as it's running retext a gazillion times.

**Comment by wooorm** [comment]
I unfortunately have no idea how to properly do that, with retext, currently.

It’s possible for the markdown tree to be converted to a natural language tree, through [remark-retext](https://github.com/wooorm/remark-retext). This keeps positional info intact, and strips the syntax. Thus making it possible for, say, [retext-spell][https://github.com/wooorm/retext-spell] to detect `ex*em*ple` as misspelt and suggest `example` instead.

That three can also be properly modified by [retext-smartypants](https://github.com/wooorm/retext-smartypants).

However, theres no way to merge that tree back into the markdown tree. And I’m not sure how to do it.

Say, staying with the earlier example, `retext-spell` autocorrected `ex**em**ple` to `example`. What happens with the strong node? There’s probably ways to deal with that. [Prosemirror](https://github.com/prosemirror/prosemirror) deals with similar problems, and things like React or  [virtual-dom](https://github.com/Matt-Esch/virtual-dom) of course. But I’m not entirely sure where to start.

😬

**Comment by wooorm** [comment]
Thought about this a short while, we probably need:

* `unist-util-diff` (`Array.<Patch> = diff(Node, Node)`)
* `mdast-util-patch-from-nlcst` (`Array.<Patch> = patchFromNLCST(Node, Array.<Patch>)`)
* `unist-util-patch` (`patch(Node, Array.<Patch>)`)

the diff and patch would be ok, but changing nlcst patches to mdast patches is hard, I think.

**Comment by wooorm** [comment]
I’ve updated the above, as [`unist-diff`](https://github.com/syntax-tree/unist-diff) is now a thing!

**Comment by KyleAMathews** [comment]
Nice! These look like super useful utilities (even beyond this use case).

**Comment by wooorm** [comment]
Still unsure how to do this. I never really got the utilities to work. Transforming stuff with retext and then merging the changes back into remark is, well, hard.
Something for a far future, maybe!
