### ISSUE TITLE
Footnotes parsed as images?

### ISSUE THREAD

**Issue by vhf** [remarkjs/remark#283]
Not sure this is a bug or an expected Markdown behaviour.

`Hello![^footnote]` has `![^footnote]` parsed as an image:

    imageReference (1:6-1:18, 5-17) [identifier="^footnote"][referenceType="shortcut"]

If this is considered as a bug, a fix might be to not allow `imageReference`'s `identifier`s to start with a caret (`^`) when `remark` is configured with `footnotes: true`.

**Comment by wooorm** [comment]
When I refactored the footnote stuff recently, I saw that for a second, and actually though that this wouldn’t show up that much, but your example is quite convincing, so I’ll do that in the next major!

**Comment by vhf** [comment]
Thanks a bunch!

**Comment by wooorm** [comment]
Done!
