### ISSUE TITLE
Migrate projects to remarkjs organisation

### ISSUE THREAD

**Issue by niftylettuce** [remarkjs/remark#291]
To ensure this project is stable in case of any issues - it's not great having just one person having access to NPM / GitHub for such widely used package.

**Comment by dherges** [comment]
Speaking for myself, I ma also willing to move the plugin [remark-embed-images](https://github.com/dherges/remark-embed-images) to that GitHub / npm org!

**Comment by wooorm** [comment]
We should definitely move, but I don’t have much time to do it right now. When I’m ready to cut a new release (which should also be soon), I’ll move stuff over to a separate organisation (`remarkjs`).

On the organisation, I’d like a separate issue tracker for people to suggest new plugins.
Currently there are some on this tracker, so I’ll link those to this issue, and then later to the separate tracker.

**Comment by wooorm** [comment]
All done btw, feel free to open new plugin ideas in [`remarkjs/ideas`](https://github.com/remarkjs/ideas)!

**Comment by niftylettuce** [comment]
you rock. thanks!!!
