### ISSUE TITLE
Remark change &reg into ® in URL

### ISSUE THREAD

**Issue by Joxit** [remarkjs/remark#307]
At each instance of the `& reg` element, remark transforms it to ®, even in URLs.

Input is :
```markdown
[example 1](http://www.example.com?param=1&region=here)
http://www.example.com?param=1&region=here
`http://www.example.com?param=1&region=here`
```

Output is :
```markdown
[example 1](http://www.example.com?param=1®ion=here)
<http://www.example.com?param=1®ion=here>
`http://www.example.com?param=1&region=here`
```

I think it should have an exception on URL formatting.

**Comment by wooorm** [comment]
That has to do with non-terminated entities being allowed in HTML, but we can switch to [`nonTerminated: false`](https://github.com/wooorm/parse-entities#optionsnonterminated) in our usage of `parse-entities`.

That’s a breaking change though, so I’ll bundle that up with other breaking changes!
