### ISSUE TITLE
A heading immediately after a list element is parsed as an item of that list

### ISSUE THREAD

**Issue by SimenB** [remarkjs/remark#313]
Originally reported to prettier: https://github.com/prettier/prettier/issues/3247

See http://astexplorer.net/#/gist/e3eaf84774057db35a17b3065aa3f8a3/69aa50de7bc313fad863946ebe318aa88d288afa

**Comment by wooorm** [comment]
Would you be interested in working on this?

As a pointer, you can add tokenisers to [`interruptList`](https://github.com/wooorm/remark/blob/86b049a0ca0e499c1aa06894c6bd7755c59dc9b9/packages/remark-parse/lib/parser.js#L63-L77)!
