### ISSUE TITLE
Configuring remark()

### ISSUE THREAD

**Issue by tmcw** [remarkjs/remark#314]
Somehow I've never done this before, but I'm wanting to configure `remark` - specifically to turn `commonmark` on. I'm not seeing any API documentation that makes it clear how to do that: [remark-parse](https://github.com/wooorm/remark/tree/master/packages/remark-parse#usage) demonstrates how to configure remark-parse when using unified, [remark](https://github.com/wooorm/remark/tree/master/packages/remark) doesn't have API documentation as far as I can see.

From reading the tests, it looks like [data('settings](https://github.com/wooorm/remark/blob/master/test/remark.js#L40) is the way to do this, and I can see [data](https://github.com/unifiedjs/unified#processordatakey-value) documented in unified, but can't find anywhere that says 'settings' is a supported value. Maybe I'm missing a clear example for this that's in a different readme?

**Comment by wooorm** [comment]
Yes, passing the settings though data is the suggested way to do that! The docs got lost when I started preferring using unified directly over remark.

For example, like this on the API:

```js
remark()
  .data('settings', {commonmark: true})
  // ...
```

However, maybe simpler, is using a [preset](https://github.com/unifiedjs/unified#preset):

```js
remark()
  .use({settings: {commonmark: true}})
  // ...
```

--- 

I think I should add docs for this in the [remark readme](https://github.com/wooorm/remark/tree/master/packages/remark#readme) though. Could you tell me:

- Where you looked?
- Given the above info, what sort of docs did you expect?

**Comment by tmcw** [comment]
Sure: I looked

- [remark readme](https://github.com/remarkjs/remark), [packages/remark](https://github.com/remarkjs/remark/tree/master/packages/remark) readme, [unified readme](https://github.com/unifiedjs/unified), [remark.js.org](http://remark.js.org/)
- I kind of expect the [packages/remark](https://github.com/remarkjs/remark/tree/master/packages/remark) readme to include details about how it is a restricted/specific subset of unified - for instance, this `'settings'` key appears to be a special recognized value by the `data()` function, only to remark - so it doesn't fit in the unified documentation. It's fine if most of the docs are handled by unified, but ideally the remark documentation makes it clear how remark sets up unified and what the API surface of remark-parse becomes.
- Also, specifically, the [options documentation in processor.use](https://github.com/remarkjs/remark/tree/master/packages/remark-parse#processoruseparse-options) says that the options can be passed through processor.data(), but nothing more than that: given that minimal information, I'd likely guess that the syntax was

```js
remark()
  .data({commonmark: true})
```

not

```js
remark()
  .data('settings', {commonmark: true})
```
