### ISSUE TITLE
Remove support for seeing non-ASCII whitespace as such

### ISSUE THREAD

**Issue by maximbaz** [remarkjs/remark#321]
### Subject of the issue

```
preserve leading and trailing no-break whitespaces in inline code: `   hello   `
```

Markdown strips regular whitespaces: `   hello   `
However it preserves non-breaking whitespaces: `   hello   `

Parser should also preserve non-breaking whitespaces, while stripping regular ones.

### Steps to reproduce

[astexplorer](http://astexplorer.net/#/gist/981820a08e2310097ed01236175fcaf7/880d65bab3c76e74913fc6fd74f9c22c3c8103fc)

### Expected behaviour

```
{
  "type": "root",
  "children": [
    {
      "type": "paragraph",
      "children": [
        {
          "type": "text",
          "value": "preserve leading and trailing whitespaces in inline code: ",
        },
        {
          "type": "inlineCode",
          "value": "   hello   ",
        }
      ],
    }
  ],
}
```

### Actual behaviour

```
{
  "type": "root",
  "children": [
    {
      "type": "paragraph",
      "children": [
        {
          "type": "text",
          "value": "preserve leading and trailing whitespaces in inline code: ",
        },
        {
          "type": "inlineCode",
          "value": "hello",
        }
      ],
    }
  ],
}
```

**Comment by wooorm** [comment]
Hey @maximbaz!

I tried it on the [commonmark dingus](http://spec.commonmark.org/dingus/) (permalinking doesn’t work for me there) and it didn’t have your result. Why do you believe markdown should act like this?

P.S. GitHub does show them: preserve leading and trailing no-break whitespaces in inline code: `   hello   `

**Comment by maximbaz** [comment]
Hey, this all started because I have a variable with trailing whitespace as a default value, and this is documented in a markdown file (example below). I noticed that Github removes the trailing whitespace, and then I was suggested to use a non-breaking whitespace because Github keeps it. However, `prettier` (which uses this project internally) auto-formats my markdown document and removes the trailing whitespace, which is annoying 🙂

![image](https://user-images.githubusercontent.com/1177900/35051051-9ecf38ca-fba4-11e7-966c-d4b337db7374.png)

Now I see that apparently multiple markdown specifications exist (of course 🤦‍♂️ ), and not all of them preserve non-breaking whitespaces... What do you usually do in such cases? Follow commonmark's specification and not github's?

**Comment by maximbaz** [comment]
Actually, can it be a bug in commonmark dingus?

http://spec.commonmark.org/0.28/#code-spans

> The contents of the code span are the characters between the two backtick strings, with leading and trailing **spaces** and line endings removed

http://spec.commonmark.org/0.28/#space

> A space is U+0020.

**Comment by wooorm** [comment]
It could be! I dunno?!

Anyway, unrelated to this bug, but related to your original question: what I personally do in these cases of invisible characters is use the middot characters: `foo··` (where `·` represents a space), similar to `»` for tab, `␊` for `\n` and `␍␊` for `\r\n`.

**Comment by maximbaz** [comment]
This is an interesting approach, thanks for sharing!

**Comment by wooorm** [comment]
Could you check with commonmark to see if it’s a bug in their code / dingus?

- If that’s a case, and they should follow GFM instead, I feel we should support this here too
- If it’s in fact GFM not following the commonmark spec, I’m not sure we should do something here...

**Comment by maximbaz** [comment]
It was easy, here's owner of commonmark repo explaining that [non-breaking space should **not** be stripped](https://github.com/commonmark/CommonMark/issues/366#issuecomment-138959948), and [this ticket in commonmark.js](https://github.com/commonmark/commonmark.js/issues/132) is describing what looks like a pretty much the same issue.
