### ISSUE TITLE
Code fence with no language is rewritten as indented

### ISSUE THREAD

**Issue by kentcdodds** [remarkjs/remark#322]
### Subject of the issue

I want code fences which do not have a language specified to remain in a code fence when they're re-printed (just like those which do have a language specified). This is more about consistency than stylistic preference (though I do prefer it stylistically as well). It's also more convenient because it makes it easier to add a language later.

### Your environment

*   Name and version of operating system - N/A
*   Names and version of required packages - `remark-cli@4.0.0`
*   Version of node and npm, or names and versions of browser - N/A

### Steps to reproduce

Here's my reproduction: https://github.com/kentcdodds/remark-code-fences-issue

Here's [the input](https://raw.githubusercontent.com/kentcdodds/remark-code-fences-issue/master/README.md): 

<details>
<summary>input</summary>

````
I want all of this to be printed as it appears after remark processes it.

Pretty much I just want non-language code fences to remain code fences.

```
This code fence has no language specified
```

```javascript
this.codeFence = 'is JavaScript'
```

I think it's a consistency issue. I'm fine if it reprints already indented code blocks as indented, but if I wrap it in a code fence it should be reprinted as a code fence.

I expect this means we'll have to store metadata on the AST for code blocks to distingish whether the source is code fenced? Maybe?

See the `output.md` file to see what the output of `remark README.md > output.md` is
````

</details>

Here's [the output](https://raw.githubusercontent.com/kentcdodds/remark-code-fences-issue/master/output.md):

<details>
<summary>output</summary>

````
I want all of this to be printed as it appears after remark processes it.

Pretty much I just want non-language code fences to remain code fences.

    This code fence has no language specified

```javascript
this.codeFence = 'is JavaScript'
```

I think it's a consistency issue. I'm fine if it reprints already indented code blocks as indented, but if I wrap it in a code fence it should be reprinted as a code fence.

I expect this means we'll have to store metadata on the AST for code blocks to distingish whether the source is code fenced? Maybe?

See the `output.md` file to see what the output of `remark README.md > output.md` is
````

</details>

### Expected behaviour

The output markdown code should look exactly like the input.

### Actual behaviour

The output markdown code has the code fence without a language specified as an indented code block.

**Comment by erquhart** [comment]
It's not that the language has to be indicated, but that fences aren't on by default in Remark. Just add a .remarkrc file or `remarkConfig` property in your package.json with the following value:

```
{
  "settings": {
    "fences": true
  }
```

**Comment by kentcdodds** [comment]
Awesome. Thanks for that! How would I do this with the `remark` package programmatically?

**Comment by erquhart** [comment]
You can pass a settings object in via `use`:

```javascript
remark()
  .use({
    settings: {
      fences: true,
    },
  })   
```

Here's a live example based on your sample input: https://runkit.com/erquhart/5a60f4bc0e0bc000124e132d

And docs: https://github.com/remarkjs/remark/tree/master/packages/remark

**Comment by kentcdodds** [comment]
Thanks! I'll give that a try!

**Comment by kentcdodds** [comment]
That worked perfectly! Thanks a bunch!

While I'm here, I discovered that this:

`````
I am markdown and I'm giving an example of markdown:

````markdown
This is an example of markdown

```
and this is code inside the markdown example inside markdown
```

This is the end of the markdown example
````
`````

Will be transformed to this:

`````
I am markdown and I'm giving an example of markdown:

````markdown
    This is an example of markdown

    ```
    and this is code inside the markdown example inside markdown
    ```

    This is the end of the markdown example
````
`````

Then if I run it again, that'll be transformed to this:

`````
I am markdown and I'm giving an example of markdown:

````markdown
        This is an example of markdown

        ```
        and this is code inside the markdown example inside markdown
        ```

        This is the end of the markdown example
````
`````


And so on and so on... To be clear, what's happening is if you have a code fence inside a markdown code fence, everything inside the markdown code fence is indented 4 spaces. This happens whether `fences` is `true` or `false`.

Should I open a new issue for this? Or am I doing something wrong?

**Comment by erquhart** [comment]
I'd assume Remark is using a non-configured Remark instance for that output, not certain how you'd go about changing that.

@wooorm?

**Comment by erquhart** [comment]
Odd, still happens without the "markdown" syntax designation, and it only indents if a code block is present. This is valid gfm, so I suspect it's a bug.

**Comment by kentcdodds** [comment]
I'll go ahead and open a new bug report with a reproducible example.

**Comment by kentcdodds** [comment]
Filed the issue here: https://github.com/remarkjs/remark/issues/323

**Comment by wooorm** [comment]
Thanks for the detailed info Kent, and for helping Shawn, and sorry about the slow reply!
Looks like this original issue is answered correctly, but I’ll respond to the other issue with some more info about it!
