### ISSUE TITLE
Nested code fence is indented

### ISSUE THREAD

**Issue by kentcdodds** [remarkjs/remark#323]
### Subject of the issue

This is a continuation from the bug found in #322 

### Your environment

*   Name and version of operating system - N/A
*   Names and version of required packages - `remark@8`
*   Version of node and npm, or names and versions of browser - N/A

### Steps to reproduce

Here's a reproducible example: https://runkit.com/5a6136fdb1e8430012930517/5a6136fed6b02b001283e07b

Here's what happens:

`````
I am markdown and I'm giving an example of markdown:

````markdown
This is an example of markdown

```
and this is code inside the markdown example inside markdown
```

This is the end of the markdown example
````
`````

Will be transformed to this:

`````
I am markdown and I'm giving an example of markdown:

````markdown
    This is an example of markdown

    ```
    and this is code inside the markdown example inside markdown
    ```

    This is the end of the markdown example
````
`````

Then if I run it again, that'll be transformed to this:

`````
I am markdown and I'm giving an example of markdown:

````markdown
        This is an example of markdown

        ```
        and this is code inside the markdown example inside markdown
        ```

        This is the end of the markdown example
````
`````

And so on and so on... To be clear, what's happening is if you have a code fence inside a markdown code fence, everything inside the markdown code fence is indented 4 spaces. This happens whether `fences` is `true` or `false`.

### Expected behaviour

It should not change the input code at all

### Actual behaviour

It indents the nested code fence 4 spaces.

**Comment by erquhart** [comment]
Note: this occurs with or without the "markdown" syntax indication, it's the combination of four backticks with a nested code block that causes everything inside of the four backticks block to be indented.

**Comment by erquhart** [comment]
Ah, seems this is intentional: https://github.com/remarkjs/remark/commit/84e84d833fba6c48f34cb97dd49e042e97c4fe12

**Comment by kentcdodds** [comment]
Interesting... It doesn't seem to cause trouble on GitHub anymore though as I'm using it above in this comment. Also, I'm processing the same file regularly and it's going to continue to indent forever. So that at least it's still a bug.

Thanks for having that commit. That will make it easier to know how to fix this. Now we just need to decide what the fix will be. I'm thinking we basically revert that 2 year old commit (manually). I think the issue it's trying to solve is no longer an issue.

**Comment by wooorm** [comment]
Thanks both! I fixed it, see the commit message for some more detail! I agree with you Kent: it’s no longer an issue, and I just essentially reverted the commit!

**Comment by kentcdodds** [comment]
Thank you so much!
