### ISSUE TITLE
HTML code block peculiarities

### ISSUE THREAD

**Issue by matthewmueller** [remarkjs/remark#326]
Hey bud, thanks for putting this project together. I'm trying to parse HTML blocks within markdown and I'm running into an inconsistency:

```js
const markdown = require('remark-parse');
const fn = unified().use(markdown, { position: false })

const ast = fn.parse(`
<a>
  hey **yo**
</a>
`)

console.dir(ast, { depth: Infinity, colors: true})
```

produces:

```js
{ type: 'root',
  children: [ { type: 'html', value: '<a>\n  hey **yo**\n</a>' } ] }
```

I'd have expected it to break it apart. The following other cases **do work** as I'd expect.

---

```js
const markdown = require('remark-parse');
const fn = unified().use(markdown, { position: false })

const ast = fn.parse(`
<a>hey **yo**</a>
`)

console.dir(ast, { depth: Infinity, colors: true})
```

produces:

```js
{ type: 'root',
  children:
   [ { type: 'paragraph',
       children:
        [ { type: 'html', value: '<a>' },
          { type: 'text', value: 'hey ' },
          { type: 'strong', children: [ { type: 'text', value: 'yo' } ] },
          { type: 'html', value: '</a>' } ] } ] }
```

---

```js
const markdown = require('remark-parse');
const fn = unified().use(markdown, { position: false })

const ast = fn.parse(`
<a>

hey **yo**

</a>
`)

console.dir(ast, { depth: Infinity, colors: true})
```

produces:

```js
{ type: 'root',
  children:
   [ { type: 'html', value: '<a>' },
     { type: 'paragraph',
       children:
        [ { type: 'text', value: 'hey ' },
          { type: 'strong', children: [ { type: 'text', value: 'yo' } ] } ] },
     { type: 'html', value: '</a>' } ] }
```

---

I'm thinking the first case would probably mirror how `<a>hey **yo**</a>` parses and not how `<a>\n\nhey **yo**\n\n</a>` parses.

**Comment by wooorm** [comment]
Hi Matthew! 👋

Yup, I agree it’s weird. But I don’t think [Commonmark](http://spec.commonmark.org/dingus/), [markdown-it](https://markdown-it.github.io), or GFM think it’s weird:

<a>
  hey **yo**
</a>

There are some subtle difference between tags, as `<div>*yo*</div>` would not work, but because `<a>` is not a known block element, it does get it’s contents transformed from markdown.

So, I don’t think remark should support this by default. You could a) add support for this with a plugin though, overwriting the [`blockHTML`](https://github.com/remarkjs/remark/blob/master/packages/remark-parse/lib/tokenize/html-block.js) function, or b) teach yourself to use blank lines between stuff!

What do you think?

**Comment by matthewmueller** [comment]
@wooorm thanks for the info! 2 followups:

> There are some subtle difference between tags, as <div>*yo*</div> would not work

Why doesn't this work? At first glance, it seems like it should compile to `<div><em>yo</em><div>`.

> So, I don’t think remark should support this by default. You could a) add support for this with a plugin though, overwriting the blockHTML function, or b) teach yourself to use blank lines between stuff!

I'd be happy to extend this, do you have any example code I could take a look at that would be similar-ish?

Thanks!

**Comment by wooorm** [comment]
Sure no probs!

> Why doesn't this work? At first glance, it seems like it should compile to `<div><em>yo</em><div>`.

There’s different handling of known block and non-block HTML elements in markdown 🤷‍♂️

> I'd be happy to extend this, do you have any example code I could take a look at that would be similar-ish?

The docs for [extending the parser](https://github.com/remarkjs/remark/tree/master/packages/remark-parse#extending-the-parser) may help here. I don’t think there’s an example where HTML handling is changed like this though, but you’d probably want to reimplement the [`blockHTML`](https://github.com/remarkjs/remark/blob/master/packages/remark-parse/lib/tokenize/html-block.js) code I previously linked to!

**Comment by matthewmueller** [comment]
Got it – thanks a lot for your help!
