### ISSUE TITLE
Provide Demo

### ISSUE THREAD

**Issue by fritz-c** [remarkjs/remark#335]
It would be nice to have a demo of the basic functionality of remark (and maybe plugin demonstration would also be nice in the future). I threw together a basic example on codesandbox. At worst, you could add a link to a fork of that sandbox somewhere in the readme.
https://3vnx23qny5.codesandbox.io/

**Comment by wooorm** [comment]
@fritz-c For the parsing, we already have [astexplorer](https://astexplorer.net), but as remark (or rather, unified) can take anything and spit anything out, I’m not sure how useful demo is compared to [runkit](https://npm.runkit.com/remark)?

**Comment by fritz-c** [comment]
Ok, that makes sense.
