### ISSUE TITLE
feature request: --cache similar to ESLint for remark-cli?

### ISSUE THREAD

**Issue by Trott** [remarkjs/remark#338]
### Subject of the issue

It would be useful for Node.js core if remark-cli had a --cache option similar to that used in ESLint. We fake it right now in our Makefile by generating a timestamp file and only linting if the directory of markdown files was modified after the timestamp file. This works OK in most situations but has the following disadvantages:

* If only one file changes, it re-lints the entire directory instead of just the file that changed.
* If our rules change, it's not smart enough to know that it needs to re-lint everything. (ESLint knows that its cache is invalid if the config settings are changed.)
* If remark-cli itself is updated, the Makefile does not know to re-lint everything. (Again, ESLint knows that its cache is invalid if the cache was generated by a different version of ESLint.)

### Your environment

*   macOS 10.13.5
*  `remark-cli`, `remark-preset-lint-node`
*  `node` 10.4.1, `npm` 6.1.0

### Steps to reproduce

We use something like `remark-cli/cli.js -q -f doc` where `doc` is a directory with a lot of markdown files. Ideally, it would be great if we could pass `--cache` to generate a `.remarklintcache` file the way ESLint generates an `.eslintcache` file.

### Expected behaviour

With the cache file, running the command again and again should be much faster (unless all the files change, a rule is changed, or the version of `remark-cli` is updated).

### Actual behaviour

Well, the feature isn't implemented so I get the `remark-cli` help message.

**Comment by Murderlon** [comment]
I will give this a shot this weekend :)
Also, this feature will live in the underlying `unified-engine`, the already existing issue can be found here 👉 https://github.com/unifiedjs/unified-engine/issues/22

**Comment by Murderlon** [comment]
Turns out I'm completely packed till I leave for vacation in two weeks so I won't be able to do this for at least a month. To not claim a stale contribution, consider me out until I say here otherwise. So if anyone is excited to pick this up you don't have to hesitate :)
