### ISSUE TITLE
Support for fenced code block info string

### ISSUE THREAD

**Issue by arobase-che** [remarkjs/remark#342]
Hi,

I'm looking for a support for fenced code block info string. It's not a regular markdown but it's pretty commun and both [GFM](https://github.github.com/gfm/#info-string) and [CommonMark](https://spec.commonmark.org/0.28/#info-string) spec it.

If i implement it and make a pull request, will it be merged or should i make a plugin ?

Thanks ! :wink:

**Comment by ChristianMurphy** [comment]
Since it is part of the common mark spec, I'd personally lean toward including this in remark directly.

---

It'd be good to get the specification example as a test

```markdown
~~~~    ruby startline=3 $%@#$
def foo(x)
  return 3
end
~~~~~~~
```

https://spec.commonmark.org/0.28/#example-112

---

and also would be good to get the MDAST spec updated with the new attribute
https://github.com/syntax-tree/mdast#code

**Comment by arobase-che** [comment]
Arf, in fact ... While discussing with @hypercube he remarked to me that the info string is the whole string. In you example "ruby starline=3 $%@#$". Which is exactly the value of the "lang" attribute.

So "lang" **is** actually the info string. Now "lang" is the info string, but it's used by other plugins as the first word of the info string as it's name suggests it is.

I will make a PR soon fix it.

**Comment by Hypercubed** [comment]
The name is @hypercubed...  :)

Anyway, yeah, from the spec:

> The content of a code fence is treated as literal text, not parsed as inlines. The first word of the info string is typically used to specify the language of the code sample, and rendered in the class attribute of the code tag. However, this spec does not mandate any particular treatment of the info string.

So, if you want to keep backword compat, the "info string" should be the whole string and `lang` should be the first word of teh info string.  This might be breating for existing code that look for the full info string in `lang`...  (it will break me, but for the greater good?).

**Comment by wooorm** [comment]
@Hypercubed Yeah I was thinking something along those lines, a `code.infoString` being the whole thing, `lang` being the first “word”? It’s breaking, but more fixing.

@arobase-che Thanks for the issue! Sorry for the slow response. I’m also happy to see how you worked “remark” in your comment (“...he remarked to me...”) 😛

**Comment by arobase-che** [comment]
needs pr you said ?

Ok let's go. Where are the tests about remark-parse ? I only found [that file](https://github.com/remarkjs/remark/blob/02297a5dea290751a0bfd766b4154ad403307b7e/test/remark-parse.js).

**Comment by ChristianMurphy** [comment]
There are also fixtures https://github.com/remarkjs/remark/tree/02297a5dea290751a0bfd766b4154ad403307b7e/test/fixtures
Each text file in `input/` has a matching JSON file in `tree/`.

**Comment by arobase-che** [comment]
Ty :+1: 

_____

~~~shell
05:30:55  ~/g/r/t/fixtures/tree  grep -rw '"lang"' | wc -l
853
~~~

Oups ! That's a lot of files >_<
Should i add the "infoString" attribute along with the "lang" one ?

If yes, will finish by the day.

**Comment by ChristianMurphy** [comment]
yes, `lang` and `infoString` :+1: 

---

It would also help to document the new attribute at https://github.com/syntax-tree/mdast/blob/master/readme.md#code

**Comment by wooorm** [comment]
@arobase-che You can run `node script/regenerate-fixtures` to regenerate all output trees, you don‘t have to do that manually!

So you can write the code, add an `input/` fixture, create a corresponding `tree/` one (contents has to be json but otherwise doesn’t matter), and run `regenerate-fixtures`. You can then check with git diff what changes are made to all the fixtures with the new algorithm!

**Comment by arobase-che** [comment]
Ty @wooorm 

I still on it.

**Comment by arobase-che** [comment]
And a PR on syntax-tree/mdast#22

**Comment by arobase-che** [comment]
Hi,
Is there anything I can do to help ?
Is everything ok ?
 :grinning:
