### ISSUE TITLE
Support for code blocks inside HTML

### ISSUE THREAD

**Issue by gjuchault** [remarkjs/remark#343]
### Subject of the issue

Using HTML in markdown, you can't have code blocks inside HTML elements.

### Your environment

*   remark@7.0.1
*   gatsby-transformer-remark@1.7.44

### Steps to reproduce

```
# Some markdown title

<table>
   <tbody>
      <tr>
         <td>
            ```
            foobar()
            ```
         </td>
         <td>
            ```
            foobaz()
            ```
         </td>
      </tr>
   </tbody>
</table>
```

### Expected behaviour

Having the code blocks parsed (I also use gatsby-remark-prismjs). They actually use `visit(ast, 'code', ...)`, so I'm guessing remark is not outputting those code blocks as block elements, but as text nodes

### Actual behaviour

I'm having plain string inside my <td>

**Comment by wooorm** [comment]
@gjuchault You should be able to do that, but you need a blank line between markdown and block-HTML!

**Comment by gjuchault** [comment]
So I've tried a few things 

```
        <tr>
            <td>
              ```
              	foobar()
              ```
            </td>
```

outputs 

```
        <tr>
            <td>```foobar()```</td>
```

I tried the following:

```
        <tr>
            <td>

              ```
              foobar()
              ```

            </td>
            <td>
```

Which gave:

```
<tr>
            <td><div class="gatsby-highlight" data-language="text">
      <pre class="language-text"><code class="language-text">          ```foobar()```

        &lt;/td&gt;
        &lt;td&gt;
          ```foobar()```
        &lt;/td&gt;
    &lt;/tr&gt;
&lt;/tbody&gt;</code></pre>
      </div></td></tr>
```

Visual result:
![image](https://user-images.githubusercontent.com/678848/43050977-deb527d8-8e11-11e8-8ea5-02a6efac7a47.png)


I also tried (I had to replace with backticks as GitHub is using markdown):
```
        <tr>
            <td>

BBBsql
INSERT INTO users(user_id,
                  age,
                  name)
VALUES ("f62255a8259f",
        30,
        Peter)
BBB

            </td>
            <td>
              BBBjs
                  foobar()
              BBB
```

Which gave:
![image](https://user-images.githubusercontent.com/678848/43051037-c5bad0d8-8e12-11e8-84f8-b2b5f726ca1d.png)

**Comment by gjuchault** [comment]
Sorry for the log posts and unclear example. It might be related to <table> structure and browser forcing tag close. As you might know, a <td> is not supposed to have spaces inside.

React actually warns me (about <table>, <thead>, etc.):

index.js:2177 Warning: validateDOMNesting(...): Whitespace text nodes cannot appear as a child of <table>. Make sure you don't have any extra whitespace between tags on each line of your source code.

**Comment by wooorm** [comment]
Thanks for the detailed results! I believe the problem is the indentation. Anything of four spaces or more is seen as indented code, not code blocks or HTML.

[But this should work!](https://astexplorer.net/#/gist/f8dc6bdedda70550f613844394652cf1/2330319cc51fcbff5b11c22ad3d5b4c650964056)

**Comment by gjuchault** [comment]
@wooorm Thank you for you nice example. I was indeed able to make it work without indentation.
I'm not sure wether this issue should stay open (if you think avoiding indentation is a part of the Markdown spec) or not :)

**Comment by wooorm** [comment]
Hmm, yeah I think this is just related to how markdown works.

Note that you could always start out with HTML, and embed markdown in it (e.g., by using a class of some sort on an HTML element). But then you need a new (gatsby) plugin.

Anyway I hope this helped! 👍
