### ISSUE TITLE
[CommonMark] Leading/trailing newlines are stripped in the value of fenced codeblock

### ISSUE THREAD

**Issue by ikatyang** [remarkjs/remark#351]
### Subject of the issue

`commonmark: true`

````md
```


123


```
````

### Steps to reproduce

[astexplorer](http://astexplorer.net/#/gist/1837dd975fffe3816f33417ad0cf5273/3e4bf65b1dfbed052c28785c66d5a0317ad1fa67)

### Expected behaviour

Same as [CommonMark playground](https://spec.commonmark.org/dingus/?text=%60%60%60%0A%0A%0A123%0A%0A%0A%60%60%60):

```json
{
  "type": "code",
  "lang": null,
  "value": "\n\n123\n\n"
}
```

### Actual behaviour

```diff
 {
   "type": "code",
   "lang": null,
-  "value": "\n\n123\n\n"
+  "value": "123"
 }
```

Original post: prettier/prettier#5037

**Comment by wooorm** [comment]
@evilebottnawi Definitely! But we should also get a release out the door 🚪🛳

I’m hoping to get GH-345, GH-346, and potentially GH-321 in there though!
