### ISSUE TITLE
Position seems wrong for indented code blocks.

### ISSUE THREAD

**Issue by tolmasky** [remarkjs/remark#353]
If I have an indented code block, I would expect the column on the code Node to represent this. For example:

```markdown
   ``` javascript
   5 + 5
   \```
```

(forgive the backslash, I don't know how else to prevent the markdown code block from ending prematurely).

Here, the position will be column:1, line:1 for start. Of course, perhaps the `Position` refers to the theoretical resultant "Code Block" which will indeed simply be attached to the left. However, my goal with the `Position` is to be able to accurately report an error to the user. For example, say I syntax check code blocks, if I want to tell them what line/column their error occurs in their actual file, the Position isn't super useful here. Is there a different position I can check with this, or is `Position` indeed incorrect and it should be reporting column:3 in the above example?

**Comment by wooorm** [comment]
You can write markdown code like this:

````markdown
this block has 4 ticks, and a markdown language

```javascript
console.log('this block has ', 2 + 1, 'ticks, and a javascript language')
```

````

For your question, it’s because initial white-space is also part of the node. We recently talked about it in the issue GH-340!

What do you think?

**Comment by tolmasky** [comment]
Hi @wooorm,

Thanks for the speedy reply. I just read through the other issue and it if I understand correctly if seems that column and indent do in fact represent values in “markdown land” vs. the original source (whereas offset seems to represent a value from the original source). In my case, I wasn’t even doing anything complex like nesting in a list, just indenting a code block 50 spaces to see what would happen and observing the values staying at 1 (example: https://runkit.com/tolmasky/remark-indent-example ).

I saw in the bug that it may be possible to work backwards from offset and column to determine the original column, but this seems somewhat unfortunate given that the remark parser almost certainly has this information at *some point*, so it would be nice to not have to effectively reparse sections of the document after the fact. Would it be possible to just include originalPosition or something like that in the object? It seems that there really are just two different kinds of positions, so hopefully it makes sense to include both.

**Comment by wooorm** [comment]
> In my case, I wasn’t even doing anything complex like nesting in a list, just indenting a code block 50 spaces to see what would happen

That sounds pretty complex 😉

> given that the remark parser almost certainly has this information at some point

Yes, the parser has that, and you are able to retrieve that value again in a plugin by checking the input document and the syntax-tree, and doing a bit of math and calculation on your own.

> Would it be possible to just include originalPosition or something like that in the object? It seems that there really are just two different kinds of positions, so hopefully it makes sense to include both.

Not in the remark AST. FWIW, I’m working on something in the next half year that will have this and will properly deal with all this. But it’s not something that should be in remark I think.
