### ISSUE TITLE
remark does not parse metadata at the beginning of a document 

### ISSUE THREAD

**Issue by luca3m** [remarkjs/remark#356]
### Subject of the issue

I see that MDAST supports yaml metadata at the beginning of the document: https://github.com/syntax-tree/mdast#yaml

But remarkjs 9.0.0 does not parse it. Is it just unsupported right now or is a bug?

### Your environment

*  macOs High Sierra
*  node 10.5 and remark 9.0.0

### Steps to reproduce

- create a file like this:

```
---
foo: bar
---

Hello world
```

- run remark:

```
remark --tree-out test.md
```

### Expected behaviour

I would have expected some node holding the whole YAML data as described in the doc above

### Actual behaviour

I see a thematicBreak entry and a `heading` entry

```
{
  "type": "root",
  "children": [
    {
      "type": "thematicBreak",
      "position": {
        "start": {
          "line": 1,
          "column": 1,
          "offset": 0
        },
        "end": {
          "line": 1,
          "column": 4,
          "offset": 3
        },
        "indent": []
      }
    },
    {
      "type": "heading",
      "depth": 2,
      "children": [
        {
          "type": "text",
          "value": "foo: bar",
          "position": {
            "start": {
              "line": 2,
              "column": 1,
              "offset": 4
            },
            "end": {
              "line": 2,
              "column": 9,
              "offset": 12
            },
            "indent": []
          }
        }
      ],
[....]
```

**Comment by wooorm** [comment]
That’s what [`remark-frontmatter`](https://github.com/remarkjs/remark-frontmatter) does!

remark is mostly plugins, see the [list of plugins](https://github.com/remarkjs/remark/blob/master/doc/plugins.md#list-of-plugins) for most of them!

**Comment by wooorm** [comment]
Also, hello! 👋 Sorry, i forgot to say that :)

**Comment by luca3m** [comment]
Thank you for your answer, I tried `remark-frontmatter` and it's indeed working as expected!

**Comment by wooorm** [comment]
Great! Also thanks for getting back to me that it works, most people don’t do that! 🤗
