### ISSUE TITLE
Feature: ability to cleanly disable specific tokenizers

### ISSUE THREAD

**Issue by bjudson** [remarkjs/remark#357]
### Subject of the issue

In order for my project to support a limited subset of Markdown, I want to be able to disable specific tokenizers so that parsing a block of text will just skip over ignored tokens as if they weren't part of the Markdown spec.

### Your environment

N/A

### Steps to reproduce

Since this is a feature request, I'm not sure this is necessary, but I can provide some examples of how the recommended method of disabling tokenizers can break parsing, if that would help.

### Expected behaviour

Disabling tokens should be part of the API. As a first stab, I would suggest adding an `ignoreTokens` key to the `options` object, which takes an array of tokens to ignore. Any parsing code would skip over tokens included in this array.

### Actual behaviour

The documentation for `remark-parse` suggests [deleting tokenizers](https://github.com/remarkjs/remark/tree/master/packages/remark-parse#turning-off-a-tokenizer) from the parser prototype. This works for some tokens, but not others. For instance, deleting the list tokenizer like so:
```
delete remarkParse.Parser.prototype.blockTokenizers.list;
```
Will throw during parse on this line, where a call to `blockTokenizers.list` is hardcoded:
https://github.com/remarkjs/remark/blob/master/packages/remark-parse/lib/tokenize/paragraph.js#L83

In addition, I have found that it's necessary not just to delete the tokenizer from the `inlineTokenizers` and `blockTokenizers` objects on the parser prototype, but also from the following arrays, otherwise the interrupt functions may throw:
* `interruptParagraph`
* `interruptList`
* `interruptBlockquote`

The pull request I created for `react-markdown` to handle this demonstrates how much is required for a client to actually disable arbitrary tokens (and this implementation still doesn't allow ignoring `list` tokens among others):
https://github.com/rexxars/react-markdown/pull/223

**Comment by wooorm** [comment]
@bjudson Thanks for the detailed issue! It makes sense to have a better way.

Any ideas on how a proper and nice interface for this should look like?

**Comment by bjudson** [comment]
@wooorm This is more or less how I imagine this working.

From the user's perspective, they would need to opt-out of parsing specific tokens via options:
```
unified()
  .use(parse, {ignoreTokens: ['blockquote', 'list']})
  .use(html)
  .process("> * a\n* b\n* _c_\n")
  .then(value => console.log(value));

// output
<p>> * a</p>
<p> * b</p>
</p>* <em>c</em></p>
```

Within the library, I see checking the `ignoreTokens` array:
* at the top of the `while` loop in `interrupt()`
* at the top of the `while` loop in `tokenize()`

Then probably add a simple abstraction for the various places that tokenizers call other tokenizers inline, that will check the `ignoreToken` array before executing the call.

**Comment by bjudson** [comment]
@wooorm Any reason I shouldn't get started on a PR for this? Problems with approach described above?

**Comment by wooorm** [comment]
Sorry, I’m busy with hacktoberfest and a lot of other things! Thanks for pinging again! 👍

Could we move the toggling on and off to a new plugin? Such as, `remark-token-control` or something? I love the ecosystem, and think most stuff should go there.
Now, if we need better hooks in the parser, that makes sense, so maybe it’s both a plugin and some changes here, I’m all for that, but I think the “human interface” should go in a plugin, whereas the API may go in the parser.

What do you think?

**Comment by bjudson** [comment]
Makes sense to me! I'll read up on the plugin API and start moving ahead with that approach, then submit a PR for the parser hook(s) when I get a better handle on how the interface should work.

**Comment by bjudson** [comment]
I was going through the plugins to get a better feel for the ecosystem and stumbled on this one, which appears to do exactly what I want:
https://github.com/zestedesavoir/zmarkdown/tree/master/packages/remark-disable-tokenizers

The solution they used is obvious in retrospect, just replace the unwanted tokenizers with a noop function, rather than deleting it. So, instead of making a plugin I can submit a PR to update the `remark-parse` documentation to mention this method, and perhaps recommend the plugin.

**Comment by wooorm** [comment]
Oh nice! 🎉 I forgot about that one, sorry.
Yes. Please do so! 👍

**Comment by msingleton** [comment]
Thanks for the discussion, I'm working on a similar use case to offer a limited set of markdown. The only block tokenizer I can't seem to disable is 'paragraph' (my goal is to have no paragraphs, only <br /> for every \n)

When I disable paragraph using remark-disable-tokenizers I get the error `Infinite loop`.

I assume that's coming from: https://github.com/remarkjs/remark/blob/02297a5dea290751a0bfd766b4154ad403307b7e/packages/remark-parse/lib/tokenizer.js#L115

Which assumes at least one of the block tokenizers will eat, and the paragraph will basically always eat. Any suggestions on how to work around this?

**Comment by wooorm** [comment]
@msingleton Correct, the `paragraph` tokeniser shouldn’t be turned off.
This sounds like an [XY problem](https://meta.stackexchange.com/questions/66377/what-is-the-xy-problem). What is that you exactly want to do?

**Comment by msingleton** [comment]
Gotcha, hah not quite an XY problem, our use case is somewhat unique to our product's UI where have a desire to have all line breaks translate to <br />.

Just wondering if it was possible to turn off that tokenizer and sounds like no, no problem

**Comment by wooorm** [comment]
@msingleton Note that if you include HTML in markdown it’s seen as HTML, so there was a `br` up there, if you want to use code, wrap it in backpacks 😉

Maybe what you’re looking for is [remark-breaks](https://github.com/remarkjs/remark-breaks)?
