### ISSUE TITLE
Linting is broken

### ISSUE THREAD

**Issue by niftylettuce** [remarkjs/remark#359]
Currently using latest versions of `remark-cli` and `remark-preset-github`.  There seems to be a bug with linting, it fixes incorrectly and on the second run reports an error.

```sh
λ ~/Projects/forward-email/ master* node_modules/.bin/remark . -qfo
λ ~/Projects/forward-email/ master* node_modules/.bin/remark . -qfo
README.md
  90:1-90:6  warning  Rules should use `---`  rule-style  remark-lint

⚠ 1 warning
```

**Comment by wooorm** [comment]
Hey nick! This issue doesn’t have enough info to help you. Please see [`contributing.md`](https://github.com/remarkjs/remark/blob/master/contributing.md) for more info!

**Comment by niftylettuce** [comment]
Sorry @wooorm here's how to reproduce:

1. `git clone https://github.com/niftylettuce/forward-email.git`
2. `cd forward-email`
3. `yarn` (or `npm` works too)
4. look at `README.md` contents, specifically line 90 (it has `* * *` now instead of `---`)
5. `node_modules/.bin/remark . -qfo`
6. look at `README.md` contents, specifically line 90 (it has `* * *` now instead of `---`)
7. `node_modules/.bin/remark . -qfo`
8. you will receive the following error output:

    ```sh
    README.md
      90:1-90:6  warning  Rules should use `---`  rule-style  remark-lint
    
    ⚠ 1 warning
    ```

**Comment by niftylettuce** [comment]
additionally the line in question is correct, but despite a `rule-style` of `---` it gets changed

see <https://github.com/niftylettuce/forward-email/blame/master/README.md#L90>

also see https://github.com/niftylettuce/remark-preset-github/blob/master/index.js#L49

**Comment by wooorm** [comment]
So, remark-lint lints, so if there’s `* * *` as a marker, while you expect `---`, it warns.
But remark itself outputs the rule.

To fix your problem, set [`rule: '-'`](https://github.com/remarkjs/remark/tree/master/packages/remark-stringify#optionsrule) and [`ruleSpaces: false`](https://github.com/remarkjs/remark/tree/master/packages/remark-stringify#optionsrulespaces) and you’re fine!

**Comment by niftylettuce** [comment]
@wooorm where exactly would I set this at?  in remark-preset-github somewhere?  a bit confused

https://github.com/niftylettuce/remark-preset-github/blob/master/index.js

**Comment by niftylettuce** [comment]
@wooorm never mind figured it out, need to put it here <https://github.com/niftylettuce/remark-preset-github/blob/master/index.js#L5-L8>!

**Comment by wooorm** [comment]
Nice! Glad you figured it out! 👍

**Comment by natterstefan** [comment]
I had a similar issue with [`listItemIndent`](https://github.com/remarkjs/remark/tree/master/packages/remark-stringify#optionslistitemindent) not properly working together with [`preset-lint-markdown-style-guide`](https://github.com/remarkjs/remark-lint/tree/master/packages/remark-preset-lint-markdown-style-guide). Finally, figured it out after reading https://github.com/remarkjs/remark/issues/359#issuecomment-426063021. Thank you @wooorm.
