### ISSUE TITLE
Easily insert a re-usable footer by including it in config somehow?

### ISSUE THREAD

**Issue by niftylettuce** [remarkjs/remark#362]
It would be great to be able to re-use a common footer across all projects somehow.

Like I have a "Related" section here that I want to automatically have added to the footer, like Contributors.

https://github.com/niftylettuce/email-templates#related

Is there a plugin that already exists for something like this?

I guess I could clone "Contributors" and add to `package.json` a new property called "related_projects" which would be like:

```js
"related_projects": [
  { name: 'Lass', link: 'https://lass.js.org', description: 'Some description that could use **Markdown**' }
]
```

Any thoughts let me know.  It'd be nice to normalize this for other use cases somehow.  Maybe we could abstract https://github.com/hughsk/remark-contributors enough so we could use it for contributors, related_projects, etc.  Not sure... just sharing thoughts

**Comment by wooorm** [comment]
I like that idea, and it doesn’t exist yet! I’d suggest [`remark-license`](https://github.com/remarkjs/remark-license) as a base, as it’s more modern, and already reads `package.json`.

**Comment by niftylettuce** [comment]
Something like this would be cool, and we could use it to generate any table including one for contributors

```js
  "remarkConfig": {
    "plugins": [
      "preset-github",
      [
        "package-to-section",
        {
          addSectionIfNotExists: true
          sections: [
            { header: '# Contributors', property: 'contributors' },
            { header: '# Related Projects', property: 'related_projects' },
            // ...
          ]
        }
      ]
    ]
  },
```

I put a bug bounty on this already since it'd be amazing to have this abstraction.

**Comment by niftylettuce** [comment]
It would be so nice if `package.json` supported an "extends" property 😆.

**Comment by pke** [comment]
@niftylettuce I'll tackle that next. A few questions:

1. The property in the package file should be called `relatedProjects` to stay in the camelCasing used in package.json so far.

2. Couldn't we resolve the related projects by merely naming their npm name or github URL? The plugin could then fetch the required meta info itself.

**Comment by pke** [comment]
Any idea @niftylettuce why my package files markdown in the description is escaped when inserted as children into the markdown?

**Comment by niftylettuce** [comment]
@pke I think due to the tokenizer (see references below)

cc @wooorm can you lend your insight here to this?

ref:
- https://github.com/pke/remark-contributors/blob/add16553f6fd6ae9e1a5495e4650020e15c8bc29//index.js#L221-L224
- https://github.com/remarkjs/remark/tree/master/packages/remark-parse#parserinlinemethods?

**Comment by niftylettuce** [comment]
also curious what you guys think the name for this should be?

unless we can rename `remark-contributors` to `remark-package-to-section` or something?  or @pke can just make a new package for this (using @pke's fork/commits and Lass)?

**Comment by pke** [comment]
Sure I plan to make a new package, I was just working of `remark-contributor` as a start. `remark-package` is not specific enough?
Maybe one of the owners/contributors can create a repo under the `remarkjs` wings using `lass`?

**Comment by wooorm** [comment]
Thanks both!

> Sure I plan to make a new package, I was just working of remark-contributor as a start. remark-package is not specific enough?

Awesome! Thanks for working on this. For the name, I suggest rather being more specific, `remark-package` could be used for very different things!

> Maybe one of the owners/contributors can create a repo under the remarkjs wings using lass?

I’d suggest just creating a repo on your own user or an org, and linking to it from the [list of plugins](https://github.com/remarkjs/remark/blob/master/doc/plugins.md). When it gets traction we can move it to remarkjs!

And finally, I’m slowing this issue here. I prefer to keep this issue tracker for the remark processor. [`remarkjs/ideas`](https://github.com/remarkjs/ideas) is a good place to discuss ideas for the ecosystem (such as plugins like this).
