### ISSUE TITLE
Bug(stringify): stringify mail link with trouble

### ISSUE THREAD

**Issue by imcuttle** [remarkjs/remark#369]
### Steps to reproduce

```javascript
var remark = require("remark")

const md = `[moyuyc95@gmail.com](mailto:moyuyc95@gmail.com).`;

console.log(String(remark().processSync(md)))
// => "<mailto:moyuyc95@gmail.com>.\n"
```

[runkit](https://runkit.com/moyuyc/runkit-npm-remark)

### Expected behaviour

Returns `'[moyuyc95@gmail.com](mailto:moyuyc95@gmail.com).\n'`

### Actual behaviour

Returns `'<mailto:moyuyc95@gmail.com>.\n'`

**Comment by wooorm** [comment]
@imcuttle Why do you think this is a bug? Wouldn’t you want the shorter (more common) usage?

**Comment by imcuttle** [comment]
emmm, It's well, I just measured up to GitHub that has not shorter usage

**Comment by wooorm** [comment]
Ah, you’re right! Interesting.

Could you create a PR? Should be somewhere here: https://github.com/remarkjs/remark/blob/1ba8e98e15aec88c8c3d921bca9ff7a382b4183e/packages/remark-stringify/lib/visitors/link.js#L48-L55
