### ISSUE TITLE
AtxHeading with trailing hashsigns is inconsistent with GFM

### ISSUE THREAD

**Issue by TitanSnow** [remarkjs/remark#374]
https://github.com/remarkjs/remark/blob/78b7aca650f041017b5dc5d1d72a7daa5376433a/packages/remark-parse/lib/tokenize/heading-atx.js#L107

GFM requires at least one space or tab between heading text and trailing hashsigns. For example:
```markdown
### awd###
### awd ###
```
will became

### awd ###

But in remark, the space is not required. The above two will be parsed into same ast:
```json
{
  "type": "root",
  "children": [
    {
      "type": "heading",
      "depth": 3,
      "children": [
        {
          "type": "text",
          "value": "awd"
        }
      ]
    },
    {
      "type": "heading",
      "depth": 3,
      "children": [
        {
          "type": "text",
          "value": "awd"
        }
      ]
    }
  ]
}
```

**Comment by wooorm** [comment]
Ohh you’re right, thanks for noticing! PRs welcome!
