### ISSUE TITLE
Consecutive spaces in inline code is not preserved

### ISSUE THREAD

**Issue by zwz** [remarkjs/remark#393]
### Subject of the issue

IMHO, it is good to keep it the same as what the user inputed in `code` (inline or block).
But I found in inline code consecutive spaces are parsed as one space.

### Steps to reproduce

See https://astexplorer.net/#/gist/0a92bbf654aca4fdfb3f139254cf0bad/cc52d2ef9dfc5b9c510e42217d7d4c279e7610de

**Comment by ChristianMurphy** [comment]
@zwz would you be interested in opening a PR? the relevant code is in https://github.com/remarkjs/remark/blob/master/packages/remark-parse/lib/tokenize/code-inline.js

**Comment by zwz** [comment]
Well, I would like to.
I tried replace the last line of `code-inline.js` with
`return eat(subvalue)({type: 'inlineCode', value: queue})`
Here `queue` keeps all the spaces. But it still does not work.
I think the relevant code lies in the `eat` function.

**Comment by wooorm** [comment]
I cannot reproduce this bug:

```sh
$ cat example.md 
# Hello

`echo '    ' > test.py`

$ ./packages/remark-cli/cli.js --no-config -- example.md 
# Hello

`echo '    ' > test.py`
example.md: no issues found

$ ./packages/remark-cli/cli.js --no-config --inspect -- example.md 
root[2] (1:1-4:1, 0-33)
├─ heading[1] (1:1-1:8, 0-7) [depth=1]
│  └─ text: "Hello" (1:3-1:8, 2-7)
└─ paragraph[1] (3:1-3:24, 9-32)
   └─ inlineCode: "echo '    ' > test.py" (3:1-3:24, 9-32)
example.md: no issues found
```

There is no code to collapse white space when [tokenizing](https://github.com/remarkjs/remark/blob/master/packages/remark-parse/lib/tokenize/code-inline.js) or when [compiling](https://github.com/remarkjs/remark/blob/master/packages/remark-stringify/lib/visitors/inline-code.js).

I think ASTexplorer injects the values in the DOM, where the DOM collapses multiple white space to a single space.
