### ISSUE TITLE
[remark-parse] HTML entity code parsing broken in web worker 

### ISSUE THREAD

**Issue by Jarred-Sumner** [remarkjs/remark#394]
### decode-entity broken in web worker

Web workers don't have a `document` object, but `decode-entity.browser.js` uses `document` to decode the entities. This makes total sense in a regular browser context, but not in a web worker. I think it'd need to use a library for HTML entity decoding to work in a web worker environment.

```js
ReferenceError: document is not defined
    at decodeEntity (decode-entity.browser.js:13)
    at parse (index.js:250)
    at parseEntities (index.js:95)
    at Of.decoder [as decode] (decode.js:33)
    at Of.text (text.js:52)
    at Of.tokenize [as tokenizeInline] (tokenizer.js:58)
    at Of.paragraph (paragraph.js:115)
    at Of.tokenize [as tokenizeBlock] (tokenizer.js:58)
    at listItem (list.js:371)
    at Of.list (list.js:330)
```

### Your environment

* Chrome 73 on macOS

### Steps to reproduce

1. Load `remark-parse` in a Web Worker
2. Feed it input that contains HTML entity codes (e.g. `&lt;`)
3. It raises an exception

### Expected behaviour

It should decode the entities

### Actual behaviour

It throws an error

**Comment by Jarred-Sumner** [comment]
hmmm. Maybe this should actually go in https://github.com/wooorm/parse-entities, since that appears to be the library `remark-parse` uses to parse HTML entities

**Comment by wooorm** [comment]
Yep, should go there!

Hmmm... We were able to shave off a lot of bytes by using the DOM in the browser... But the default is to package the normal build, except for bundlers that pick up on the `browser` field. I’d guess more libraries would have similar problems. I feel like there should be a way to specify that the `browser` field shouldn’t be used if building for web workers?

**Comment by wooorm** [comment]
Seems that webpack let’s you define a [`webworker` as `target`](https://webpack.js.org/configuration/target/). Could you check if that works? If so, we should update the docs here (and in `parse-entities`)

**Comment by wooorm** [comment]
This should be fixable by configuring webpack.
