### ISSUE TITLE
Incorrect HTML with new lines parsing

### ISSUE THREAD

**Issue by 1999** [remarkjs/remark#395]
### Subject of the issue

HTML parsing is sometimes wrong when HTML contains new lines:

```html
<table>
    <tbody>
        <tr><td>1</td></tr>

        <tr><td>2</td></tr>
  </tbody>
</table>
```

### Steps to reproduce

```
var unified = require('unified')
var markdown = require('remark-parse')
var html = `<table>
    <tbody>
        <tr><td>1</td></tr>

        <tr><td>2</td></tr>
  </tbody>
</table>`;
 
var processor = unified()
  .use(markdown);
  
console.log(processor.parse(html));
```
### Expected behaviour

The returned object contains only one child node which is "html"

### Actual behaviour

The returned object contains only three children which are:

1. "html" (value: `<table>\n    <tbody>\n        <tr><td>1</td></tr>`)
2. "code" (value: `    <tr><td>2</td></tr>`)
3. "html" (value: `  </tbody>\n</table>`)

**Comment by 1999** [comment]
Another example:
```
<table>
    <tr>
        <td>
            Text

            One more text
        </td>
    </tr>
</table>
```

**Comment by ChristianMurphy** [comment]
@1999 This behavior is correct.
Here is the same code in the official commonmark reference.
https://spec.commonmark.org/dingus/?text=%3Ctable%3E%0A%20%3Ctbody%3E%0A%20%20%20%20%3Ctr%3E%3Ctd%3E1%3C%2Ftd%3E%3C%2Ftr%3E%0A%0A%20%20%20%20%3Ctr%3E%3Ctd%3E2%3C%2Ftd%3E%3C%2Ftr%3E%0A%20%3C%2Ftbody%3E%0A%3C%2Ftable%3E

the output from the reference parser marks the section after the newline as a code block.

```html
<table> <tbody> <tr><td>1</td></tr> <pre><code>&lt;tr&gt;&lt;td&gt;2&lt;/td&gt;&lt;/tr&gt; </code></pre> </tbody> </table> 
```

**Comment by 1999** [comment]
Thanks Christian, Markdown is a mess (┛ಠ_ಠ)┛彡┻━┻
