### ISSUE TITLE
HTML figure tags are processed as markdown

### ISSUE THREAD

**Issue by CxRes** [remarkjs/remark#400]
Another pathological example! HTML figure tags seem to be treated differently by remark. The tags seem to be left alone and markdown inside gets processed as if `<figure>`  were an inline tag.

As agreed in rehypejs/rehype-raw#8, contents of block elements are not parsed as markdown according to commonmark/gfm rules. 

**I am not using `rehype-raw`.**

 

### Environment

+ Windows 10 x64
+ "rehype-stringify": "^5.0.0",
+ "remark-parse": "^6.0.3",
+ "remark-rehype": "^4.0.0",
+ "unified": "^7.1.0",
+ Node 8.15.1

### Steps to reproduce

The code:

```js
const processor = unified()
  .use(parse, { gfm: true })
  .use(remark2rehype, { allowDangerousHTML: true })
  .use(html)

fs.readFile('sample.md', 'utf8', function(err, data) {
  processor.process(data)
    .then(function(out) {
      fs.writeFile('sample.html', out, 'utf8', function(err){
        if (err) throw err;
        return;
      })
    })
    .catch(function(err) {
      console.log(err);
    });
});
```

`sample.md`

```markdown
<figure>
![foo](example.com)
</figure>
```

### Expected behaviour

```html
&#x3C;figure>![foo](example.com)&#x3C;/figure>
```

### Actual behaviour

```html
<figure><img src="example.com" alt="foo"></figure>
```

**Comment by CxRes** [comment]
My Bad! I was using luhmann/tufte-markdown processors in between (and forgot to turn them off while investigating how to allow markdown processing in blocks) and then wondering why the figure tag gets processed.

**Comment by wooorm** [comment]
No problem! I do appreciate the issues!
