### ISSUE TITLE
Support link definitions in lists

### ISSUE THREAD

**Issue by 1999** [remarkjs/remark#401]
### Subject of the issue

Parsing result is incorrect for this case:

```
* Foo

  [1]: /Foo
```

### Steps to reproduce

```
var remarkParse = require("remark-parse")
var unified = require('unified');

var parser = unified().use(remarkParse);
var ast = parser.parse(`* Foo

  [1]: /Foo`);
  
console.log(ast);
```
### Expected behaviour

Returned tree contains one list item with "Foo" text

### Actual behaviour

Returned tree contains one list item with "Foo" and "[1]: Foo" text chunks

![image](https://user-images.githubusercontent.com/73191/57203624-06025e80-6ff5-11e9-9f5f-522d08ac3e4e.png)

**Comment by wooorm** [comment]
Thanks for another issue @1999!

(tip, if you’re sharing the actual syntax tree, you could use [astexplorer and share a snippet](https://astexplorer.net/#/gist/0fe7edacc5507167b0919c6934c2c1d4/bb3a81b17ffc87ee24968946fe5d854b93645e1c))

Could you expand on your expected output, do you believe `[1]: /Foo` should be seen as a link definition? For what it’s worth, I think the actual output makes sense, but CM/GFM seem to agree with you!

**Comment by 1999** [comment]
I'm not that familiar with the Markdown AST to answer this question. Is this link supposed to be a LinkReference node? If yes, isn't it supposed to be on the top level of the tree?

**Comment by wooorm** [comment]
According to the current state, it’s a reference, and would turn into a link if a definition was provided (`[1]: /bar` but outside the list)

According to CM/GFM, it’s a definition, and other references (`[text][1]`) would turn into links if they were added somewhere.

For more info on the syntax tree, mdast, you can see [this spec](https://github.com/syntax-tree/mdast).

**Comment by wooorm** [comment]
I think this can be fixed by toggling this boolean:

https://github.com/remarkjs/remark/blob/a47c3c9af64e69988bea6ba00d7eb552a419a9af/packages/remark-parse/lib/tokenize/definition.js#L7
