### ISSUE TITLE
How to embed the slides in Blogger?

### ISSUE THREAD

**Issue by jefferyyuan** [remarkjs/remark#405]
- It would be great if we can embed the slide in blogpost or wordpress, I tried to add the following html into my blogger, but the result seems not desired.
- http://lifelongprogrammer.blogspot.com/p/test.html
```html
    <style type="text/css">
      @import url(https://fonts.googleapis.com/css?family=Yanone+Kaffeesatz);
      @import url(https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic);
      @import url(https://fonts.googleapis.com/css?family=Ubuntu+Mono:400,700,400italic);
      body { font-family: 'Droid Serif'; }
      h1, h2, h3 {
        font-family: 'Yanone Kaffeesatz';
        font-weight: normal;
      }
      .remark-code, .remark-inline-code { font-family: 'Ubuntu Mono'; }
    </style>
    <textarea id="source">
<!-- .slide: data-background="#000000" -->
## A slide with a dark background

Try to press the down arrow key.

Implicit return statement:

```ruby
def add(a,b)
*  a + b
end
```

# Notice how there is no return statement.

--

## Another slide

Try **Esc** and **F** keys.

- A bullet point
- Another convincing argument

---

## Code blocks are no problem

Here we have some Python code:

```python
from itertools import cycle

fizz = cycle(['', '', 'Fizz'])
buzz = cycle(['', '', '', '', 'Buzz'])

for i in range(1, 101):
    print((next(fizz) + next(buzz)) or i)
```

[Source](https://github.com/olemb/nonsense/blob/master/fizzbuzz/itertools_cycle.py)

    </textarea>
    <script src="https://remarkjs.com/downloads/remark-latest.min.js"/>
    </script>
    <script type="text/javascript">
      var slideshow = remark.create({
        highlightLines: true,
      });
    </script>
```

**Comment by wooorm** [comment]
You’re having a problem with a different remark: https://github.com/gnab/remark. We can’t help you, but good luck!
