### ISSUE TITLE
1:1: Incorrectly eaten value: please report this warning on http://git.io/vg5Ft

### ISSUE THREAD

**Issue by TopKeingt** [remarkjs/remark#409]
I tried out Netlify CMS today to learn new things for my next project. After set up a default website template given by netlify CMS [deployment link](https://www.netlifycms.org/docs/start-with-a-template/). I found this bug after clicking on one of the link to edit in admin page (in the blog's collection). 

I don't know if I should ask here or in the Netlify CMS's repository but the error told me to report here and I couldn't find similar issue as mine either.

Thanks in advance.

Full Error message:
```
Error
There's been an error - please report it.

Details
1:1: Incorrectly eaten value: please report this warning on http://git.io/vg5Ft
```

**Comment by TopKeingt** [comment]
sorry but I think its Netlify CMS's fault cuz other links works but one

**Comment by wooorm** [comment]
I’m guessing netlify-cms as well, you should report it there!
