### ISSUE TITLE
Merge block quotes

### ISSUE THREAD

**Issue by arobase-che** [remarkjs/remark#415]
Hi,

As specified [gfm#220](https://github.github.com/gfm/#example-220).

When option `gfm` is used, we shouldn't merge two block quotes.
It's already done, if the option `commonmark` is used.

It's an easy thing to do, I will submit a PR soon.

❤️

**Comment by wooorm** [comment]
Thanks for opening this, and that you’re writing a PR!

**Comment by wooorm** [comment]
Closed by GH-417. ✨
