### ISSUE TITLE
A tilde in code fence metastring doesn't parse correctly

### ISSUE THREAD

**Issue by johno** [remarkjs/remark#421]
### Subject of the issue

A tilde in a code fence's metastring causes unexpected parsing to occur. This is related to mdx-js/mdx#630.

### Steps to reproduce

````md
# Hello, world!

```js filename=~/.bashrc
echo Hello
```
````

- [See the AST Explorer example](https://astexplorer.net/#/gist/734e5cfd60d5ba11aa88468c65a1e1ac/fa0c30109212beb5130c4778ccd7240a1256ff27)
- [See a CodeSandbox reproduction](https://codesandbox.io/s/pedantic-swirles-7zrnh)

### Expected behaviour

It should parse the code block and return `filename=~/.bashrc` as the metastring.

### Actual behaviour

It parses as a paragraph with inline code (see AST explorer link above).

**Comment by wooorm** [comment]
I believe this check:

https://github.com/remarkjs/remark/blob/c73f4095796ca9f761ed801f0a57c2a1deecccc2/packages/remark-parse/lib/tokenize/code-fenced.js#L103-L104

So instead be `character === marker`.
