### ISSUE TITLE
typings: visitor typings for remark-stringify

### ISSUE THREAD

**Issue by ChristianMurphy** [remarkjs/remark#426]
### Subject of the feature

Give `visitor`s a type safe way to depend on super types of unist `node`

### Problem

In this example

```ts
function gap(this: unified.Processor) {
  const Compiler = this.Compiler as typeof remarkStringify.Compiler
  const visitors = Compiler.prototype.visitors
  const original = visitors.heading

  visitors.heading = heading

  function heading(this: unified.Processor, node: Node, parent?: Parent) {
    // FIXME: remove need for explicit 'as' casting
    const headingNode = node as (Node & {depth: number})
    return (
      (headingNode.depth === 2 ? '\n' : '') +
      original.apply(this, [node, parent])
    )
  }
}

const plugin: unified.Attacher = gap
```

to get a `HeadingNode` from the visitor it needs to be cast `as (Node & {depth: number})`.
Which reduces the type safety since any property can be added in the `{}` block and typescript will accept it.

### Expected behaviour

`header` should automatically of type `HeaderNode`

```ts
function gap(this: unified.Processor) {
  const Compiler = this.Compiler as typeof remarkStringify.Compiler
  const visitors = Compiler.prototype.visitors
  const original = visitors.heading

  visitors.heading = heading

  function heading(this: unified.Processor, node: HeaderNode, parent?: Parent) {
    return (
      (headingNode.depth === 2 ? '\n' : '') +
      original.apply(this, [node, parent])
    )
  }
}

const plugin: unified.Attacher = gap
```

This should be safe, because the visitors are staticly defined ahead of time.
https://github.com/remarkjs/remark/blob/acada43abe624f306545800da0de633063e3cccc/packages/remark-stringify/lib/compiler.js#L37-L63

**Comment by ChristianMurphy** [comment]
This is a continuation of https://github.com/remarkjs/remark/pull/383#discussion_r302762011

Some previously discussed solutions

---

One option would be a generic.
Something like

```ts
  interface Transformer<I extends Node = Node, O extends Node = Node> {
    (
      node: I,
      file: VFileCompatible,
      next?: (error: Error | null, tree: O, file: VFile) => {}
    ): Error | O | Promise<O>
  }
```

Which would guarantee that the input and the output are a super type of a unist `Node`.
But could not guarantee that type `I` matches what the previous plugin output, meaning it would be possible for JavaScript errors to slip through the typings.

---

Another would be to add a generic to Processor, and set that generic to a union of all types for the give language.
For example
```ts
type AllUnifiedTypes = Node | Parent
const unifiedProcessor = unified<Settings, AllUnifiedTypes>

type AllRemarkTypes = List | ListItem | Table | ...
const remarkProcessor = unified<Settings, AllRemarkTypes>
```

But then there would be the question of how do plugins participate in the supported node typings?
And how are transitions between languages, like mdast to hast, handled?

**Comment by wooorm** [comment]
@ChristianMurphy Is this actionable, and useful enough?

**Comment by ChristianMurphy** [comment]
Actionable, yes.
Useful, a bit.
This got a lot easier to work around, now that unist-util-is has typings.
It would still be nice to have here, save an extra step.

**Comment by wooorm** [comment]
We don’t have visitors anymore, so I’ll close this. Type changes can be done to [`mdast-util-to-markdown`](https://github.com/syntax-tree/mdast-util-to-markdown).
