### ISSUE TITLE
Unecessary escaped exclamation mark

### ISSUE THREAD

**Issue by arobase-che** [remarkjs/remark#427]
### My environment

*   Arch Linux
*   `remark@11.0.0`, since `remark-stringify@6.0.4`
*   node@v11.15.0 / npm@6.10.1

### Steps to reproduce

~~~js
const remark = require('remark');

const processed = remark().processSync('![not link\\](ahah)').toString();
console.log(processed);
console.log(remark().processSync(processed).toString())
~~~

### Expected behaviour

Stringify should be idempotent. `remark().processSync(processed).toString()` should be identical to `processed`. So the output of the previous script should be : 

~~~plain
!\[not link](ahah)

!\[not link](ahah)
~~~
 
### Actual behaviour

The actual output of the markdown stringified is: 
~~~plain
\!\[not link](ahah)

!\[not link](ahah)
~~~

The first time the markdown is processed, the exclamation point is escaped and it should not be.

_____________

I don't understand the purpose of : 
```js
        (character === exclamationMark &&
          value.charAt(position + 1) === leftSquareBracket) ||
```
In [remark-stringify](https://github.com/remarkjs/remark/commit/d4a8121b0d2f7c07fee49b1201cbe593d9e9cd47#diff-e4024287fef80033295c2d2417908d28R93)

Since the bracket will always be escaped, they is no need to escape the exclamation mark as well.
But it seems to be expected as there is a test about that : 
```js
t.equal(toString('![a'), '\\!\\[a', '`!` before `[`')
```

The easy fix is to delete the lines I pointed and modify the test.    
I can submit a PR obviously. ^^

**Comment by wooorm** [comment]
I think you’re right!
It may be that the test is wrong, and that the `!` does not need to be escaped. It could be though that `[` is not always escaped.

> I can submit a PR obviously. ^^

✨
