### ISSUE TITLE
Live captions

### ISSUE THREAD

**Issue by jmankoff** [remarkjs/remark#431]
### Subject of the feature

It is becoming standard for accessibility reasons to show live captions when giving a presentation. It would be great if this could be added to remark as well. Looks like there are APIs for this (e.g. see https://github.com/google/io-captions-gadget) 

### Expected behaviour

When in presentation mode, captions for anything spoken by the presenter should show up in a footer at the bottom of the slideshow.

**Comment by ChristianMurphy** [comment]
@jmankoff I think you might have intended this ticket for https://github.com/gnab/remark ?

**Comment by wooorm** [comment]
I love accessibility but this is the wrong remark!

**Comment by jmankoff** [comment]
Whoops sorry :)

Jennifer Mankoff | jmankoff@acm.org | make4all.org
