### ISSUE TITLE
remark-parse TS: Property 'settings' is missing in type 'Parse'

### ISSUE THREAD

**Issue by alex996** [remarkjs/remark#433]
### Problem

Calling `unified().use()` with `remark-parse` raises the following error in TypeScript

> Argument of type 'Parse' is not assignable to parameter of type 'ProcessorSettings<Settings>'.
  Property 'settings' is missing in type 'Parse' but required in type 'ProcessorSettings<Settings>'.

### Packages

```json
"remark-parse": "^7.0.0",
"typescript": "^3.5.3",
"unified": "^8.3.2"
```

### Reproduction

A minimal boilerplate from [`unified` readme](https://www.npmjs.com/package/unified#use)

```ts
import unified from 'unified'
import markdown from 'remark-parse'
import remark2rehype from 'remark-rehype'
import html from 'rehype-stringify'

unified()
  .use(markdown) // <--- This causes an error
  .use(remark2rehype)
  .use(html)
```

### Expected behavior

It should raise no warnings / errors.

### Actual behavior

It raises a warning / error.

**Comment by sondr3** [comment]
I'm getting this error still, with the following TS file:

```js
import unified from "unified";
import markdown from "remark-parse";
import remark2rehype from "remark-rehype";
import html from "rehype-stringify";

const testOutput = `
# Hello World

## Table of Content

## Install

A **example**.

## Use

More \`text\`.

## License

MIT`;

const processor = unified()
  .use(markdown)
  .use(remark2rehype)
  .use(html);

processor.processSync(testOutput, (err, out) => {
  if (err) throw err;
  console.log(out);
});

export default processor;
```
