### ISSUE TITLE
Reference "markdown style guide"

### ISSUE THREAD

**Issue by fulldecent** [remarkjs/remark#436]
Readme.md identifies "markdown style guide".

Could reference to this style guide (a link) please be made there?

**Comment by wooorm** [comment]
Where is that reference?

**Comment by fulldecent** [comment]
At 

https://github.com/remarkjs/remark/blob/master/readme.md

"check Markdown code style" but if you click that it shows the rule.

"remark-preset-lint-markdown-style-guide — rules that enforce the markdown style guide"

**Comment by ChristianMurphy** [comment]
Thanks for reaching out @fulldecent.
For the quotes in question:

> check Markdown code style

is accurate, `remark-lint` checks several different style standards, and supports custom standards.

> remark-preset-lint-markdown-style-guide — rules that enforce the markdown style guide

This isn't in the remark repo, this is over at https://github.com/remarkjs/remark-lint
When the link is followed, the headline for the plugin is 

> remark preset to configure remark-lint with settings that the [Markdown Style Guide](https://cirosantilli.com/markdown-style-guide) recommends.


Note that Markdown Style Guide is linked

**Comment by fulldecent** [comment]
Got it. Thanks for pointing this out.
