### ISSUE TITLE
Span around text in checkbox list for custom checkbox

### ISSUE THREAD

**Issue by muuvmuuv** [remarkjs/remark#438]
### Subject of the feature

I would like to customize the checkbox. On other website I had used a combination of the checkbox and a span which had before and after (checked and unchecked). Is it possible to modify or customize the output?

The span would be here: https://github.com/remarkjs/remark/blob/acada43abe624f306545800da0de633063e3cccc/packages/remark-stringify/lib/visitors/list-item.js#L61

### Problem

At the moment it is just the checkbox and the text which is difficult to style and difficult to move the checkbox properly without moving the text too.

### Expected behaviour

What should happen?  Please describe the desired behaviour.

### Alternatives

What are the alternative solutions?  Please describe what else you have considered?

**Comment by ChristianMurphy** [comment]
@muuvmuuv It's not clear what you're asking for.
Can you provide an example of what the input markdown would be and what the output markdown or html would be?

**Comment by muuvmuuv** [comment]
Sorry, thought it would be clear. I'm using remark in my [GatsbyJS](https://www.gatsbyjs.org/) website with the [`gatsby-transformer-remark`](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-transformer-remark) plugin.

Input would be:

```md
- [ ] Text
- [x] Text
```

Output:

```html
<ul>
  <li class="task-list-item"><input type="checkbox" checked=""> Text</li>
  <li class="task-list-item"><input type="checkbox" checked="" disabled=""> Text</li>
</ul>
```

Expected output:

```html
<ul>
  <li class="task-list-item"><input type="checkbox" checked=""> <span>Text</span></li>
  <li class="task-list-item"><input type="checkbox" checked="" disabled=""> <span>Text</span></li>
</ul>
```

**Comment by ChristianMurphy** [comment]
Gotcha, thanks!

This would be best suited for a remark plugin. (docs on creating plugins here https://unifiedjs.com/create-a-plugin.html)
The plugin could look something like:

```js
const visitor = require('unist-util-visit');

const isCheckBox = (node) => node.type = 'listItem' && typeof node.checked === 'boolean';

const checkboxSpanner = (ast) => {
  // visit each checkbox node
  visitor(ast, isCheckBox, (checkbox) => {
    // add spans around the paragraph text
    const paragraph = checkbox.children[0];
    paragraph.unshift({ type: 'html', value: '<span>' });
    paragraph.push({ type: 'html', value: '</span>' });
  }
  return ast;
}

module.exports = () => checkboxSpanner;
```

**Comment by karlhorky** [comment]
@muuvmuuv did you ever end up creating such a plugin? Is it open source?
