### ISSUE TITLE
how to disable auto link

### ISSUE THREAD

**Issue by viewerw** [remarkjs/remark#442]

**Comment by viewerw** [comment]
I just want render a link text not a clickable <a>

**Comment by wooorm** [comment]
You ignored our guide on [how to ask for questions](https://github.com/remarkjs/.github/blob/master/support.md) 😕

**Comment by fdcds** [comment]
@viewerw Maybe you are interested in this question concerning micromark, the latest parser remark uses, and the remark gfm plugin: https://github.com/micromark/micromark/discussions/57
