### ISSUE TITLE
 Incorrectly eaten value: please report this warning

### ISSUE THREAD

**Issue by dizid** [remarkjs/remark#443]
### Error in the Netlify CMS content editor

When navigating to a specific post, i got this:
Error There's been an error - please report it.
Details 1:1: Incorrectly eaten value: please report this warning on http://git.io/vg5Ft

All other post work just fine, it just happens with the first post: "Basic Rules For Walking In The Mountains".

### Your environment

*   All online, no local dev.
*  I use Stackbit with the Fjord-theme + Gatsby + Netlify CMS + GitHub/Netlify

### Steps to reproduce
Deploy a site, edit with Netlify CMS

### Expected behaviour
I should see a blog post, ready to be edited.

### Actual behaviour
An error msg and a request to report it

**Comment by fazouane-marouane** [comment]
Hello @dizid 
Could you please provide a link to the deployed site or maybe a sample markdown content that reproduces this ? Thanks a lot

**Comment by dizid** [comment]
Deployed [site](https://pleasant-velociraptor-f655b.netlify.com/)
github [markdown file](https://github.com/dizid/pleasant-velociraptor/blob/master/src/pages/posts/basic-rules-for-walking-in-the-mountains.md)

**Comment by wooorm** [comment]
Hey Marc! Thanks for raising this issue, and providing the repo, deployed version, and source. That helped!

This is 99.9% a problem with Gatsby, specifically, the `@stackbit/gatsby-plugin-menus` or `gatsby-remark-page-creator` projects. Those are likely the root of the problem.
We can’t provide customer support for the Gatsby ecosystem, so to see this resolved, could you open an issue for either of those projects? Thanks and good luck!
