### ISSUE TITLE
TypeScript return from `parse` incorrect

### ISSUE THREAD

**Issue by DataTables** [remarkjs/remark#444]
### Subject of the issue

I might be wrong, but I think the TypeScript definition for the [parse() method's return](https://github.com/remarkjs/remark/blob/0114ff967b913ad35fddfd45d44e2d1ed4d5e869/packages/remark-parse/types/index.d.ts#L7) should be `Parent` rather than `Node`.

This is based on the fact that in Unist `Parent` extends `Node` adding the `children` array. The `parse()` method includes that array.

### Your environment

*   **OS**: Fedora 29
*   **Packages**: Remark 11.0.1
*   **Env**: Node 12.11.1, TypeScript 3.4.3

**Comment by wooorm** [comment]
@ChristianMurphy @Rokt33r What do you think? Is more specific better? In that case, why not expose a RootNode? Or is more generic better?

**Comment by ChristianMurphy** [comment]
I'm cautious, this typing is inherited from Unified.
https://github.com/unifiedjs/unified/blob/d21d47f6a35526eb2e37da77cd5cbb94e3b922a9/types/index.d.ts#L65-L71

I'm not sure all parsers (remark, rehype, retext, redot) guarantee that `Parent` will be returned.

Can you describe the use-case where returning `Node` is causing an issue?
Thus far, it has been common to use https://github.com/syntax-tree/unist-util-visit and https://github.com/syntax-tree/unist-util-is to walk the tree and narrow the types.

**Comment by DataTables** [comment]
Absolutely. Its worth highlighting that the issue is purely a typing one - there are no run time issues.

If you do something simple like:

```
const remark = require('remark')();

let ast = remark.parse('some text');
console.log( JSON.stringify(ast));
```

you will see that there is a `children` array in the `ast` object (I've removed the `position` for brevity):

```
{
	"type": "root",
	"children": [{
		"type": "paragraph",
		"children": [{
			"type": "text",
			"value": "some text",
		}],
	}],
}
```

The problem with returning a Unified `Node` type from Parse is that it doesn't have a `children` option - that comes from `Parent`. So Typescript has a good old whine about it :).

**Comment by ChristianMurphy** [comment]
@DataTables understanding the use case where children is being directly accessed would help.

Again the most common use case that I've had/seen is manipulating a specific node type.

For example, a plugin to increment top level headings
```ts
import { Node } from 'unified';
import * as remark from 'remark';
import * as visit from 'unist-util-visit';

remark().use(() => (tree: Node) => {
  visit(tree, {type: 'heading', depth: '1'}, (heading: Heading) => {
    node.depth += 1;
  })
})
```

**Comment by DataTables** [comment]
Oh I see - sorry. I was just using Remark to parse Markdown into an tree that I can then use to process myself (into QuillJS deltas in this case). I suspect I might not be doing exactly the right thing doing it that way(?), but it works quite well.

Its not a problem to work around it, a simple type casting in TypeScript does the job, but I think thought I'd flag it up since the return from the `prase()` method is something other than what the current tying information says it is.

**Comment by ChristianMurphy** [comment]
Interesting, sounds like a fun project, is the Quill JS delta project something that's open source, or you'd be comfortable sharing?
Being able to see the TypeScript code, or a part of it, would help us better understand how the typings are being used.

**Comment by ChristianMurphy** [comment]
@DataTables give this a try, using `unist-util-is` casting can be avoided.

```ts
import * as remarkModule from "remark";
import { Node } from "unist";
import * as is from "unist-util-is";
import { Text, Strong, Delete, Emphasis, Paragraph, Root } from "mdast";

import { IOperation } from "./formatters";

const remark = remarkModule();

export default class MarkdownToDelta {
  /* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
   * Static methods
   */

  /**
   * Convert HTML to a delta format
   * @param  html The HTML string to convert
   * @returns Array of delta operations
   */
  public static process(html: string): IOperation[] {
    let convertor = new MarkdownToDelta(html);
    return convertor.result();
  }

  /* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
   * Properties
   */
  private _result: IOperation[] = [];

  /* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
   * Constructor
   */
  constructor(val: string) {
    let root = remark.parse(val);

    if (is<Root>(root, "root")) {
      this._result = this._nodesToOps(root.children);
    }
  }

  /* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
   * Public methods
   */

  /**
   * Get the result from the processing of the HTML to Delta converter
   *
   * @returns Array of operations
   */
  public result(): IOperation[] {
    return this._result;
  }

  /* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
   * Private methods
   */
  private _nodeToOp(node: Node): IOperation {
    if (is<Text>(node, "text")) {
      return {
        text: node.value,
        type: "text"
      };
    }

    if (is<Strong>(node, "strong")) {
      return {
        children: node.children,
        type: "bold"
      };
    }

    if (is<Delete>(node, "delete")) {
      return {
        children: node.children,
        type: "strike"
      };
    }

    if (is<Emphasis>(node, "emphasis")) {
      return {
        children: node.children,
        type: "italic"
      };
    }

    if (is<Paragraph>(node, "paragraph")) {
      return {
        children: node.children,
        type: "para"
      };
    }

    throw new Error(`Unknown tag name (${node.type}). Cannot parse to delta`);
  }

  private _nodesToOps(nodes: Node[]): IOperation[] {
    return nodes.map(node => this._nodeToOp(node));
  }
}
```

**Comment by DataTables** [comment]
Thank you for putting so much error into this!

If this is the correct way to go about the `.parse` method:

```js
    let root = remark.parse(val);

    if (is<Root>(root, "root")) {
      this._result = this._nodesToOps(root.children);
    }
```

then shouldn't `.parse()` return a `Root` type rather than `Node` as it currently does?

**Comment by ChristianMurphy** [comment]
Potentially.
It would take some enhancements to the Unified typings, which remark extends.
https://github.com/remarkjs/remark/blob/0114ff967b913ad35fddfd45d44e2d1ed4d5e869/packages/remark/types/index.d.ts#L12-L14

---

The typing for `parse` are defined here:
```ts
    /**
     * Parse text to a syntax tree.
     *
     * @param file VFile or anything which can be given to vfile()
     * @returns Syntax tree representation of input.
     */
    parse(file: VFileCompatible): Node
```

https://github.com/unifiedjs/unified/blob/d21d47f6a35526eb2e37da77cd5cbb94e3b922a9/types/index.d.ts#L65-L71

---

To also allow `rehype`, `retext`, and `redot` define their own node types, this could be made generic.

```ts
  /**
   * Processor allows plugins, parsers, and compilers to be chained together to transform content.
   *
   * @typeParam P Processor settings. Useful when packaging unified with a preset parser and compiler.
   */
  interface Processor<P = Settings> {
```

https://github.com/unifiedjs/unified/blob/d21d47f6a35526eb2e37da77cd5cbb94e3b922a9/types/index.d.ts#L8-L13

could be enhanced with a node type generic `N`, which extends type `Node` and defaults to `Node` to make it a non-breaking change.

```ts
interface Processor<P = Settings, N extends Node = Node>
```

then weave the generic through the rest of `Processor`.

**Comment by wooorm** [comment]
Oh also: plugins could make it return something else. The only 'vontract' is that it is a node, not that it is a parent, or a root

**Comment by ChristianMurphy** [comment]
@wooorm that is specific to parser plugins, correct?
Since, [transform plugins are not run on `processor.parse`.](https://github.com/unifiedjs/unified#description)

**Comment by wooorm** [comment]
Correct, only parser plugins could do that

**Comment by wooorm** [comment]
It seems that the discussion hasn’t really resulted in something better, therefore I think the status quo is fine.
