### ISSUE TITLE
include support

### ISSUE THREAD

**Issue by etylsarin** [remarkjs/remark#446]
### add possibility to include a linked markdown file

I'm looking for a way, how to include some reusable markdown flavoured text, which I would like to keep in a separate file.
I quite like the syntax DocFX supports: https://dotnet.github.io/docfx/spec/docfx_flavored_markdown.html#file-inclusion

### it's not a plugin but core feature

I'm quite new here, so I might be wrong, but from what I understood this is more a change of remark-parse than writing a new plugin. Also I'm not sure about some security consequences here.

### probability of adding this feature

I do believe that this new feature would be highly appreciated by many. Is there any chance to list it on your roadmap?

Thank you,
Filip

**Comment by wooorm** [comment]
Hi Filip!

You can search for things like this with GitHub search, it gave me [remark-include](https://github.com/Qard/remark-include). Maybe that’s what you want?

Almost everything in remark is a plugin. This as well. remark plugins can also [integrate with remark-parse](https://github.com/remarkjs/remark/tree/master/packages/remark-parse#extending-the-parser).

But, maybe a better solutions, is that you may be interested in [MDX](https://mdxjs.com/getting-started). It’s a nice way to do things like this. It can import other MDX files.

**Comment by etylsarin** [comment]
hi @wooorm thanks a lot! I haven't seen the remark-include in the plugins list, that's why I created the ticket :)
