### ISSUE TITLE
Online playground?

### ISSUE THREAD

**Issue by rauschma** [remarkjs/remark#447]
I find online playgrounds useful. For example, Pandoc’s playground: https://pandoc.org/try/

For Remark, this could work as follows:

* Enter Markdown
* See syntax tree or HTML

Optional:

* Configure plugins, intermediate processing steps, etc.
* Document an npx invocation that does something similar

**Comment by ChristianMurphy** [comment]
For seeing the AST checkout https://astexplorer.net
For a playground, as part of https://github.com/unifiedjs/unifiedjs.github.io/issues/12, I've been looking at integrating https://runkit.com/home#notebooks to allow trying code samples live in browser.

PRs and other ideas are welcome!

**Comment by tomByrer** [comment]
MDX has one partly:

https://mdxjs.com/playground

**Comment by arobase-che** [comment]
@zestedesavoir too. Based on our needs, MD to ATX, HTML and LaTeX.

https://zestedesavoir.github.io/zmarkdown/

Based on a webpack version of our server.

**Comment by fazouane-marouane** [comment]
Hi everyone,

I started prototyping a playground. It's very minimal for now, no visual styling, no plugins and no tweaking with options and it only has one output (html).

code can be found here: https://codesandbox.io/s/remark-playground-wmfor
preview of the playground: https://wmfor.csb.app/

I'll add more things to it if I find more time this week.

**Comment by Aparus** [comment]
why don't use codesandbox.io --> add dependency --> remark --> see all you need in console ))

**Comment by ChristianMurphy** [comment]
The bug issue template now include several code sandbox playgrounds https://github.com/remarkjs/.github/blame/main/.github/ISSUE_TEMPLATE/1-bug.md#L37-L39

remark only (for markdown to markdown): https://codesandbox.io/s/remark-debug-ikwvx
remark and rehype (for markdown to html): https://codesandbox.io/s/remark-rehype-debug-4cz8v
react-markdown: https://codesandbox.io/s/react-markdown-debug-9n4eg

**Comment by wooorm** [comment]
Made a playground! https://remark.js.org.

I had to think a bit about what would be useful. As remark doesn’t really do anything by default. Everything can, and will, be done by plugins. Going to HTML isn’t the only useful case.

Anyway, being able to see an AST, or the generated markdown/html, or toggling some plugins, can be nice. So, there goes!
