### ISSUE TITLE
Paragraph followed by list item is parsed as single paragraph

### ISSUE THREAD

**Issue by jschaf** [remarkjs/remark#449]
### Subject of the issue

A paragraph followed by a list is parsed as a single paragraph instead of a paragraph and then a list.

```
test one two
1. hello
```

Both commonmark (https://spec.commonmark.org/dingus/) and Github parse this as a paragraph and then a list.

In Github:

test one two
1. hello

### Steps to reproduce

https://astexplorer.net/#/gist/3279e1f258a69e98db0697114408f039/db6672c98fcbbc31c0de2ce5114471a693fed0f1

### Expected behaviour

There should be a parse tree of (roughly):
```
root
  paragraph
  list
```

### Actual behaviour

The parse tree is:

```
root
  paragraph
```

**Comment by wooorm** [comment]
Hi Joe!

You can set the `commonmark: true` option in ASTExplorer or [give it to remark](https://github.com/remarkjs/remark/tree/master/packages/remark#use)!

Good luck!
