### ISSUE TITLE
IE11 throws error to due usage of is-plain-obj

### ISSUE THREAD

**Issue by lifeiscontent** [remarkjs/remark#454]
### Subject of the issue

https://github.com/sindresorhus/is-plain-obj/issues/7

### Your environment

*   **OS**: N/A
*   **Packages**: remark, remark-html
*   **Env**: browser

### Steps to reproduce

Tell us how to reproduce this issue.  Please provide a working and simplified example.

https://codesandbox.io/s/heuristic-pine-vptuh

🎉 BONUS POINTS for creating a [minimal reproduction](https://stackoverflow.com/help/mcve) and uploading it to GitHub.  This will get you the fastest support.  🎉

### Expected behaviour

having remark not throw in IE11

What should happen?

the page should render.

### Actual behaviour

What happens instead?

the page doesn't render.

**Comment by fazouane-marouane** [comment]
Hello @lifeiscontent 
I took the liberty to deploy the example to now.sh and it seems to be working on IE11
<img width="1439" alt="Screenshot 2019-12-03 at 09 53 38" src="https://user-images.githubusercontent.com/2125859/70035243-cb749a80-15b2-11ea-9ad1-088fc8f723e3.png">

I changed the build script to `parcel build index.html --out-dir public` and clicked on the deploy button on the left in codesandbox.

So my impression is that you can only run production builds on IE11, not the dev builds. All famous bundlers can already consume `is-plain-obj` and the other dependencies without any issue. Can you please check that you were testing production builds on IE11?

**Comment by lifeiscontent** [comment]
@fazouane-marouane yes, this is our app, running next.js in production and its still happening. https://app.trustedhealth.com/jobs/roles/registered/locations/ca

**Comment by lifeiscontent** [comment]
@fazouane-marouane I'm using next.js I took the approach you did and deployed to now.sh to test IE11. The error is still present as you can see here: https://csb-x2zct-5jq6b6p1y.now.sh/ and the code here: https://codesandbox.io/s/nextjs-x2zct

if you don't see the syntax error, you will if you refresh.

**Comment by SirensOfTitan** [comment]
`is-plain-obj` is primarily for a node-js environment, not the browser, and as a result its package isn't transpiled.  If you're using `next`, you'll want to use `next-transpile-modules` (I think this is the name of the package) and explicitly tell it to transpile the `is-plain-obj` package.

**Comment by lifeiscontent** [comment]
@SirensOfTitan as mentioned here https://github.com/sindresorhus/is-plain-obj/issues/7#issuecomment-560975137 this should happen automatically by the framework without the need for 3rd party packages.

**Comment by ChristianMurphy** [comment]
@lifeiscontent remark is designed to run on Node.
It can be run in browser using a transpiler, as part of the transpilation, include the polyfills for the browsers you want to support.
