### ISSUE TITLE
Remark fails when used in lint-staged pre-commit hook

### ISSUE THREAD

**Issue by jpohancenik** [remarkjs/remark#455]
### Remark fails when used in pre-commit hook

Remark fails when used in combination with lint-staged package for multiple .md files with error:
```
Error: Cannot write multiple files to single output: [path-to-local-repo]\1.md
  at done ([path-to-node-modules]\unified-engine\lib\file-pipeline\copy.js:63:9)
  at onstatfile ([path-to-node-modules]\unified-engine\lib\file-pipeline\copy.js:46:7)
  at FSReqCallback.oncomplete (fs.js:159:5)
```

When running outside the coomit hook (`npm run md:fix`), remark works as expected.

### Your environment

*   **OS**: WIN 10
*   **Packages**: see package.json in included minimal reproduction
*   **Env**: node 12.13.0

### Steps to reproduce

1. clone the repo https://github.com/jpohancenik/remark-lint-issue
2. run `npm i` to install packages
3. make some invalid changes in 1.md and 2.m (e.g. multiple empty lines between text)
4. stash the files `git add .`
5. commit the files `git commit -m test`
6. see the error in console

[minimal reproduction: https://github.com/jpohancenik/remark-lint-issue](https://github.com/jpohancenik/remark-lint-issue)

### Expected behaviour

Remark should write fixes to output files without throwing error.

### Actual behaviour

Remark fails with error message `Cannot write multiple files to single output`

**Comment by wooorm** [comment]
You can fix this if you add `--` to the end of your script, like so: `remark . -o --`.
This feature, which many other commands also support, says to not parse further values (which lint-staged passes) as arguments, but instead as files!

**Comment by jpohancenik** [comment]
Thank you, works like a charm!
