### ISSUE TITLE
GitHub Action?

### ISSUE THREAD

**Issue by Jolg42** [remarkjs/remark#461]
I was looking for a GitHub Action to validate links in markdown files on every push / Pull Request and thought that remark would be really great combined with the [remark-validate-links](https://github.com/remarkjs/remark-validate-links) plugin.

Do you know if anybody tried to used remark as a GitHub Action?

I guess one more common usage is to do it locally on a pre-commit hook maybe?

**Comment by wooorm** [comment]
People typically use remark-cli in an npm script, often with a preset such as [this one](https://github.com/wooorm/remark-preset-wooorm) (which can include remark-validate-links, remark-lint, and the like).
One benefit of remark and those presets is that you can set up a pipeline that transforms and formats markdown too (e.g., remark-toc)

It’s possible to do these things in actions too!

**Comment by ChristianMurphy** [comment]
unified, the parent project of remark, uses remark cli to check markdown contents in a github action.
https://github.com/unifiedjs/unified/blob/master/.github/workflows/ci.yml as part of `npm test`.

**Comment by wooorm** [comment]
@ChristianMurphy I think we can close this?

**Comment by ChristianMurphy** [comment]
I think so
