### ISSUE TITLE
Underscores within links interfering with emphasis in pedantic mode.

### ISSUE THREAD

**Issue by fabiosantoscode** [remarkjs/remark#470]
### remark seems to be conflating underscores in links with emphasis underscores, in pedantic mode.

When using pedantic mode, an underscore-surrounded link isn't properly parsed, when this link has underscores. Read below for repro, the code is clearer than my wording :)

### Your environment

*   **OS**: Elementary OS Luna (kernel 4.15.0-74-generic)
*   **Packages**: remark=10.0.1, remark-parse=6.0.3
*   **Env**: node=12.10.0, yarn=1.17.3

### Steps to reproduce

Run this in a node repl or script:

```
const Remark = require('remark')
new Remark().data('settings', {pedantic: true}).parse('_baz [link](https://example.com/with_underscore)_').children[0]
```

We can verify that the link is being parsed in a weird way, and the link is broken too, and starts pointing to `https://example.com/with`, which ignores its `_underscore` ending.

### Expected behaviour

This should return a simple tree, comprised of:

```
paragraph
  - emphasis
    - text "baz"
    - link [to the URL with an underscore]
      - text "link"
```

### Actual behaviour

I get a very complex tree:

```
paragraph
  - emphasis
    - text "baz"
    - linkReference
    - text "("
    - link to https://example.com/with
      - text "https://example.com/with"
  - text "underscore)_"
```

Cheers!

**Comment by wooorm** [comment]
Hi! 👋 I would strongly suggest, if possible, to stop using pedantic mode: it emulates the buggy original markdown from 2004

**Comment by fabiosantoscode** [comment]
@wooorm thank you for your suggestion. I will go through that avenue and check if the HTML is similar. Feel free to close!

**Comment by wooorm** [comment]
If that's possible, that'd be great! It's been so long that I think it would be better for remark and markdown to start thinking of removing pedantic mode.
May I ask what the reason was for using this mode?

**Comment by fabiosantoscode** [comment]
Gatsby [defaults it to true](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-transformer-remark/src/extend-node-type.js#L110). I don't know the reason behind it.
