### ISSUE TITLE
Bad formatters in inline math mode

### ISSUE THREAD

**Issue by startnoob** [remarkjs/remark#471]
Here is what I need:
`$A \leftarrow B$`
But It returns this:
`$A \\leftarrow B$`

I'm not sure if it is a bug or just my mistakes, but I just can't find any option from remark itself can fix it.

**Comment by ChristianMurphy** [comment]
@startnoob could you provide more context?
For example:
1. what version of remark you are using?
2. what remark plugins are being used?
3. how are remark and the plugins configured?
4. what is the source markdown you are transforming?

**Comment by startnoob** [comment]
Version:
`remark: 9.0.0, remark-cli: 5.0.0`

No plugins are being used.

I try to use vim-autoformat to call remark(The command:`remark --silent --no-color`)

The example:
`$$
\frac{a^{2}}{3}+\pi
$$ `

It returns:
`$$
\\frac{a^{2}}{3}+\\pi
$$`

It seems that every backslash will be changed to two backslashes.

**Comment by ChristianMurphy** [comment]
@startnoob could you try remark 11?

With the latest version and commonmark I'm not able to reproduce the issue you mention.
Code I tested
```js
const remark = require('remark')

remark()
  .data('settings', {commonmark: true})
  .processSync('$$ \frac{a^{2}}{3}+\pi $$')
  .contents
```

runnable example: https://runkit.com/christianmurphy/5e548615321a770019b99771

**Comment by startnoob** [comment]
Fine, I just find out I installed from AUR but the package from it is too old...... :sweat_smile: 
Anyway, The problem is solved.
Thanks! Please forgive my mistake.
