### ISSUE TITLE
<a> HTML tag seems not to be handled correctly

### ISSUE THREAD

**Issue by pd4d10** [remarkjs/remark#472]
### Your environment

*   **OS**: macOS
*   **Packages**: remark-parse v7.0.2
*   **Env**: node and browser

### Steps to reproduce

```js
const unified = require('unified');
const md = require('remark-parse');
const parser = unified().use(md);

console.log(parser.parse(`<a href="b">c</a>`).children[0]);
```

### Expected behaviour

The whole `<a href="b">c</a>` should be parsed as an HTML node

### Actual behaviour

```js
{
  type: 'paragraph',
  children: [
    { type: 'html', value: '<a href="b">', position: [Position] },
    { type: 'text', value: 'c', position: [Position] },
    { type: 'html', value: '</a>', position: [Position] }
  ],
  position: Position {
    start: { line: 1, column: 1, offset: 0 },
    end: { line: 1, column: 18, offset: 17 },
    indent: []
  }
}
```

**Comment by wooorm** [comment]
This is expected, because inline HTML can contain Markdown again:

```markdown
<a href="#">*emphasis works*</a>
```

<a href="#">*emphasis works*</a>

**Comment by pd4d10** [comment]
@wooorm Get it, thanks for your quick response!

Another thing which made me confused is the result of `<a href="b">\nc</a>`:

```js
{
  type: 'html',
  value: '<a href="b">\nc</a>',
  position: Position {
    start: { line: 1, column: 1, offset: 0 },
    end: { line: 2, column: 6, offset: 18 },
    indent: [ 1 ]
  }
}
```

So the markdown in HTML only takes effects when there is no line break?

**Comment by wooorm** [comment]
HTML in Markdown is weird. Because the line has only a complete opening tag, it turns into an HTML block.

```markdown
<a href="b">
*emphasis doesn’t work*</a>
```

<a href="b">
*emphasis doesn’t work*</a>

**Comment by bentranmyriota** [comment]
I m having the same problem as @pd4d10,  with nested HTML tags and HTML tags in the markdown table cells. The styling of the texts are completed messed because it is rendered outside the HTML tags.

*Markdown content:**
```
Something is not right!
<span>Are you sure?</span>
<span>Yes</span>
```
**Rendered output in the browser:**
```
<p>Something is not right!
<span></span>Are you sure?
<span></span><span></span>Yes
</p>
```

According to this [article](https://www.markdownguide.org/basic-syntax/#html-best-practices), markdown should not be allowed in the HTML.

**Comment by wooorm** [comment]
@pd4d10 Please see [support.md](https://github.com/remarkjs/.github/blob/main/support.md#asking-quality-questions) on how to ask questions.
