### ISSUE TITLE
Auto link not considering last parentheses

### ISSUE THREAD

**Issue by ivanbanov** [remarkjs/remark#478]
### Subject of the issue

When using auto link with parentheses in the URL it can end up ignoring a parentheses character when it's at the end of the line

### Your environment

*   **OS**: MacOS Catalina 10.15.2
*   **Packages**: remark-parse
*   **Env**: node v11.15.0 / chrome 80.0.3987.149

### Steps to reproduce

Use remark-parse with `autolink:true` and parse the following text
```
https://google.com/?q=(123)
```

### Expected behaviour

the whole text should be a link

### Actual behaviour

the parser doesnt consider the number of open parentheses in the middle of the link

![image](https://user-images.githubusercontent.com/2953018/77780305-116ad800-7054-11ea-896f-3246107a8b7e.png)

**Comment by ivanbanov** [comment]
Just notice it seems to be a problem with brackets as well `]`
e.g. https://google.com/?q=123]

**Comment by wooorm** [comment]
Hi @ivanbanov, could you fill out the form? https://raw.githubusercontent.com/remarkjs/.github/master/.github/ISSUE_TEMPLATE/1-bug.md

**Comment by ivanbanov** [comment]
@wooorm updated
