### ISSUE TITLE
Add support to Footnotes

### ISSUE THREAD

**Issue by TJProgrammer** [remarkjs/remark#486]
### Subject of the feature

Add support to [Footnotes](https://python-markdown.github.io/extensions/footnotes/)

### Problem

I can't add a footnote.

`blabla[^1]` -> is parsed correctly
`[^1]: footnote blabla` -> is parsed -> `[^1]&#x3A; footnote blabla`

### Expected behaviour

`[^1]: footnote blabla` -> no parsing

### Alternatives

No.

### Note

I'm using `remark` through `atom-beautify`.

**Comment by wooorm** [comment]
https://github.com/remarkjs/remark-footnotes

remark is based on plugins. The above plugin adds footnotes. Read more about plugins, remark, and the unified collective in our readme: https://github.com/remarkjs/remark#intro
