### ISSUE TITLE
stringify: incorrect entity encoding

### ISSUE THREAD

**Issue by ysiw** [remarkjs/remark#498]
remark-stringify outputs incorrect escaped entites in table if options.entities is "escape"

```bash
$ cat a.md
| aaa        | aaa |
| ---------- | --- |
| http://abc |     |
$ remark a.md
| aaa             | aaa |
| --------------- | --- |
| http&#x3A;//abc |     |
a.md: no issues found
$ remark --setting '"entities":"escape"' a.md
| aaa                 | aaa |
| ------------------- | --- |
| http&amp;#x3A;//abc |     |
a.md: no issues found
$
```

**Comment by wooorm** [comment]
What is the reason for using `entities: 'escape'`?

**Comment by wooorm** [comment]
This is indeed a bug. Double escaping is going on if `entities: 'escape'` is defined.
I think it makes the most sense to remove the option altogether.

**Comment by ysiw** [comment]
I prefer some entites are escaped, such as `&check;` (&check;), `&cross;` (&cross;). It is the only way to do it.

**Comment by wooorm** [comment]
> I prefer some entites are escaped, such as `&check;` (✓), `&cross;` (✗)

That behavior is closer to `entities: true` than `entities: 'escape'`.
`escape` used to work but is now broken, and should do the inverse: https://github.com/wooorm/stringify-entities/tree/355100188e1f3661359e7404115cd7e04c75ed41#optionsescapeonly.

I think removing `'escape'` makes the most sense.

**Comment by ysiw** [comment]
I suggest modifing behavior of `entites: 'escape'` to escape all character entites listed in https://dev.w3.org/html5/html-author/charref

There is a package `character-entities` which has the complete list.

Current implementation gives me no option to keep my document unchanged.

![image](https://user-images.githubusercontent.com/18527938/84505185-e0638080-acef-11ea-83d7-6057c566612e.png)

**Comment by wooorm** [comment]
> I suggest modifing behavior of entites: 'escape' to escape ONLY all character entites listed in https://dev.w3.org/html5/html-author/charref

That does include many ASCII / other characters, such as a space, a tab, a line feed, +, -, :, and so many more!

---

As you are already invested in Unicode, with Chinese characters, I don’t really get why check and cross can’t be in unicode either?

I instead strongly think we should drop options on encoding character references. /CC @ChristianMurphy, what do you think?

**Comment by ChristianMurphy** [comment]
> drop options on encoding character references

As in remove `options.entities` from the project entirely?

**Comment by wooorm** [comment]
Yes

**Comment by wooorm** [comment]
background: it was added because I recently made stringify-entities, which had those options. Now, years later, we definitely live in a unicode world, there is basically no reason anymore to use character references.

**Comment by ChristianMurphy** [comment]
Removing the option works for me.
The only character entity that I've used in projects recently is `&nbsp;`, which I believe has a Unicode equivalent.
