### ISSUE TITLE
Property 'blockTokenizers' does not exist of type 'RemarkParser'

### ISSUE THREAD

**Issue by tmm** [remarkjs/remark#499]
Curious why `blockTokenizers` aren't added to the type, but `blockMethods` are.

https://github.com/remarkjs/remark/blob/31905d14610ff34a844e738657c0d1d27cc5f354/packages/remark-parse/types/index.d.ts#L6-L14

I'm trying to override `blankLine` and get a `Property 'blockTokenizers' does not exist of type 'RemarkParser'` error:

```ts
const blockTokenizers = remarkParse.Parser.prototype.blockTokenizers // type error here
blockTokenizers.blankLine = tokenize.blankLine
```

Would it work to add the following?

```ts
declare class RemarkParser implements Parser { 
  ...
  blockTokenizers: {
    [key: string]: remarkParse.Tokenizer
  }
  ...
}
```

**Comment by ChristianMurphy** [comment]
@tmm if this is a question, https://spectrum.chat/unified/type-definitions would be the best place for this.
If this is a bug report/feature request please fill out the issue template
https://github.com/remarkjs/.github/blob/master/.github/ISSUE_TEMPLATE/1-bug.md
or https://github.com/remarkjs/.github/blob/master/.github/ISSUE_TEMPLATE/2-feature.md

**Comment by tmm** [comment]
posted on spectrum. closing for now.

will re-open with the proper template later if necessary.

thanks for triaging quickly.

**Comment by dwjohnston** [comment]
@ChristianMurphy @tmm  can you tell me what the resolution for this was?

**Comment by wooorm** [comment]
This is a question about a feature that was removed two years ago. The resolution is: don’t use 2 year old features. Ask new questions following our support guide to get help.

**Comment by dwjohnston** [comment]
@wooorm  lol fair enough. If you see the above link back you see that this relates to a plugin (remark-grid-tables) that no longer works with remark-parse@9 and so I this issue just came up as part of that investigation. 

On the chance that migrating plugins is straight forward - do you know how I would convert some some code that looks like this: 


```
export default function plugin () {

  const Parser = this.Parser

  // Inject blockTokenizer
  const blockTokenizers = Parser.prototype.blockTokenizers
  const blockMethods = Parser.prototype.blockMethods
  blockTokenizers.gridTable = gridTableTokenizer
  blockMethods.splice(blockMethods.indexOf('fencedCode') + 1, 0, 'gridTable')
```

to the remark-parse@10 way of doing things?

**Comment by wooorm** [comment]
The answer to “how to use a plugin that does not work anymore”, namely `remark-grid-tables`, is solved by looking at the issues of that plugin. As far as I am aware, they are looking for help.
No, it is not trivial. It is extremely complex.
