### ISSUE TITLE
Unclear of the best way to handle listItems with links inside

### ISSUE THREAD

**Issue by domharrington** [remarkjs/remark#500]
### Subject of the issue

Hey! Thanks for this module. I have a possible bug report (or maybe some more docs could be added) about the parsing of list item contents when they contain links.

Given the following mdast:

```
{
  type: 'root',
  children: [
    {
      type: 'list',
      children: [
        {
          type: 'listItem',
          children: [
            { type: 'text', value: 'text' },
            { type: 'text', value: 'text' },
          ],
        },
      ],
    },
  ],
}
```

When I convert this to markdown (using the following code):

```js
const unified = require('unified');
const markdown = require('remark-parse');
const stringify = require('remark-stringify');

const output = unified().use(stringify).stringify(ast);

console.log(output);
```

I get the following:

```
-   texttext
```

If I add a link into the ast like so:

```
{
  type: 'root',
  children: [
    {
      type: 'list',
      children: [
        {
          type: 'listItem',
          children: [
            { type: 'text', value: 'text' },
            { type: 'link', url: 'https://example.com', children: [{ type: 'text', value: 'link' }] },
            { type: 'text', value: 'text' },
          ],
        },
      ],
    },
  ],
}
```

This then adds line breaks around the link:

```
-   text

    [link](https://example.com)

    text
```

Which when converted to HTML turns into p tags:

```
<ul>
<li>
<p>text</p>
<p><a href="https://example.com">text</a></p>
<p>text</p>
</li>
</ul>
```

I managed to get it working by wrapping the li contents in a p tag, like so:

```js
{
  type: 'root',
  children: [
    {
      type: 'list',
      loose: false,
      children: [
        {
          type: 'listItem',
          children: [
            {
              type: 'paragraph',
              children: [
                { type: 'text', value: 'text' },
                {
                  type: 'link',
                  children: [{ type: 'text', value: 'link' }],
                  url: 'https://example.com',
                },
                { type: 'text', value: 'text' },
              ],
            },
          ],
        },
      ],
    },
  ],
}
```

Which correctly outputs to HTML as follows:

```html
<ul>
<li>text<a href="https://example.com">link</a>text</li>
</ul>
```

Did I do something wrong here? Should this have worked as intended? I managed to solve my problem by using the AST Explorer and working backwards from my intended markdown output: https://astexplorer.net/#/gist/0a92bbf654aca4fdfb3f139254cf0bad/2c60546e5027d026acfb40046aed1f192443a9b1. This is maybe related to https://github.com/syntax-tree/mdast-util-to-hast/pull/23?

### Your environment

*   **OS**: macOS
*   **Packages**:
"remark-parse": "^8.0.2",
"remark-rehype": "^7.0.0",
"rehype-stringify": "^7.0.0",
"unified": "^9.0.0"

*   **Env**: node.js v10.16.0

**Comment by domharrington** [comment]
In retrospect, maybe this is documented sufficiently in the mdast spec by saying that children of `ListItem` should be `BlockContent` https://github.com/syntax-tree/mdast#blockcontent. But a parser error would be helpful if that's the case.

**Comment by ChristianMurphy** [comment]
Hey @domharrington!
Sorry you ran into a spot of trouble with that.

I agree having a way to validate the hierarchy of content types of the AST could be valuable.
That could be a good fit for https://github.com/remarkjs/remark-lint which focuses on checking the validity of an AST, and some of this functionality may exist already in https://github.com/syntax-tree/mdast-util-assert

remark itself really focuses on the parsing and stringifying and less on the validation of content.

**Comment by wooorm** [comment]
Maybe content types can be check in https://github.com/syntax-tree/mdast-util-assert/blob/master/index.js ? It doesn’t yet, but does check other problems

**Comment by wooorm** [comment]
Made an issue for that: https://github.com/syntax-tree/mdast-util-assert/issues/5

I’d prefer to do a best-possible job here in remark-stringify (or in mdast-util-to-html or hast-util-to-html) instead of crashing or warning, so I’ll close this.
