### ISSUE TITLE
Error Markdown files: transform **abc\_def\_cde**. Need to conserve escape \_

### ISSUE THREAD

**Issue by pacocom** [remarkjs/remark#503]
I use
```
"prettier": "2.0.5"
    "gatsby": "2.23.3",
    "gatsby-image": "2.4.7",
    "gatsby-plugin-catch-links": "2.3.5",
    "gatsby-plugin-manifest": "2.4.11",
    "gatsby-plugin-react-helmet": "3.3.4",
    "gatsby-plugin-remove-serviceworker": "1.0.0",
    "gatsby-plugin-sass": "2.3.4",
    "gatsby-plugin-sharp": "2.6.11",
    "gatsby-plugin-typescript": "2.4.6",
    "gatsby-remark-autolink-headers": "2.3.5",
    "gatsby-remark-copy-linked-files": "2.3.5",
    "gatsby-remark-external-links": "0.0.4",
    "gatsby-remark-images": "3.3.10",
    "gatsby-remark-link-rewrite": "0.2.1",
    "gatsby-remark-prismjs": "3.5.4",
    "gatsby-remark-relative-images": "0.3.0",
    "gatsby-remark-responsive-iframe": "2.4.5",
    "gatsby-remark-smartypants": "2.3.4",
    "gatsby-source-filesystem": "2.3.11",
    "gatsby-transformer-json": "2.4.5",
    "gatsby-transformer-remark": "2.8.15",
    "gatsby-transformer-sharp": "2.5.5"
```

```
{
  "printWidth": 80,
  "tabWidth": 2,
  "useTabs": false,
  "semi": true,
  "singleQuote": true,
  "jsxSingleQuote": false,
  "trailingComma": "es5",
  "bracketSpacing": true,
  "jsxBracketSameLine": true,
  "arrowParens": "always",
  "endOfLine": "lf"
}
```

Error md files: transform **abc\_def\_cde**. Need to conserve _ inside of **
I don't want (cursive)
  _a_
I want
  \_a\_

Example:
1- The good code;
`There is also a metric called **spark\_read\_valid** to check how many records were successfully processed and **spark\_records\_written** to know how many records were written to datasource.`
![image](https://user-images.githubusercontent.com/7735329/84485352-53430c00-ac9c-11ea-800b-e96c1d13ab84.png)

2- After prettier this file;
`There is also a metric called **spark_read_valid** to check how many records were successfully processed and **spark_records_written** to know how many records were written to datasource.`
![image](https://user-images.githubusercontent.com/7735329/84485399-62c25500-ac9c-11ea-8249-934f7ed7684e.png)

3- If I try to add more escapes:
`There is also a metric called **spark\\\_read\\\_valid** to check how many records were successfully processed and **spark\\\_records\\\_written** to know how many records were written to datasource.`
![image](https://user-images.githubusercontent.com/7735329/84485488-81285080-ac9c-11ea-995a-33c11a349069.png)

I want first case but appliying prettier.

Thanks.

**Comment by wooorm** [comment]
This sounds like a problem with prettier? If so, please raise it there. Alternatively, it could be a problem with Gatsby. Lastly, if it is a problem here, could you narrow the example down to something that does not include prettier or Gatsby?

**Comment by pacocom** [comment]
@wooorm Yes.

With this code:
`There is also a metric called **spark_read_valid** to check how many records were successfully processed and **spark_records_written** to know how many records were written to datasource.`
I want:
```html
<p>There is also a metric called <strong>spark_read_valid</strong> to check how many records were successfully processed and <strong>spark_records_written</strong> to know how many records were written to datasource.</p>
```
![image](https://user-images.githubusercontent.com/7735329/84492682-d5d0c900-aca6-11ea-8bae-54978e1c09a0.png)

**Comment by wooorm** [comment]
Could you explain how you generate HTML from Markdown?

Again, this is probably related to Gatsby. The solution probably lies here: https://github.com/remarkjs/remark/issues/470

**Comment by pacocom** [comment]
@wooorm I will try. It looks like the solution.

**Comment by wooorm** [comment]
Could you confirm whether my understanding, that removing `pedantic: true`, solved your problem?

**Comment by pacocom** [comment]
Yes, it was the solution.

Very thanks!
