### ISSUE TITLE
None of your links work on the website

### ISSUE THREAD

**Issue by rj-coding** [remarkjs/remark#506]
### Subject of the issue

404 errors everywhere in your website....
Probably related to you switching your `master` branch to `main`.

### Steps to reproduce

Go to https://remark.js.org/ and click any link (like Plugins, Parses, Compiles). All give a 404.

### Expected behaviour

I want to see the docs.

### Actual behaviour

404 errors....

**Comment by wooorm** [comment]
Thanks, you’re right. Fixes will come tomorrow!

**Comment by r3dcrosse** [comment]
Thank you for making the switch from `master` to `main`!

**Comment by wooorm** [comment]
Thanks, fixed in https://github.com/remarkjs/remark/commit/11694cdcd27993dfb985241545399b271dda7936
