### ISSUE TITLE
Move vscode-remark to the remarkjs organization

### ISSUE THREAD

**Issue by asbjornu** [remarkjs/remark#508]
This isn't exactly a feature request, but I thought this would be the best way to bring your attention to the topic, so please bear with me.

[vscode-remark](https://github.com/mrmlnc/vscode-remark) is a plugin to [Visual Studio Code](https://code.visualstudio.com/) that uses remark-lint to automatically lint documents. The plugin has [~7.000 downloads on the Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=mrmlnc.vscode-remark) and is currently looking for a new maintainer (see mrmlnc/vscode-remark#22). I thought the best solution would be to have the repository moved from @mrmlnc to @remarkjs.

If no one else comes forth with a strong desire to maintain the plugin, I'll volunteer as an administrator of the repository after the move. To perform the move, an administrator in the @remarkjs organization needs to be added as an administrator of the [vscode-remark](https://github.com/mrmlnc/vscode-remark) repository to initiate the move.

Thoughts?

**Comment by wooorm** [comment]
Hi Asbjørn, Denis,

That’s possible indeed! The process we use for such things is documented here: https://github.com/unifiedjs/collective/blob/main/organizations.md#motion-to-grant-governance.

I’m not a VSCode user though, so would prefer some other remark member or you to be the “owner” of the project, as I lack the knowledge or interest.

@asbjornu, are you also interested in other remark / unified projects?

**Comment by asbjornu** [comment]
Thanks, @wooorm! Much appreciated. We'll follow through with our commitments according to your governance process soon, I hope.

I'm happy to become an owner of the repository after it's moved.

> are you also interested in other remark / unified projects?

What did you have in mind?

**Comment by mrmlnc** [comment]
I agree to transfer my project to your organization.

JFYI: I can't give you the rights for the extension in the store. As I understand from the ((https://github.com/microsoft/vscode/issues/21478 instruction)) — I can grant rights to all extensions, but not to one specific one. So in this case we can deprecate the existing extension and point users to the next extension.

**Comment by asbjornu** [comment]
@wooorm, do you need anything else in order to start the transfer?

**Comment by wooorm** [comment]
Heyy sorry about the wait.

@mrmlnc Are you saying that, going with step 1, would give @asbjornu or me or so, access to publish *all* your extensions? 😞

**Comment by asbjornu** [comment]
@wooorm, isn't a much better solution to create a `remark` or `remarkjs` organization/user on the Visual Studio Marketplace under which we can publish an entirely new extension and then obsolete and redirect the old extension to the new one?

**Comment by mrmlnc** [comment]
I think that the option suggested by @asbjornu suits us better. This does not require any investment (money) other than time (a little). Also VS Code has a great [instruction](https://code.visualstudio.com/api/working-with-extensions/publishing-extension).

**Comment by asbjornu** [comment]
@mrmlnc, ping?

**Comment by wooorm** [comment]
@mrmlnc can you give me more access rights? I can’t see the `settings` tab yet?

**Comment by mrmlnc** [comment]
I couldn't find any buttons to give more rights (already `collaborator`). So, I chose transfer ownership to @wooorm.

**Comment by wooorm** [comment]
I keep forgetting how to best transfer haha, this works, thanks!

**Comment by asbjornu** [comment]
@wooorm, awesome to see the repository moved. Could you please promote me to admin as well? 🙏
