### ISSUE TITLE
Errors are thrown when typing "<-" inside HTML tag content

### ISSUE THREAD

**Issue by gilisho** [remarkjs/remark#509]
### Subject of the issue

I'm using `react-markdown` module (https://github.com/rexxars/react-markdown). 
It seems like the underlying parser, which is remark, is failing to parse a piece of text within HTML tags correctly.

### Steps to reproduce

1. Go to https://rexxars.github.io/react-markdown/
2. Paste this piece of code in the left column:
```
<code>
bla bla <- bla bla
</code>
```

### Expected behaviour

Should present a simple element, like Github does:
<code>
bla bla <- bla bla
</code>

### Actual behaviour

The parser fails to parse the text.
There are errors thrown in console:
```
DOMException: Failed to execute 'createElement' on 'Document': The tag name provided ('-') is not a valid name.
 ```
```
Uncaught DOMException: Failed to execute 'createElement' on 'Document': The tag name provided ('-') is not a valid name.
```

**Comment by ChristianMurphy** [comment]
@gilisho here is the content, as it is processed by `remark` https://astexplorer.net/#/gist/9d55e3d353efc05ae1e832157e4436b8/f569e617b084d5a780b5f914a6b9f9fcf7802975
Note that remark appears to correctly identify the `html` section.

This appears to be an issue with `react-markdown`, specifically with https://github.com/rexxars/react-markdown/blob/c63dccb8185869cfc73c257d098a123ef7a7cd33/src/plugins/html-parser.js

If you are looking for a way to work around this, check out https://github.com/rexxars/react-markdown/pull/428
Which you can also use via https://github.com/ChristianMurphy/react-remark

**Comment by gilisho** [comment]
Thank you so much for the fast response!!
I'll take a look at the links and post here if I have any further questions.

**Comment by gilisho** [comment]
Hey @ChristianMurphy!
First of all, your fix looks amazing. I wish it would have been merged, along with [this PR](https://github.com/rexxars/react-markdown/pull/425). BTW what is blocking from merging? A code review of the admin?
I still want to cover all the options though: if this fix can be consumed via `astPlugins` prop of `react-markdown`, instead of using the `htmlParser` the library provides - this will be the "awesomest".
If there's no choice, then I guess I would have to migrate my whole project to a different library (the one you provided). Since your fix is waiting to be merged to `react-markdown` anyway, maybe a replacement for the current plugin would be the best.

On the other hand, I see in your PR that the whole API of `react-markdown` is changed, so I'm not sure it would be possible to consume the fix in the form of an `astPlugin`.

**Comment by wooorm** [comment]
> I see in your PR that the whole API of react-markdown is changed

The type definitions changed. The rest of the API is the same.

---

You could also look into using remark, remark-rehype, rehype-react directly!

**Comment by ChristianMurphy** [comment]
> I wish it would have been merged, along with this PR. BTW what is blocking from merging? A code review of the admin?

For an admin to review, merge, and release the update.

> On the other hand, I see in your PR that the whole API of react-markdown is changed, so I'm not sure it would be possible to consume the fix in the form of an `astPlugin`

yes, there's an example of this https://christianmurphy.github.io/react-remark/?path=/story/remark-component--mixed-html-sanitized
The source for the example is https://github.com/ChristianMurphy/react-remark/blob/441254abfe378d34fa237639988cbe37bb0dd758/stories/remark-component.stories.tsx#L44-L59

**Comment by ChristianMurphy** [comment]
> You could also look into using remark, remark-rehype, rehype-react directly!

Yep, https://github.com/ChristianMurphy/react-remark is just a thin wrapper around `remark`, `remark-rehype`, and `rehype-react`. They can be used directly as well.

**Comment by wooorm** [comment]
Going to close this here, as there‘s nothing we need to change in this project.

FWIW, I pinged @/rexxars about this, they’ll look into the PRs but I think they’re busy
