### ISSUE TITLE
add remark-cli command line usage with options to README

### ISSUE THREAD

**Issue by muescha** [remarkjs/remark#510]
### Subject of the feature

The command line usage of plugins with options are not described in the [remark-cli readme](https://github.com/remarkjs/remark/tree/main/packages/remark-cli)

### Problem

I don't found an info about this in remark and remark-cli readme

### Example

found here: https://github.com/remarkjs/remark-validate-links

```shell
remark --use 'validate-links=repository:"foo/bar"' example.md
```

maybe also write how i can use 2 parameters...

### Alternatives

n/a

**Comment by ChristianMurphy** [comment]
@muescha https://github.com/remarkjs/remark/tree/main/packages/remark-cli#cli give a high level overview of the options, it also  links to https://github.com/unifiedjs/unified-args#cli which describes the options in depth, including how to `--use` plguins https://github.com/unifiedjs/unified-args#--use-plugin

> maybe also write how i can use 2 parameters

The documentation may help, if you have a specific question on using options together feel free to reach out at https://spectrum.chat/unified/unified

**Comment by muescha** [comment]
thanks for the fast reply. 

the linked docs are very detailed :)

*it is easy to miss the line above: "See [unified-args](https://github.com/unifiedjs/unified-args#cli), which provides the interface, for more info on all available options."*

**Comment by wooorm** [comment]
What about another bullet at the start of the initial list, saying: "Interface by [unified-args]"? Packages/remark also has such an initial item.

Generally though, adding an example of one thing, will make the readme more verbose, and instead *harder* to find all the other things.

**Comment by muescha** [comment]
i think just put the info just below the CLI package help block like:

```markdown
## CLI

...

## Usage

A detailed description of all available options of `remark-cli` are at: [`unified-args`][unified-args].
```

--> because while i scan the readme i would there expect at this place the details how to use it



> See unified-args, which provides the interface, for more info on all available options.

this line i "translated" for me at first glimpse as: "this tool uses unified-args, if you also like to use unified-args in your tool, then look at the link for options how you can implement it for your tools"

**Comment by wooorm** [comment]
We already have a Use section, which typically contains a basic example, adding another one doesn’t make sense to me.
I added another link at the top: https://github.com/remarkjs/remark/commit/4673f75f0eb7d117aa386ef963e25636fba88ec4.
I’m not sure what to do with “at first glimpse”, I of course want to make docs better but this also sounds like not reading the docs. The link to unified-args is in there twice now, I hope that’s enough!

**Comment by muescha** [comment]
if you have the command documentations (for example also the "man pages" -> `man less` in terminal) then you have mostly this order:

1. name
2. short description
3. overview of options
4. option details
(5. examples)

so i looked at position 4 for the option details and can not find infos. then i was not expecting in section 2 to find the infos behind in this link in the description

so placing the info with link after the codeblock would helped me:

```markdown
## CLI

...
...
...

A detailed description of all available options of `remark-cli` are at: [`unified-args`][unified-args].
```


PS: also your docs at https://github.com/unifiedjs/unified-args#cli follow this order
