### ISSUE TITLE
Empty table cells do not render correctly

### ISSUE THREAD

**Issue by RandyMustache** [remarkjs/remark#511]
### Subject of the issue

Describe your issue here.

This is *not* a place to ask questions.  For that, go to [spectrum](https://spectrum.chat/unified/remark)

### Steps to reproduce

If you create a table, and the last column is empty, it does not correctly render. For reference, this works on GitHub.

Using the demo as an example: 
```
| Feature   | Support | Empy |
| --------- | ------- | ---- |
| tables    | ✔ |
| alignment | ✔ |
| wewt      | ✔ |
```
You get this:
<img width="1183" alt="image" src="https://user-images.githubusercontent.com/16965913/87389253-86a9eb00-c5fa-11ea-863f-90d5f86a33b5.png">

and the cells do not appear in the markup:
<img width="312" alt="image" src="https://user-images.githubusercontent.com/16965913/87274367-b9d37800-c52f-11ea-872d-25adda614581.png">

Investigating in the AST explorer shows the table rows only have 2 children as well, instead of the expected 3.
<img width="1396" alt="image" src="https://user-images.githubusercontent.com/16965913/87388875-befcf980-c5f9-11ea-8680-998c774ba002.png">

### Expected behaviour

It should render as GH renders tables. 

| Feature   | Support | Empy |
| --------- | ------- | ---- |
| tables    | ✔ |
| alignment | ✔ |
| wewt      | ✔ |

### Actual behaviour

Empty cells do not render.

**Comment by wooorm** [comment]
As your question includes the word “rendering”, well, that implies stuff outside of remark core. Something with HTML, perhaps?

Please complete the relevant parts, such as environment and steps to reproduce, of the issue template: https://raw.githubusercontent.com/remarkjs/.github/main/.github/ISSUE_TEMPLATE/1-bug.md

**Comment by wooorm** [comment]
Given this `package.json`:

```json
{
  "name": "example",
  "version": "1.0.0",
  "description": "",
  "main": "example.js",
  "dependencies": {
    "rehype-stringify": "^8.0.0",
    "remark-parse": "^8.0.2",
    "remark-rehype": "^7.0.0",
    "unified": "^9.0.0"
  },
  "devDependencies": {},
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}
```

And this script, `example.js`:

```js
var unified = require('unified')
var markdown = require('remark-parse')
var remark2rehype = require('remark-rehype')
var html = require('rehype-stringify')

var doc = `| Feature   | Support | Empy |
| --------- | ------- | ---- |
| tables    | ✔ |
| alignment | ✔ |
| wewt      | ✔ |
`

unified()
  .use(markdown)
  .use(remark2rehype)
  .use(html)
  .process(doc, function (err, file) {
    console.error(err)
    console.log(String(file))
  })
```

Yields, when running `node example`:

```html
null
<table>
<thead>
<tr>
<th>Feature</th>
<th>Support</th>
<th>Empy</th>
</tr>
</thead>
<tbody>
<tr>
<td>tables</td>
<td>✔</td>
<td></td>
</tr>
<tr>
<td>alignment</td>
<td>✔</td>
<td></td>
</tr>
<tr>
<td>wewt</td>
<td>✔</td>
<td></td>
</tr>
</tbody>
</table>
```

---

Your problem probably results from a) other packages, such as MDX, react-markdown, Gatsby, Next, etc. b) old versions.
