### ISSUE TITLE
Value of code block without end mark should not include final new line

### ISSUE THREAD

**Issue by fisker** [remarkjs/remark#512]
### Subject of the issue

Value of fenced code block without end mark should not include final new line.

### Your environment

*   **OS**:  windows
*   **Packages**: 8.0.2
*   **Env**: Node.js@v14

### Steps to reproduce

Parse following code (Note: code ends with 2 `\n`s)

````markdown
```
a


````

### Expected behaviour

`node.value` Should end with one `\n`.

### Actual behaviour

`node.value` end with two `\n`s

[commonmark](https://spec.commonmark.org/dingus/?text=%60%60%60%0Aa%0A%0A)

Context: https://github.com/prettier/prettier/pull/8786

**Comment by wooorm** [comment]
Your proposed behavior is as I see it not documented, or perhaps even against, the spec:

> If the end of the containing block (or document) is reached and no closing code fence has been found, the code block contains all of the lines after the opening code fence until the end of the containing block (or document)
> [CM](https://spec.commonmark.org/0.29/#fenced-code-blocks)

I don’t see the expected behavior in the CM dingus AST tab?

**Comment by fisker** [comment]
Thanks for the quick response and the document, so do you think the behavior in commonmark is a bug?

**Comment by wooorm** [comment]
CM is a specification that describes, let’s say, 90% of Markdown. There are reference implementations (cm.js, cmark), but those sometimes have bugs, and they have their own behavior. To be CM compliant / support CM is to match the spec, not the reference implementations.

> so do you think the behavior in commonmark is a bug?

a) “I don’t see the expected behavior in the CM dingus AST tab?” I see CMs AST and MDAST being the same?
b) If they’re different, I think they’re differences in behavior, neither really features nor bugs.

**Comment by fisker** [comment]
[This one](https://spec.commonmark.org/dingus/?text=%60%60%60%0Aa) with ends with `a`

And 

[This one](https://spec.commonmark.org/dingus/?text=%60%60%60%0Aa%0A) with ends with 1 `\n`


They have the same AST, but remark has different value.

**Comment by wooorm** [comment]
I see, thanks!

I still believe this doesn’t make sense on their side (see my previous point b). For some reason they are swallowing a line feed character 🤷‍♂️, that behavior does not make sense from the spec:

> **the code block contains all of the lines after the opening code fence until the end of the containing block (or document)**

**Comment by fisker** [comment]
Thank you. I'll close

**Comment by wooorm** [comment]
Alright, I don’t think there’s anything to do here. I’m not sure this is significant enough to bring into the spec, and I’m not sure it’s something they’d want to change in cm.js either!
