### ISSUE TITLE
Strong element containing a single newline is not parsed correctly

### ISSUE THREAD

**Issue by emmerich** [remarkjs/remark#519]
### Subject of the issue

A strong tag containing a single newline character is not correctly parsed.

### Your environment

*   **OS**: Catalina 10.15.5
*   **Packages**: remark-parse 8.0.2
*   **Env**: node v10.16.0

### Steps to reproduce

Newline Example:

```markdown
**
**
```

### Expected behaviour

The AST should be parsed with an empty strong block.

### Actual behaviour

The asterisks are interpreted as text themselves:

```json
{
  "type": "root",
  "children": [
    {
      "type": "paragraph",
      "children": [
        {
          "type": "text",
          "value": "**\n**"
        }
      ]
    }
  ]
}
```

**Comment by wooorm** [comment]
Although some of our strong and emphasis parsing is broken, this is in fact expected behavior per [CommonMark](https://spec.commonmark.org/dingus/?text=**%0A**)

**Comment by emmerich** [comment]
@wooorm I'm running the parser in GFM Mode, where the above example should give an empty strong node.

**Comment by wooorm** [comment]
I don‘t get strong emphasis here either:

**
**

(GFM is now based on CM)

**Comment by emmerich** [comment]
> I don‘t get strong emphasis here either:
> 
> **
> **
> 
> (GFM is now based on CM)

(yes, apologies, deleted my comment after doing a bit more testing - seems it only works in some editors but it's not a standard)

**Comment by wooorm** [comment]
Fwiw, GFM is based on CM for the last two years. Some markdown parsers (like remark) are in a transitional phase. https://github.com/remarkjs/remark/issues/439
