### ISSUE TITLE
Failed to load wcwidth module

### ISSUE THREAD

**Issue by wsdjeg** [remarkjs/remark#522]
I want to use remark command line to format markdown file which contains chinese. I have installed wcwidth module via:

`npm -g install wcwidth`, and the config file is:

```js
module.exports = {
  settings: {
    listItemIndent: '1',
    stringLength: require('wcwidth'),
  },
  plugins: [
    require('remark-frontmatter'),
  ]
};
```

the command is `remark --no-color --silent -r C:\Users\wsdjeg\AppData\Local\Temp\nvimVhnAyD\0.js 2> C:\Users\wsdjeg\AppData\Local\Temp\neoformat\stderr.log`, but I still get error :

```
'Error: Cannot find module ''wcwidth'''
```

**Comment by ChristianMurphy** [comment]
remark runs the file, meaning it will scan for the dependency using https://nodejs.org/api/modules.html#modules_loading_from_node_modules_folders
Depending on your setup `npm install --global` may not install the dependency into a folder node will scan.
Try running `npm install wcwidth` in the folder with the project.

If there are follow up questions feel free to reach out on https://spectrum.chat/unified/remark

**Comment by wsdjeg** [comment]
@ChristianMurphy why this issue is closed?  I was just want to using remark to format the markdown file in my project.  if it is not a is project,  why I should install it locally?  and why remark do not support wcwidth by default?

**Comment by ChristianMurphy** [comment]
> why this issue is closed?

Please read the template for question https://github.com/remarkjs/.github/blob/main/.github/ISSUE_TEMPLATE/3-help.md, this is a question, please direct all questions to Spectrum https://spectrum.chat/unified/remark

> if it is not a is project, why I should install it locally?

Again see my previous comment, it can be installed anywhere where node scans.
Node does not scan the global folder by default.
It isn't an issue with remark, it's how Node and JavaScript work.
