### ISSUE TITLE
Fenced code block lang and meta not separated by curly bracket

### ISSUE THREAD

**Issue by kachkaev** [remarkjs/remark#528]
### Subject of the issue

When splitting the code block flag into `lang` and `meta`, remark does not account for this case:

````markdown
```js{foo=1 bar=2 baz=3}
console.log("hello world");
```
````

According to the current implementation, only spaces and tabs are considered as separators:

https://github.com/remarkjs/remark/blob/8d8e3bcfbc1c89b8eae9119703f13414269ebf73/packages/remark-parse/lib/tokenize/code-fenced.js#L230-L245

Not taking `{` into the account leads to an issue in Prettier. For example, a flag like `mylang{foo="hello   world"}` is split into `mylang{foo="hello` and `world"}` instead of `mylang` and `{foo="hello   world"}`. When Prettier stitches back `lang` and `meta`, the result becomes `mylang{foo="hello    world"}`, i.e. extra spaces are lost. See [Playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEADdArAzgAmAMwggF4BGHAIwEMAnYgJkqoC9iBmAXwB0pIosIAGzgA6QRADmACi4gAFnEHicAdwg1BAE1kBKANw90qHocy4cFiwSJlLl6nUZ3qrTjz4DhYyTPmLlahraIPqmxlBh2DiEJOR2TI7OLOzu0J6i4tKyCkoQqupaugZQRiYlZvHRNnFJifbJbKn8Qhk+2f55gYUhxaUR-UbY1rGVCQyVLuzcvGkt3ll+uflBRWFlg1jDtg7jk24zzV6ZvjkBBcGh5eHrZsB2Mbb1dRZ78dMec8ftS10XveggAA0IAgAAcYABLNLIUC0GgQFQABVoCCwyBAVEEKioAE80cCKDQqGAANZwGAAZVBxIhUAkyBgNAArnBgXAALYUOCaTTcgAyVDpTKoEjgADF1OyqDBIXT0VQmTAIED5DB2YIAOpyCHwLDUsBwCmonUQgBuOpx6LAWHxIFpWDgNBgiKJEilyHwmIdwOwAA8AEJE0nkilUdlwPm0uAer2skB+im0iTCACKTIg8Bjgm9IGpNAdNHRUpoJM0CKgKtBNFpMA1EM0MDkyAAHAAGYFViAOjVE0HoqtwAum6PAgCO6fgLrBaJQVCwAFooHBudyVTQ4OOIeuXSL3UhPdm4w72RCGcyj0nUxPo-vY8CYFQKHWG02kPR70SIYIkwBhCDsvcQEHABWFUmQdAAVR8ZwPHNTRZABJKBeVgCkwGrcEAEFkIpGAcWELMHQ4DggA).

If accepting `{` as a separator between `lang` and `meta` can count as a bugfix, I'm happy to open a PR that would add it. Doing so will save Prettier from a need to [hack the `lang` value](https://github.com/prettier/prettier/blob/370844cc4cbe3c43b8e699e3e4bcec215bd94e08/src/language-markdown/embed.js#L15-L17) – this workaround dates back to remark v5, i.e. before #345.

Looking at how Prettier does `const langMatch = node.lang.match(/^[\w-]+/);`, perhaps we can also do the same in remark. I can't imagine a scenario in which lang would not match this regex 🤔

### Your environment

*   **OS**: web
*   **Packages**: remark-parse v8.0.3 via prettier v2.1.1
*   **Env**: browser

**Comment by wooorm** [comment]
🤔

That's how commonmark (and gfm too) works 🤷‍♂️

**Comment by wooorm** [comment]
What are you needing the brace syntax for? Can you add a space before that?

**Comment by kachkaev** [comment]
Braces are used in https://shd101wyy.github.io/markdown-preview-enhanced/#/code-chunk to separate lang from the metadata, i.e. no space is needed. Also Prettier does `const langMatch = node.lang.match(/^[\w-]+/);`, i.e. ` ```js{xyz}` is treated as the JS block.

Could you please share the parts of the specs for commonmark and gfm which refer to separating lang and metadata? I thought these two parts are one indivisible piece there 🤔

The reason for creating this issue was https://github.com/gicentre/litvis/issues/50.

**Comment by wooorm** [comment]
> The content of a code fence is treated as literal text, not parsed as inlines. The first word of the info string is typically used to specify the language of the code sample, and rendered in the class attribute of the code tag. However, this spec does not mandate any particular treatment of the info string.
> Fenced code (https://spec.commonmark.org/0.29/#fenced-code-blocks, last paragraph of intro)

The first word is defined in a certain way here, but what’s more important is that, after that word, stuff is undefined.
In remark, we expose both the `lang` and the `meta` part of the info string, so other tools can access both.

While the language is the spec is pretty vague, commonmark does have test, saying that:

```markdown
~~~~    ruby startline=3 $%@#$
def foo(x)
  return 3
end
~~~~~~~
```

yields:

```html
<pre><code class="language-ruby">def foo(x)
  return 3
end
</code></pre>
```

While vague. The word “word” implies some form of, typically whitespace, break. In CM, that means one or more spaces or tabs (as in this case line endings don’t make sense). This is also what other implementations seem to use: drop everything after the first space

**Comment by wooorm** [comment]
All those examples in markdown-preview-enhanced also add a space before those braces? 🤔

**Comment by kachkaev** [comment]
IC. Yeah it seems that the spec is a bit vague indeed. It would not be too wrong to argue that a word is a set of alphanumeric characters, i.e. excluding the punctuation.

Although markdown-preview-enhanced examples put space before `{`, the parser treats ` ```lang {xyz} ` and ` ```lang{xyz}` equally. So does Atom and, because of that, Prettier: https://github.com/prettier/prettier/pull/4783.

If redefining what is meant by 'word' is hard, perhaps, remark could help downstream libraries do this on their own?

At the moment, the AST ends up [with `lang` and `meta`](https://github.com/remarkjs/remark/blob/8d8e3bcfbc1c89b8eae9119703f13414269ebf73/packages/remark-parse/lib/tokenize/code-fenced.js#L249-L250), thus loosing the spacing information between the two. Perhaps, adding `node.flag` or `node.rawLang` would help here? Without this, it is impossible to avoid the conversion from ` ```js{foo="hello   world"}` into ` ```js{foo="hello world"}` by Prettier, which looks like a regression. Happy to submit a PR that adds this extra field to the resulting node.

**Comment by wooorm** [comment]
> It would not be too wrong to argue that a word is a set of alphanumeric characters, i.e. it does not contain punctuation

Right, although to add: there are many cases where the spec can be a bit vague, [but then testing out implementations is a good way to go](https://babelmark.github.io/?text=%60%60%60asd%7Bqwe+zxc%0A%60%60%60%0A)

> At the moment, the AST ends up with lang and meta, thus losing the spacing information between the two.

I don’t believe your problem is losing the spacing info. If you use the space between the language and the meta, which is supported by markdown-preview-enhanced, commonmark, and remark, everything should be fine.
If that space between lang and meta is removed by prettier, then that’s a bug there, as it is significant.
All spaces and tabs in meta *are* preserved in remark.

I’m also not too happy with the proposed solution: that would introduce duplicate information in the tree, which is extremely hard to programmatically deal with (transformers in unified will update one but forget about the other), which’ll lead to unexpected results.

**Comment by kachkaev** [comment]
> If that space between lang and meta is removed by prettier, then that’s a bug there, as it is significant.

The only reason why the space is removed by Prettier is because the boundary between the lang and the meta is in the "wrong" place.

For an input like `js{foo="hello   world"}` Remark produces `lang` = `js{foo="hello` and `meta` = `world"}`. What Prettier does is looking into `js{foo="hello`, [extracting](https://github.com/prettier/prettier/blob/370844cc4cbe3c43b8e699e3e4bcec215bd94e08/src/language-markdown/embed.js#L15-L17) `js` from it to parse contents and then [stitching](https://github.com/prettier/prettier/blob/370844cc4cbe3c43b8e699e3e4bcec215bd94e08/src/language-markdown/printer-markdown.js#L248-L249) whatever Remark’s `lang` and `meta` values with a single space. There is no way to tell how many spaces were there in `hello   world`.

The ideal solution as I see it would be to add detection of syntax characters to [this](https://github.com/remarkjs/remark/blob/8d8e3bcfbc1c89b8eae9119703f13414269ebf73/packages/remark-parse/lib/tokenize/code-fenced.js#L230-L245
) block, so that Remark produces `lang` = `js` and `meta` = `{foo="hello   world"}` in the first place. Including duplicate `node.info` into the result is plan B.

**Comment by wooorm** [comment]
What I’m saying is the source, your markdown, according to commonmark, gfm, and remark, should be `js {stuff}`. As my link to babelmark shows: most parsers don’t detect the language if you don’t use that space. If you’re going to add stuff after the code language, there *must* be a space.

I can’t speak for prettier: I’m not sure what it does or why

**Comment by wooorm** [comment]
The extra handling of `lang` that prettier does, or atom as you mention, makes sense to me for an implementor: if you know about the syntax languages you support, you can drop some more characters from `lang`. However: as a markdown parser we don’t know about syntax highlighting.

**Comment by wooorm** [comment]
Can you add a space between the language and the meta? Does that work for you? (`lang {extra}`)

**Comment by kachkaev** [comment]
Adding space is certainly possible. The problem is that there are tools like Prettier, Markdown Preview Enhanced and Atom syntax highlighting, which guess the lang 'correctly' even when there is no space. This discrepancy may cause confusion in the eyes of someone who does not need to know about all the different tools involved in their workflow. An example would be https://github.com/gicentre/litvis/issues/50.

I shared some thoughts in https://github.com/prettier/prettier/issues/9155#issuecomment-688289879, feel free to join the conversation there.

**Comment by wooorm** [comment]
The discrepancy is unrelated: you mention that some tools, when they infer the actual code language, drop more stuff. They can already drop more stuff if they want to, regardless whether some code lands here or not

**Comment by kachkaev** [comment]
> They can already drop more stuff if they want to, regardless whether some code lands here or not

That is correct. What they can't do is to get the original number of spaces between what remark considered lang and meta. If for Prettier, the right split is `js` + `{foo="hello   world"}` and not `js{foo="hello`, `world"}`,

- Prettier _can_ derive `js` form `js{foo="hello` but
- Prettier _cannot_ restore original string or make it `js {foo="hello   world"}` (by adding a space between `js` and `{`. The number of spaces between `hello` and `world` does not exist in the remark's AST. That's what's making the potential solution in https://github.com/prettier/prettier/issues/9155 hacky or impossible.

**Comment by wooorm** [comment]
> What other tools can't do is to get the original number of spaces

That is implied with ASTs. One of the reasons why I made [micromark](https://github.com/micromark/micromark) (CST). It has a whitespace token between those two. It may be time for Prettier to make the switch to that.

> Prettier cannot restore the original string

Similarly, prettier also cannot restore whether `*` or `_` was used for emphasis through the AST. However, there’s positional information on nodes, and you have access to the original document. So you *can* detect all those things. You can do these things.

> your definition of a 'word'

As shown earlier with babelmark, that definition of word is shared by most markdown implementations, but there are no markdown implementation that follow the way you propose.

**Comment by wooorm** [comment]
I’ll close this, it’s not something that should be done here as it would differ from commonmark, although a micromark extension could do it.

**Comment by kachkaev** [comment]
Hi @wooorm, sorry for disappearing. After thinking about this delimiter problem again, I’m leaning towards agreeing with you now. _Space+tab_ is only non-vague combination of symbols we can pick for a delimiter. If we say it's also `{`, then why not any arbitrary range of UTF8 characters. The debates would never settle and different implementations will diverge from each other even further than they are now. 

I'm going to try to persuade Prettier folks to stop supporting non-whitespace delimiters. Not sure how soon this will land though because this is a breaking change. Thank you for finding time on this conversation! 🙌

**Comment by wooorm** [comment]
Awesome! And no problem. And glad that you understand!
