### ISSUE TITLE
Support for Wiki-Style ([[]]) Links

### ISSUE THREAD

**Issue by iamrecursion** [remarkjs/remark#531]
### Subject of the feature
Many implementations of wiki-style markdown such as [obsidian](https://obsidian.md/), [foam](https://github.com/foambubble/foam), [azure devops wiki](https://docs.microsoft.com/en-us/azure/devops/project/wiki/wiki-markdown-guidance?view=azure-devops) use double-square-brackets to mark internal links. It would be good to be able to optionally parse these as an AST entity in remark for use by downstream tools such as prettier. See prettier/prettier#9161 for further discussion.

Is support for this something that remark would consider as a project? If so, what would be the most appropriate approach?

### Problem
Prettier doesn't have the ability to recognise `[[]]`-style links as a separate entity due to the fact that it depends on the remark AST.

### Expected behavior
Ideally, we should be able to make remark parse `[[]]`-style links as an AST entity, such that downstream tools can treat them in special ways where necessary.

### Alternatives

There aren't really alternatives to this, short of writing a hack in prettier itself that traverses and transforms the AST to add an additional node.

**Comment by wooorm** [comment]
Hi there Ara!

In remark (and unified as a whole), we typically do everything with plugins. As foam is also made on remark, I checked with them and saw that they [support wiki links with a plugin too](https://github.com/foambubble/foam/blob/bcab41917a0a67a9d737fa24472b163f7220182d/packages/foam-core/package.json#L35).

That plugin seems a bit alpha, at 0.0.4, so not sure how great that is 🤷‍♂️ Alternatively it could serve as inspiration for your own plugin. If you have a plugin it’s a matter of adding one line of code to prettier (although I’ll leave whether it makes sense for ’em, up to the prettier folks)

**Comment by iamrecursion** [comment]
Thanks so much for the pointer and explanation! I'll go back to the prettier folks and continue the discussion!
