### ISSUE TITLE
Latest released version of remark-parse doesn't work with current remark-frontmatter

### ISSUE THREAD

**Issue by ryanfiller** [remarkjs/remark#537]
### Subject of the issue

Version compatibility issue because `remark-parse@9`, which is compatible with `remark-frontmatter@3` is under a prerelease tag while `remark-frontmatter` isn't. The latest released version of `remark-parse` doesn't work with `remark-frontmatter` which automatically installs v3

### Your environment

*   **OS**: macOS 10.14.6
*   **Packages**: `remark-frontmatter`, `remark-parse`
*   **Env**: "svelte": "^3.0.0", "sapper": "^0.27.0"

### Steps to reproduce

```
const unified = require('unified')
const remarkParse = require('remark-parse')
const remarkStringify = require('remark-stringify')
const remarkFrontmatter = require('remark-frontmatter')

const MD = `---
foo: 'bar'
---

# Hello, world!
`

unified()
  .use(remarkParse)
  .use(remarkFrontmatter, ['yaml'])
  .use(remarkStringify)
  .use(opts => tree => console.log(tree))
  .process(MD)
  .then(console.log)
```

This code should surface the error.

### Expected behavior

With a fresh `npm install`, package should correctly find `node.type === yaml`

### Actual behavior

Package is unable to produce `yaml` nodes.

**Comment by wooorm** [comment]
That is correct. See the release notes of remark-frontmatter: https://github.com/remarkjs/remark-frontmatter/releases/tag/3.0.0

**Comment by wooorm** [comment]
To add: it’s been a couple of days and will take some more, but it’s always a bit of a hassle to update hundreds of projects, so please bare with us while we’re in the middle of things!

**Comment by ryanfiller** [comment]
No worries at all! I was talking with @4lpine in Discord and he helped me work through this and requested I file an issue. Please let me know if there's anything else I can do to help.

**Comment by wooorm** [comment]
That’s a good suggestion from @johno! Yes, I do appreciate folks letting us know here about what they’re running into. Even though the answer is to match the versions of the two projects and hence this issue doesn’t need to stay open, it’ll help other folks who google or search otherwise to find it!

And feel free to let us know directly here about all your questions too!
