### ISSUE TITLE
Allow "marking" the parent that it contains list items?

### ISSUE THREAD

**Issue by dvkndn** [remarkjs/remark#542]
There's a small difference between GitHub's renders and remark's GFM mode, that GitHub has the "contains-list-item" class attached to the "ul" parent. Is this possible with remark?

Remark:
![Screenshot from 2020-10-18 02-14-21](https://user-images.githubusercontent.com/5953369/96351751-a9f7a100-10e7-11eb-9b56-9b1697baecdb.png)

GitHub:
![Screenshot from 2020-10-18 02-14-02](https://user-images.githubusercontent.com/5953369/96351753-abc16480-10e7-11eb-8818-5e5fc459db38.png)

Related: https://github.com/remarkjs/remark/commit/ec9c2cb15705814a2cd36e9bd09a4d84048afb74

**Comment by ChristianMurphy** [comment]
@dvkndn are you using `remark-parse` 8 or `remark-parse` 9 with `remark-gfm`?

**Comment by wooorm** [comment]
Yeah, seconded, I believe we’re adding the `contains-task-list` for several versions already!

**Comment by dvkndn** [comment]
Oh sorry guys! I was using an outdated version! Thank you for the quick support!

![Screenshot from 2020-10-18 16-33-46](https://user-images.githubusercontent.com/5953369/96363618-b8819f00-115f-11eb-9b0c-73204463e381.png)
