### ISSUE TITLE
Renders additional <!----> 

### ISSUE THREAD

**Issue by cristianvasquez** [remarkjs/remark#565]
Hello, 

Thanks for 'remark'! 

My report:

### Subject of the issue

```javascript
var remark = require('remark')
text = `
# Today list
* Buy milk
+ Buy cheese
`

remark()
    .process(text, function (err, file) {
        console.log(String(file))
    })
```

### Expected behavior

```markdown
# Today list

*   Buy milk
*   Buy cheese
```
### Actual behavior

renders:

```markdown
# Today list

*   Buy milk

<!---->

*   Buy cheese
```

**Comment by wooorm** [comment]
This is slightly unfortunate but expected: commonmark doesn't allow lists of the same type next to each other (as in your example: two unordered lists). The only two ways to break them up are different markers (as your input shows, but that's not very nice), or such a comment.

It's not great, but it's intended behavior!

**Comment by cristianvasquez** [comment]
Thanks @wooorm for the response!
