### ISSUE TITLE
Rendering escapes [ ] tasks

### ISSUE THREAD

**Issue by cristianvasquez** [remarkjs/remark#566]
Hello, 

Thanks for 'remark'! 

My report:

### Subject of the issue

```javascript
var remark = require('remark')
text = `
# Task List
*   [ ] Buy milk
`

remark()
    .process(text, function (err, file) {
        console.log(String(file))
    })
```

### Expected behavior

```markdown
# Task List

*   [ ] Buy milk
```
### Actual behavior

renders:

```markdown
# Task List

*   \[ ] Buy milk
```

**Comment by ChristianMurphy** [comment]
@cristianvasquez task lists are a part of GitHub flavored markdown (GFM).
In commonmark, you example is seen as an unmatched link reference, the escaping is expected.
To add GFM support use `remark-gfm`, which will recognize the task list.

for example: https://codesandbox.io/s/remark-debug-forked-ihmnb

**Comment by cristianvasquez** [comment]
Thanks Christian!
