### ISSUE TITLE
Can't create a table

### ISSUE THREAD

**Issue by optimalui** [remarkjs/remark#584]
I am trying to create a md file .But it cant create a table.

I tried like this:

|---|---|---|---|---|
|   |   |   |   |   |
|   |   |   |   |   |
|   |   |   |   |   |
But it parsed like this:

| | | | | | |---|---|---|---|---| | | | | | | | | | | | | | | | | | |

How can I create a markdown file with table using remark?

Thanks

**Comment by ChristianMurphy** [comment]
this is documented in the release notes https://github.com/remarkjs/remark/releases/tag/13.0.0
use https://github.com/remarkjs/remark-gfm
