### ISSUE TITLE
The contents of svg and math tags are split

### ISSUE THREAD

**Issue by akabekobeko** [remarkjs/remark#618]
### Subject of the issue

The contents of the `<svg>` and `<math>` tags are not a single `html`, but are split into separate` text` and `html` for each element. The `<table>` and `<a>` tags, including their children, are a single `html`.

The problem with this behavior is that if a newline in `<svg>` becomes `text` due to splitting, it will be processed by `remark-breaks` and `<br>` will be inserted.

### Your environment

*   **OS**: macOS Big Sur 11.1 (20C69)
*   **Packages**: 
  * remark-parse 9.0.0
  * remark-gfm 1.0.0
  * unified 9.2.0
*   **Env**:
  * Node.js 15.6.0
  * npm 7.4.0 

### Steps to reproduce

I've prepared a project for verification, so I think it's easy to check with this. Can check the phenomenon of this issue by setting up and executing according to the `README.md`.

- [akabekobeko/test-remark-parse-html](https://github.com/akabekobeko/test-remark-parse-html)

### Expected behavior

`<svg>` and `<math>` are parsed as a single `html` like any other tag.

### Actual behavior

The parse result for the `<svg>` and `<math>` tags does not result in a single `html`. Child and closing tags are split into separate `html` and `text`.  Below is the output formatted by `unist-util-inspect`.

```
root[6]
├─0 html "<table>\n<tbody>\n  <tr><td>aaa</td></tr>\n</tbody>\n</table>"
├─1 html "<iframe>\ntest\n</iframe>"
├─2 html "<div>\naaaaa\n</div>"
├─3 html "<a href=\"sample.jpg\">\ntest\n</a>"
├─4 paragraph[3]
│   ├─0 html "<svg xmlns=\"http://www.w3.org/2000/svg\" version=\"1.1\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" width=\"100%\" height=\"100%\" viewBox=\"0 0 3000 3000\">"
│   ├─1 html "<image width=\"3000\" height=\"3000\" xlink:href=\"../image/cover.jpg\"/>"
│   └─2 html "</svg>"
└─5 paragraph[36]
    ├─0 html "<math>"
    ├─1 html "<mrow>"
    ├─2 html "<mrow>"
    ├─3 html "<msup>"
    ├─4 html "<mi>"
    ├─5 text "a"
    ├─6 html "</mi>"
    ├─7 html "<mn>"
    ├─8 text "2"
    ├─9 html "</mn>"
    ├─10 html "</msup>"
    ├─11 html "<mo>"
    ├─12 text "+"
    ├─13 html "</mo>"
    ├─14 html "<msup>"
    ├─15 html "<mi>"
    ├─16 text "b"
    ├─17 html "</mi>"
    ├─18 html "<mn>"
    ├─19 text "2"
    ├─20 html "</mn>"
    ├─21 html "</msup>"
    ├─22 html "</mrow>"
    ├─23 html "<mo>"
    ├─24 text "="
    ├─25 html "</mo>"
    ├─26 html "<msup>"
    ├─27 html "<mi>"
    ├─28 text "c"
    ├─29 html "</mi>"
    ├─30 html "<mn>"
    ├─31 text "2"
    ├─32 html "</mn>"
    ├─33 html "</msup>"
    ├─34 html "</mrow>"
    └─35 html "</math>"
```

**Comment by wooorm** [comment]
[This behavior](https://astexplorer.net/#/gist/bd3d37fd89c5f803c3cee267114bbf55/0f20b695c61312faa7822cf54bdbfefbe8a737f4) is the same [as CommonMark](https://spec.commonmark.org/dingus/?text=%3Ctable%3E%0A%3Ctbody%3E%0A%20%20%3Ctr%3E%3Ctd%3Eaaa%3C%2Ftd%3E%3C%2Ftr%3E%0A%3C%2Ftbody%3E%0A%3C%2Ftable%3E%0A%0A%3Ciframe%3E%0Atest%0A%3C%2Fiframe%3E%0A%0A%3Cdiv%3E%0Aaaaaa%0A%3C%2Fdiv%3E%0A%0A%3Ca%20href%3D%22sample.jpg%22%3E%0Atest%0A%3C%2Fa%3E%0A%0A%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20version%3D%221.1%22%20xmlns%3Axlink%3D%22http%3A%2F%2Fwww.w3.org%2F1999%2Fxlink%22%20width%3D%22100%25%22%20height%3D%22100%25%22%20viewBox%3D%220%200%203000%203000%22%3E%3Cimage%20width%3D%223000%22%20height%3D%223000%22%20xlink%3Ahref%3D%22..%2Fimage%2Fcover.jpg%22%2F%3E%3C%2Fsvg%3E%0A%0A%3Cmath%3E%3Cmrow%3E%3Cmrow%3E%3Cmsup%3E%3Cmi%3Ea%3C%2Fmi%3E%3Cmn%3E2%3C%2Fmn%3E%3C%2Fmsup%3E%3Cmo%3E%2B%3C%2Fmo%3E%3Cmsup%3E%3Cmi%3Eb%3C%2Fmi%3E%3Cmn%3E2%3C%2Fmn%3E%3C%2Fmsup%3E%3C%2Fmrow%3E%3Cmo%3E%3D%3C%2Fmo%3E%3Cmsup%3E%3Cmi%3Ec%3C%2Fmi%3E%3Cmn%3E2%3C%2Fmn%3E%3C%2Fmsup%3E%3C%2Fmrow%3E%3C%2Fmath%3E) (see it’s AST tab).

To treat “tags” as “blocks”, have only that tag on the line, which you have done with the `<a>` case:

```markdown
<svg>
  ...whatever
</svg>
```

**Comment by akabekobeko** [comment]
Thank you. I understand that it is CommonMark compliant.

However, `<table>` is a block even if it is described by multiple lines and multiple tags. Is there any reason not to do so with other tags?

**Comment by wooorm** [comment]
Some known tags get special treatment: https://github.com/micromark/micromark/blob/main/lib/constant/html-block-names.mjs.

But again, with the line ending after the tag instead of another tag, the same behavior can be achieved: https://astexplorer.net/#/gist/853fa288ee42aa6844800eb95a3f3eb2/01ff19802dfc062495fafb67d8aedf9bdbeebced

**Comment by akabekobeko** [comment]
It's different from a special tag as CommonMark and other than that. I also understood other behaviors. Thank you for your polite response.
