### ISSUE TITLE
Custom component props lead to tailing backslash in mdx

### ISSUE THREAD

**Issue by rotpunkt-dev** [remarkjs/remark#620]
### Subject of the issue

Custom component props lead to tailing backslash in mdx.

### Your environment

*   **OS**: MacOS Big Sur
*   **Packages**:
 "remark-parse": "9.0.0",
    "remark-stringify": "9.0.1",
    "remark-mdx": "1.6.22",

*   **Env**: Node: 12, Yarn 1.22.4

### Steps to reproduce

```javascript var unified = require('unified')
var parse = require('remark-parse')
var stringify = require('remark-stringify')
var mdx = require('remark-mdx')

const testMd ='# Hello <Image alt={`Some alt text`}/>'

unified()
  .use(parse, {position: false})
  .use(stringify)
  .use(mdx)
  .process(testMd, function (err, file) {
    console.log(String(file))})
```

### Expected behaviour

No tailing backslash before component.

### Actual behaviour

A tailing backslash is added.
```
/* Output:
# Hello \<Image alt={`Some alt text`}/> */
```

**Comment by wooorm** [comment]
Hi there!

remark-mdx does define a compiler, overtaking the stringify step, so this is not something to fix here, and hence why I’ll close this.
You might want to use the latest beta of mdx-js, 2, which fixes many different things, probably also including this.
Furthermore, there’s more work on the `main` branch of mdx, which has not been released yet, but that would definitely fix this!
