### ISSUE TITLE
Consider adding syntax support for <mark> higlighting 

### ISSUE THREAD

**Issue by iljapanic** [remarkjs/remark#659]
### Subject of the feature

Many popular markdown editors such as iA Writer, Typora, Obsidian use `==` to denote highlighted text and wrap the output in `<mark>` tags.

It now seems to have become a standard notation for highlighting. See [discussion on CommonMark forum](https://talk.commonmark.org/t/highlighting-text-with-the-mark-element/840/15) for more details. I.e. [Remark supports the highlighting syntax](https://github.com/jonschlinkert/remarkable/tree/dev#syntax-extensions).

Here are details on the `<mark>` HTML element:

> The HTML Mark Text element (<mark>) represents text which is marked or highlighted for reference or notation purposes, due to the marked passage's relevance or importance in the enclosing context.

[Full `<mark>` spec](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/mark)

### Expected behavior

**Markdown**

```markdown
Vestibulum id ==ligula porta felis=== euismod semper.
```

**HTML output**

```html
Vestibulum id <mark>ligula porta felis</mark> euismod semper.
```

**HTML default rendering**

<img width="327" alt="Snapshot 2021-03-15 at 16 33 40@2x" src="https://user-images.githubusercontent.com/1295321/111179328-4301e980-85ac-11eb-83f5-7841eff3e750.png">

**Comment by wooorm** [comment]
Syntax extensions and other things in remark happen through plugins from community members.

Here’s an example of a remark plugin that adds supported for a new syntax, in this case math: https://github.com/remarkjs/remark-math/blob/main/packages/remark-math/index.js.

It defers to two other things. A micromark extension, which handles the tokenizing, and an mdast utility, which handles tokens -> ast, and ast -> string.
Most of the work for marks would be close to how strikethrough works: https://github.com/micromark/micromark-extension-gfm-strikethrough/blob/main/index.js.
