### ISSUE TITLE
Remark replaces CRLF with LF on Windows

### ISSUE THREAD

**Issue by NigeAtAnd** [remarkjs/remark#660]
### Subject of the issue

When running remark on Windows in auto-update mode, it replaces CRLF line endings with LF.

Sorry if this is the wrong repo to report this issue - let me know if so and I'll create it in the right one.

### Your environment

*   **OS**: Windows 10 64-bit 10.0.19042.804
*   **Packages**: remark-cli@9.0.0, remark-lint@8.0.0, remark-preset-lint-recommended@5.0.0
*   **Env**: node 12.16.3, yarn 1.22.4

### Steps to reproduce

1. On Windows, create a basic remark setup using remark-preset-lint-recommended
2. Create a markdown file containing no lint errors, using Windows-standard CRLF line endings
3. Run remark with `remark . -o`

### Expected behavior

Remark doesn't modify the file as it has no issues.

### Actual behavior

Remark changes the line endings in the markdown file from CRLF to LF.

**Comment by ChristianMurphy** [comment]
@NigeAtAnd could you expand on why this is an issue?

From a content/AST perspective I tend to think it isn't given that in an example like

```markdown
paragraph one

paragraph two
```

either CRLF or LF will separate the paragraphs.
If you want to preserve the exact characters, a concrete syntax tree would be needed, remark and mdast are both abstract and will keep the structure, but not the exact characters.
See https://github.com/syntax-tree/mdast/issues/36 for more context

It may be possible with micromark https://github.com/syntax-tree/mdast/issues/36#issuecomment-765637985 but a new abstraction over it will be needed.

**Comment by NigeAtAnd** [comment]
The issue makes itself obvious when using Git. Git users on Windows can use a config setting that auto translates between LF (on the server) and CRLF (on the client). This means all Windows tooling will work correctly with files from Git when they are accessed locally, as CRLF is the expected line ending. When files are pushed to remote, the CRLF is translated back to LF, to allow for consistency and interoperability between Windows and non-Windows users.

Remark breaks this by updating CRLF to LF locally, even for files that have valid markdown. These files will be shown as modified in Git (which makes sense, because they were) and will pollute commits with unintentional changes. These changes are also hard to diagnose because some tools don't distinguish between EOL types, so diffs can appear to be identical.

If it's technically feasible, it would be ideal if an optional config switch could be added which would either a) respect the native line ending format of the platform it's running on, or b) force LF or CRLF for line endings. Perhaps something like `"eolFormat": "auto"`/`"lf"`/`"crlf"`?

**Comment by ChristianMurphy** [comment]
> The issue makes itself obvious when using Git. Git users on Windows can use a config setting that auto translates between LF (on the server) and CRLF (on the client). This means all Windows tooling will work correctly with files from Git when they are accessed locally, as CRLF is the expected line ending. When files are pushed to remote, the CRLF is translated back to LF, to allow for consistency and interoperability between Windows and non-Windows users.

Right, git has it's own normalizer for line endings.
But how is it an issue? Is a file breaking?

> Remark [updates] CRLF to LF locally, even for files that have valid markdown.

Remark is rewriting all files because you set `-o` when you call `remark . -o`.
If remove `-o` it will not rewrite them.

**Comment by wooorm** [comment]
I believe there are very good tools to do this after remark. I don’t see much benefit in doing it here.

Also because, in certain cases, `\r`, `\n`, or `\r\n` *are* present in the syntax tree (say, code blocks).
That means that plugins would *also* need to detect which OS they’re running on. And that’s a lot of complexity.

So it’s not feasible other than as a post-processing step. And in that case, well, why not use a post-processing step (or let Git handle it?)

**Comment by NigeAtAnd** [comment]
> I believe there are very good tools to do this after remark. I don’t see much benefit in doing it here.
> 
> Also because, in certain cases, `\r`, `\n`, or `\r\n` _are_ present in the syntax tree (say, code blocks).
> That means that plugins, when they make code blocks, would _also_ need to detect which OS they’re running on. And that’s a lot of complexity.
> 
> So it’s not feasible other than as a post-processing step. And in that case, well, why not use a post-processing step (or let Git handle it?)

I worked around this by (eventually) managing to configure Git to use LF everywhere. I still think CRLF support would be useful but I'm closing this as I'm no longer affected by the issue.
