### ISSUE TITLE
Anchor generation from titles: inpage navigation will not work with non-english (latin) characters

### ISSUE THREAD

**Issue by bcs-gbl** [remarkjs/remark#693]
### Subject of the issue

Slug generation issue: if an md file title contains non-english (latin) characters (like é,ő, and so on) the auto-generated 
anchor will contains those chars and not replaced with engilsh basic chars (like e,o, and so on).
Those characters are invalid in any URI.

### Environment

* Windows 10
* Firefox Developer edition 87.0b9 (64 bit)
* @nuxt/content: v1.11.1
* nuxt: v2.14.12

### Reproduction Link
(none, but every install of this package got this problem)

### Steps to reproduce

1. Add a file for example: /content/something.md with this content:
`# Bevezetés`

2. Nuxt/content will generate an anchor with special latin chars:
`#bevezetés`

3. The link, to this anchor will not work on Firefox, only if you click two times on the link:
because of the "é" latin char. (or any other: áéóöőúüű)

### What is Expected?

The URLs must be not contains special chars, only basic latin alphabetical ones.
See the RFC about URIs: [](https://tools.ietf.org/html/rfc3986#section-1.2)**

### What is actually happening?

Nuxt/content will generate special chararters to the "fragment", that will cause navigtion problems
(two click on Firefox, or scrolling animation errors, and others).

### Fix:

The fragment generation must use a typical i18n slug generation code, fox example
replaces: é->e , ö->o , ä -> a, and so on.
An anchor with special latin chars: becomes #bevezetés" -> #bevezetes"

### Other things:
I came from [](https://github.com/nuxt/content/issues/835)

**Comment by wooorm** [comment]
this issue seems to be missing a lot of information?
