### ISSUE TITLE
How to support JIRA tables?

### ISSUE THREAD

**Issue by stevemk14ebr** [remarkjs/remark#720]
Hi, i'm writing a plugin to convert markdown to Jira's horrible markdown syntax. This requires that a table like this:

```
| Syntax      | Description | Test Text     |
| :---        |    :---:   |          :---: |
| Header      | Title       | Here's this   |
| Paragraph   | Text        | And more      |
```

converts to one where the header row has double pipes (https://jira.atlassian.com/secure/WikiRendererHelpAction.jspa?section=tables):
```
| |Syntax| | |Description| | |Test Text| |
| ---------- | --------------- | ------------- |
| Header     | Title           | Here's this   |
| Paragraph  | Text            | And more      |
```

I have this implemented similar to how your strip-markdown plugin works, but i've changed the following three formatters:
```
function table(node) {
    let headerRow = node.children ? node.children[0] : undefined;

    // tell row it's a header for later
    if (headerRow) {
        node.children[0].header = true;
    }
    return { type: 'table', children: node.children }
}

function tableRow(node) {
    // tell cell it's a header for later
    if (node.header) {
        for (let col of node.children) {
            col.header = true;
        }
    }
    return { type: 'tableRow', children: node.children }
}

function tableCell(node) {
    if (node.header) {
        for (let childIdx in node.children) {
            let content = toString(node.children[childIdx]);
            node.type = 'text';
            node.children[childIdx].value = `|${content}|`;
        }
    }
    return { type: 'tableCell', children: node.children }
}
...
const jiraConverter = Remark().use([[RemarkGFM, { singleTilde: false }], RemarkBreaks, RemarkJira]);
const jira = jiraConverter.processSync(text).toString();
```

This gets me pretty close to the desired output, but by pipes in the tableCell get escaped:
```
| \|Syntax\| | \|Description\| | \|Test Text\| |
| ---------- | --------------- | ------------- |
| Header     | Title           | Here's this   |
| Paragraph  | Text            | And more      |
```

Any tips for how I can remove that escaping?

**Comment by stevemk14ebr** [comment]
It seems maybe it's this option: https://github.com/syntax-tree/mdast-util-gfm-table/blob/704ed14ba30304e88b19250b2e3560665eeed3fa/to-markdown.js#L22 can I pass this option through remark-gfm somehow?

**Comment by wooorm** [comment]
Pipes in cells in normal markdown are supposed to be escaped, so that’s why that’s happening.
What if someone actually had a pipe in one of the (header) cells?

---

It’s not an option, it’s something that `mdast-util-gfm-table` turns on. I don’t think you can turn it off.

a) don’t use `mdast-util-gfm-table`, but instead supply your own
b) use both `mdast-util-gfm-table` *and* something that *overwrites* tables

**Comment by wooorm** [comment]
I’m assuming also that there are many cases where JIRA does not adhere to markdown. You might have to overwrite *many* things. If it’s really a lot of things that need to change, then it might be better to create a separate project?

**Comment by wooorm** [comment]
>  I get why it's not allowed normally in markdown but i'm in a special case where i want to break the markdown rules.

Totally understandable! It’s a very valid use case.

> 
Aside: a markdown -> jira plugin would be sweet. There's some other JS libraries that attempt this but they're all brittle and regex based. Markdown is much nicer to write in and there's more tooling support, an easy markdown -> jira need exists.

I agree! Although: I’m not personally interested in writing it. But maybe you are? I’ll help in advising where I can?

**Comment by stevemk14ebr** [comment]
I have to write the plugin anyway so i can send it to you but how should i handle the required duplication of remark-gfm? I'm going to copy the code in 1-1 and remove the bits i don't want

**Comment by wooorm** [comment]
I’m thinking something along these lines:

```js
import gfmTable from 'mdast-util-gfm-table'

const originalTable = gfmTable().handlers.table

export const myFunkyTable = {
  handlers: {table: myFunkyTableHandler}
}

function myFunkyTableHandler(node, _, context) {
  const result = originalTable(node, _, context).split('\n')
  result[0] = result[0].replace(/\|/g, '||')
  return result.join('\n)
}
```

**Comment by stevemk14ebr** [comment]
so here's how i solved this. It's a hack. I copied remark-gfm entirely, then i overrode how it uses the mdast-util-gfm-table with a hook:
```
function toMarkdown(options) {
    const origtable = markdowntable(options);
    const table = {
        handlers: {
            ...origtable.handlers,
            table: handleJiraTable
        }
    };

    // this hooks the normal table txt generation to go through a final pass where header |'s -> ||'s for Jira style
    function handleJiraTable(node, x, context) {
        let txt = origtable.handlers.table(node, x, context);
        let parts = txt.split('\n');
        if (parts.length > 1) {
            let header = parts[0].replaceAll("|", "||");
            parts.shift();
            return header + '\n' + parts.join('\n');
        }
        return txt;
    }

    var config = configure(
        { handlers: {}, join: [], unsafe: [], options: {} },
        {
            extensions: [autolinkLiteral, strikethrough, table, taskListItem]
        }
    )

    return Object.assign(config.options, {
        handlers: config.handlers,
        join: config.join,
        unsafe: config.unsafe
    })
}
```

I can't figure out how to do this without copying the remark-gfm  code into my project

**Comment by ChristianMurphy** [comment]
> I can't figure out how to do this without copying the remark-gfm code into my project

An alternative could be using https://www.npmjs.com/package/patch-package

**Comment by wooorm** [comment]
Are there no differences between GFM and JIRA in how they want autolinks, strikethrough, and tasklists?

**Comment by stevemk14ebr** [comment]
Jira is like a cousin of GFM that speaks with a weird accent. It's the same in spirit just using different control characters in some places. Summary:

* lists, ordered lists: same
* blockquotes: same
* tables: nearly the same, headers have 2 bars, doesn't support alignment syntax
* emphasis: uses _text_
* strong: uses *text*
* delete: uses -text-
* horizontalRule/thematicBreak: uses ----
* headers: h<number> vs ##, ex h1. or h2.
* code block: uses {code:language}text{code}
* code inline: uses {{text}}

everything else is the same as far as I know. To support this i've used a combination of a custom remark plugin and custom handlers for the stringify stage. Snippets:

remark-jira:
```
...copied traversal of strip-markdown, handlers follow...
function heading(node) {
    let depth = node.depth;
    let content = `h${depth}. ${NodeToString(node)}`;
    return {
        type: 'paragraph',
        children: [{
            type: 'text',
            value: content
        }]
    }
}

function code(node) {
    let lang = node.lang;
    if (lang) {
        return { type: 'text', value: `{code:${lang}}\n${node.value}\n{code}` }
    }
    return { type: 'text', value: `{code}\n${node.value}\n{code}` }
}

function horizontalRule(node) {
    return { type: 'horizontalRule', value: '----' }
}

function strikethrough(node) {
    return { type: 'delete', children: node.children }
}
```

stringify handlers:
```
[RemarkStringify, {
                handlers: {
                    horizontalRule: (node, parent, context) => {
                        // return string unescaped, would be /---- otherwise
                        return node.value;
                    },
                    delete: (node, parent, context) => {
                        let value = NodeToString(node);
                        return `-${value}-`;
                    },
                    emphasis: (node, parent, context) => {
                        let value = NodeToString(node);
                        return `_${value}_`;
                    },
                    strong: (node, parent, context) => {
                        let value = NodeToString(node);
                        return `*${value}*`;
                    }
                }
            }]
```

then combine that with the GFM hack i showed above and this is mostly a full jira pipeline. It's not elegant because I can't be bothered to package this how I should and make it 1 single 'plugin' like the GFM stuff is, but it works.

**Comment by stevemk14ebr** [comment]
![image](https://user-images.githubusercontent.com/6619205/119838388-5ea13e80-bed1-11eb-8903-ca1090b29ad8.png)

```
h1. normal stuff

*   list item 1

*   list item 2

----

*   list item 3

*   list item 4

----

*   list item 5

*   list item 6

----

> quote *block*
> with some more _italic text_, and inline {{code}} with {{this}} style too -strikethough-

{code:js}
function blah(a) {
    let b = a;
    return b*b;
}
{code}

h2. table test

||Syntax   ||Description||
|---------|-----------|
|Header   |Title      |
|Paragraph|Text       |

```

**Comment by wooorm** [comment]
Hmm, I think copying `strip-markdown` was a wrong rabbit hole to take probably. Only dealing with serialization handlers in this case, where you‘re turning a tree into a string, seems best, as it’s made for that.

**Comment by stevemk14ebr** [comment]
Took me until this ticket where you suggested that i just return a string to realize that lol
