### ISSUE TITLE
Emphasis takes precedence over inline code span

### ISSUE THREAD

**Issue by eush77** [remarkjs/remark#75]
Input:

```
_`_`_
```

Actual AST:

``` json
{
  "type": "paragraph",
  "children": [
    {
      "type": "emphasis",
      "children": [
        {
          "type": "text",
          "value": "`"
        }
      ]
    },
    {
      "type": "text",
      "value": "`_"
    }
  ]
}
```

Expected AST:

``` json
{
  "type": "paragraph",
  "children": [
    {
      "type": "emphasis",
      "children": [
        {
          "type": "inlineCode",
          "value": "_"
        }
      ]
    }
  ]
}
```

[Commonmark](http://spec.commonmark.org/0.22/#example-305):

> Code span backticks have higher precedence than any other inline constructs except HTML tags and autolinks. Thus, for example, this is not parsed as emphasized text, since the second `*` is part of a code span: `*foo`*``.

**Comment by wooorm** [comment]
This kinda sucks; due to the legacy of marked this isn’t really do-able currently.

I’d love to make this happen but it will need a rewrite of the parsing algorithm; stepping away from regexes and to a real algorithmic tokeniser, e.g., like markdown-it :frowning:

**Comment by eush77** [comment]
I came across [the test](https://github.com/wooorm/mdast/blob/552abfcab1224e1d9666ed453d538d8a9581c010/test/tree/nested-square-link.commonmark.json) that freezes the wrong precedence of `inlineCode` against `linkReference`.

In Commonmark,

```
[the `]` character](/url)
```

[should parse as](http://spec.commonmark.org/dingus/?text=[the%20%60]%60%20character]%28%2Furl%29)

```html
<a href="/url">the <code>]</code> character</a>
```

**Comment by wooorm** [comment]
Nice catch @eush77! In fact, I think all of the “pending” tests in [mdast-html](https://travis-ci.org/wooorm/mdast-html/jobs/80073421) have to do with this (I wrote a bit about it [here](https://github.com/wooorm/mdast-html/blob/master/doc/commonmark.md)).

I think the only way to fix this is by rewriting the engine to use code tokenisers in favour of regexes; it’ll take a while to rewrite everything though!

**Comment by wooorm** [comment]
Let’s track this in GH-306.
