### ISSUE TITLE
Nested list incorrectly parsed when first item is empty

### ISSUE THREAD

**Issue by artem-barmin** [remarkjs/remark#759]
### Subject of the issue

When first item in nested unordered list is empty - `remark` does not detect structure as list, but create node like:

```
{
                    "type": "listItem",
                    "children": [
                        {
                            "type": "paragraph",
                            "children": [
                                {
                                    "type": "text",
                                    "value": "a\n*"
                                }
                            ]
                        }
                    ]
                }
```

### Your environment

*   **OS**: macOS Big Sur 11.3
*   **Packages**: remark^13.0.0
*   **Env**: node v16.2.0

### Steps to reproduce

https://codesandbox.io/s/remark-debug-forked-vng8c?file=/src/index.js

### Expected behavior

List item node should be created

### Actual behavior

Nested list item node collapsed into parent node as plain text `"a\n*"`

**Comment by ChristianMurphy** [comment]
Correct, this is how commonmark handles lists, for example in the reference implementation: https://spec.commonmark.org/dingus/?text=*%20a%0A%20%20*%20
remark follows the commonmark standard.
It could be worth discussing upstream at https://talk.commonmark.org if the example could be considered a break in https://spec.commonmark.org/0.30/#principle-of-uniformity and maybe should be changed in commonmark (then in micromark/remark).

**Comment by wooorm** [comment]
What Christian points out is correct. That is because empty list items cannot interrupt paragraphs:

```markdown
a
*

b
1.
```

```html
<p>a
*</p>
<p>b
1.</p>
```

This behavior is specified in CommonMark, and while you can indeed start a discussion there, I don’t see it changing.
