### ISSUE TITLE
Weird indentation rules for nested list

### ISSUE THREAD

**Issue by PeachScript** [remarkjs/remark#764]
### Subject of the issue

The generate logic for nested list is confusing, sometimes 2 spaces can trigger nested rule, but sometimes cannot.

### Your environment

*   **OS**: --
*   **Packages**: --
*   **Env**: AST Explorer

### Steps to reproduce

Please visit this link: https://astexplorer.net/#/gist/f576e3a8fcd4d6bdc3ea8f8b0c317e67/e8440719cdc865a27dae6f621f6dffef9f9f6df8

### Expected behavior

All writing methods can trigger nested rule.

### Actual behavior

The following writing method cannot works:

```md
- a
  - b
- c
```

**Comment by ChristianMurphy** [comment]
Right, that is how markdown lists work.
the behavior is described in the commonmark spec at https://spec.commonmark.org/0.30/#example-311 and matches the reference implementation https://spec.commonmark.org/dingus/?text=4%20spaces%20can%20be%20nested%0A%0A1.%20xx%0A%20%20%20%201.%20xx%0A2.%20xx%0A%0A2%20spaces%20cant%20not%20be%20nested%0A%0A1.%20xx%0A%20%201.%20xx%0A2.%20xx%0A%0ABut%202%20spaces%20without%20last%20top-level%20item%20can%20be%20nested%0A%0A1.%20xx%0A%20%201.%20xx

If you're looking for a way to highlight where indent may not be used as expected consider using remark-lint https://github.com/remarkjs/remark-lint/tree/main/packages/remark-preset-lint-recommended#readme
the https://github.com/remarkjs/remark-lint/tree/main/packages/remark-lint-list-item-bullet-indent rule will catch where indent may not be used as intended.
