### ISSUE TITLE
Link to Documentation & Snippet in README

### ISSUE THREAD

**Issue by coolaj86** [remarkjs/remark#778]
### Subject of the feature

I'd like to see something like this in the README:

~~~mkdn
## Documentation

See https://wherever-docs-are/docs/#quickstart

## Browser Usage

```html
<script src="https://cdn.jsdelivr.net/npm/remark@x.y.z/dist/browser/remark.min.js"></script>
<script>
  var html = window.Remark.render("# Hello, World!\n\nHey!\nHo!\n\nLet's go!")
  document.body.innerHTML = html;
</script>
```

## Node Usage

```bash
npm install --save remark
```

```js
var remark = require('remark')
var html = remark.render("# Hello, World!\n\nHey!\nHo!\n\nLet's go!")
console.log(html);
```

~~~

### Problem

Searching for "doc" on the README... I get nothing. I can't find the documentation.

### Expected behavior

There should be a link to the docs, and a no-brainer short snippet quick start, like the one shown above.

### Alternatives

<https://marked.js.org/#installation>

**Comment by ChristianMurphy** [comment]
There are four packages in this repo, each has its own readme, remark's is in the remark folder https://github.com/remarkjs/remark/tree/main/packages/remark#readme

**Comment by ChristianMurphy** [comment]
For a more general introduction see https://unifiedjs.com/learn also linked from the readme

**Comment by coolaj86** [comment]
Is there a CDN URL for the browser?

**Comment by wooorm** [comment]
there are several CDNs that provide browser builds for any package on npm. Such as https://jspm.org, https://esm.sh, https://www.skypack.dev.

**Comment by coolaj86** [comment]
Yes, I am aware. But what's the url for _this_ package and its builds?

The dist stuff isn't committed to the repo, so I can't see the folder structure, and none of the "Learn Unified" blog posts or the READMEs seem to reference it.

**Comment by wooorm** [comment]
Another solutions would be unpkg. Some of these CDNs show a search box at the top. unpkg itself provides several examples of how to use URLs to get bundled packages: https://unpkg.com

> But what's the url for this package and its builds?

It depends on which of the hundreds of unified packages you want and which CDN you want. If you’d want unified itself, un unpkg, it could be:

https://unpkg.com/unified

> The dist stuff isn't committed to the repo, so I can't see the folder structure

There are indeed no `dist/` folders. There is only the source code, which is directly published to npm.

> and none of the "Learn Unified" blog posts or the READMEs seem to reference it.

They all assume knowledge of npm or yarn to install packages

**Comment by coolaj86** [comment]
> They all assume knowledge of npm or yarn to install packages

I don't know if you're trolling me, or if you just don't do frontend browser development.

npm packages don't work in browsers unless you do something to make them work in browsers. On unpkg.com, for example, you can see that React has a `./umd` directory that's published to npm that hold the dist files. Most packages that I've used in the browser follow a similar pattern where you're required to specify the `./dist` or `./browser` or some such and then the development or minified version.

It sounds like you're saying that you don't publish dist files, in which case this code probably doesn't work in the browser.

> It depends on which of the hundreds of unified packages you want

I don't even know what that means. It almost sounds like `unified` is its own package system, but built in the style of a pipeline plugin system. I've never heard of unified before and if it's some sort of common dependency plugin system I don't know why I'd need to learn about _it_ specifically to use this project.

I'm here on the **remark** repo (not the _unified_ repo) because I want to do what remark claims to be the most popular at doing - convert markdown to html.

**Comment by wooorm** [comment]
> I don't know if you're trolling me, or if you just don't do frontend browser development.

I have a lot of frontend experience. I am not trolling you. I am surprised by people proficient in frontend that do not have experienced bundling code before.

> npm packages don't work in browsers unless you do something to make them work in browsers

That is what unpkg et al do. Some CDNs bundle code. Specifically, unified itself, is an ESM module. Which evergreen browsers support. You can use `import {unified} from 'https://unpkg.com/unified'` in browsers to access the code.

*You* can also do things to run code from npm in browsers. These are called bundlers. such as browserify, webpack, rollup, parcel, and what I’d suggest: esbuild.

> I don't even know what that means. It almost sounds like unified is its own package system, but built in the style of a pipeline plugin system. I've never heard of unified before and if it's some sort of common dependency plugin system I don't know why I'd need to learn about it specifically to use this project.

This is like asking about a jQuery plugin but not wanting to know jQuery. I understand it, but I urge you to take some time to read up on the different projects, packages, and what the problem space entails.

> I'm here on the remark repo (not the unified repo) because I want to do what remark claims to be the most popular at doing - convert markdown to html.

Users often don’t know well what they’re asking for. Especially, well, it took me 3 times of asking what and why to get you to ask this. That’s why I ask what and why’s.

You might like micromark: https://github.com/micromark/micromark.

**Comment by ChristianMurphy** [comment]
> That is what unpkg et al do. Some CDNs bundle code. Specifically, unified itself, is an ESM module. Which evergreen browsers support. You can use `import {unified} from 'https://unpkg.com/unified'` in browsers to access the code.

To add on to this, once https://github.com/unifiedjs/unified/issues/121 including ESM has rolled out to `remark`.
Import maps (https://www.chromestatus.com/feature/5315286962012160) offer the potential that `remark` could be run in browser without any build tools.

> I'm here on the remark repo (not the unified repo) because I want to do what remark claims to be the most popular at doing - convert markdown to html.

https://unifiedjs.com/learn/recipe/remark-html/

**Comment by ChristianMurphy** [comment]
> I don't even know what that means. It almost sounds like unified is its own package system, but built in the style of a pipeline plugin system. I've never heard of unified before and if it's some sort of common dependency plugin system I don't know why I'd need to learn about it specifically to use this project.

unified is the abstract syntax tree utility that remark builds on, the introduction gives more context https://unifiedjs.com/learn/guide/introduction-to-unified/
It's useful in this context because `remark` handles parsing markdown and compiling back to markdown.
You want to move from markdown to HTML, this is supported through a mix is remark and rehype https://unifiedjs.com/learn/recipe/remark-html/
