### ISSUE TITLE
Depend on unified@10?

### ISSUE THREAD

**Issue by karlhorky** [remarkjs/remark#787]
Hi @wooorm ! 👋 Hope you're all good.

### Subject of the feature

Upgrade `unified` from [`^9.1.0`](https://github.com/remarkjs/remark/blob/ea4fd81c0a8afc0aac9def0a97b111926b6e6aec/packages/remark/package.json#L40) to `^10.0.0` (major version upgrade). Are there any plans to do this upgrade?

### Problem

When using `unified@10` in a project which also has a dependency on `remark@13`, I'm getting type errors:

```
  The last overload gave the following error.
    Argument of type 'Plugin<[(htmlOptions | undefined)?]>' is not assignable to parameter of type 'ProcessorSettings<RemarkOptions>'.
      Property 'settings' is missing in type 'Plugin<[(htmlOptions | undefined)?]>' but required in type 'ProcessorSettings<RemarkOptions>'.
```

### Expected behavior

The latest `remark` should also be compatible with the latest `unified`

### Alternatives

This may be as a result of unusual dependency resolution because of the Yarn Workspaces configuration that it is under. Could investigate further and probably find a way to fix the types.

**Comment by wooorm** [comment]
Expect it soon: https://github.com/unifiedjs/unified/issues/121.

I've done almost everything except remark and rehype. Those are planned before end of month!

**Comment by wooorm** [comment]
Released! https://github.com/remarkjs/remark/releases/tag/14.0.0

**Comment by karlhorky** [comment]
Amazing, thanks!
