### ISSUE TITLE
Typescript support on nodejs

### ISSUE THREAD

**Issue by 3axap4eHko** [remarkjs/remark#819]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

14.0.1

### Link to runnable example

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzlApiAhlA1nAvnAMyghDgHJUNsyBuAKFElmTUywAkAVAWQBlDipCq2wBaABYwQAG1p06AYwgA7AM7xJMgMIqYKZfAC8cAAZ0AxJbjsU06RDgB3aNIAmAQjon6dABTpVAE9lBThfAEo4QwA+RDo4OCU1eCS9Ayi4dEd0YHhKNgiAOgBXVRRffOwuPnDCsGIFFFVVX01pHQN9GHD6BKTVCGkUQvsAc19Urp66XHCI+iA

### Steps to reproduce

1. Install `remark`, `remark-html`, `typescript`
2. execute the following code using `ts-node`
```
import { remark } from 'remark';
import remarkHTML from 'remark-html';

const htmlContent = `
### Hello world!
`;

(async () => {
  const content = await remark().use(remarkHTML).process(htmlContent);
  console.log(content);
})();
```

### Expected behavior

I expect to see `<h3>Hello world!</h3>`

### Actual behavior

Error `Cannot use import statement outside a module`

### Runtime

Node v16

### Package manager

yarn v2

### OS

Linux

**Comment by wooorm** [comment]
Hi there!

This is because of ESM.
Please see the changelog for v14 and the resources linked from there (which is also references from the install sections in the readmes): https://github.com/remarkjs/remark/releases/tag/14.0.0.

**Comment by 3axap4eHko** [comment]
@wooorm any suggestions on how can I handle this on typescript?

**Comment by wooorm** [comment]
Sure. See the TS section in that linked post: https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c#how-can-i-make-my-typescript-project-output-esm

**Comment by 3axap4eHko** [comment]
@wooorm it does not help, I'm facing the same error message in my app and ts playground

**Comment by wooorm** [comment]
It sounds like you don't have a package.json with a type: 'module' field?

**Comment by 3axap4eHko** [comment]
@wooorm  this is an example https://gist.github.com/3axap4eHko/5b787dae3ad3c07473ed0d424fefff99

**Comment by wooorm** [comment]
Thanks, right, that’s still missing `"type": "module"` in `package.json`

**Comment by 3axap4eHko** [comment]
Exactly, and it does not work if I set `"type": "module"`

**Comment by wooorm** [comment]
Could you please post the issue that arises when you do?

**Comment by wooorm** [comment]
Jeez, my friend, you are not just using TypeScript. You are using Jest and ts-node, which (most importantly Jest) are bad at modules.
It’s okay using TS and ts-node with modules, but Jest is really really bad at it.
There are lots of ways around it, as can be seen in that FAQ, but I’d say: use the previous version of remark for now. It’s all possible, but a bit of a messy situation, which might not be worth your time now

**Comment by ChristianMurphy** [comment]
To add on, using remark with TypeScript is fairly straight forward https://stackblitz.com/edit/http-server-quvryg?file=example.ts is an example of how it works, just the few configuration tweaks mentioned in https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c#how-can-i-make-my-typescript-project-output-esm makes TypeScript happy, plus it can also use top level await.

As @wooorm notes, using Jest with ESM currently can a bit more involved, but the Jest team is working to improve ESM support, you can track the progress of that initiative here: https://github.com/facebook/jest/issues/9430

**Comment by yuzhanglong** [comment]
> Hi there!
> 
> This is because of ESM. Please see the changelog for v14 and the resources linked from there (which is also references from the install sections in the readmes): https://github.com/remarkjs/remark/releases/tag/14.0.0.

I think it's best to provide a commonJS version, otherwise libraries like Jest won't work.
Many well-known libraries provide both ESM and commonjs versions, and UMD versions suitable for browsers if necessary.

**Comment by wooorm** [comment]
I recommend using a different test framework that Jest. Dual doesn’t work well in my experience.

We’ve had this discussion already. This isn’t bringing new information to that discussion. To prevent that from happening further, I’m locking this issue.
