### ISSUE TITLE
stringify() appears to mishandle reference links with inline code

### ISSUE THREAD

**Issue by Trott** [remarkjs/remark#850]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

remark-stringify@10.0.0

### Steps to reproduce

```js
import {unified} from 'unified'
import remarkParse from 'remark-parse'
import remarkStringify from 'remark-stringify'

const u = unified()

const input = '[`foo`][]\n\n[`foo`]: http://example.com/'

const ast = u()
  .use(remarkParse)
  .parse(input)

const output = u()
  .use(remarkStringify)
  .stringify(ast)

if (input !== output) {
  console.log(`INPUT: ${input}`)
  console.log(`OUTPUT: ${output}`)
  console.log(`AST: ${JSON.stringify(ast, null, 1)}`)
}
```

### Expected behavior

I would expect the link on the first line of the input/output to either be left as it is in the input, or else converted to ```[`foo`][`foo`]```.

### Actual behavior

The output breaks the reference link on the first line by changing it from ```[`foo`][]``` to ```[`foo`][foo]```.

### Runtime

Node v16

### Package manager

npm v7

### OS

macOS

**Comment by wooorm** [comment]
What does it break though? Other than being different?

**Comment by Trott** [comment]
The link is broken by the transformation (unless I'm misunderstanding something?). Here's the document input:

```markdown
[`foo`][]

[`foo`]: http://example.com/
```

A typical markdown-to-HTML tool might render like this:

```html
<p><a href="http://example.com/"><code>foo</code></a></p>
```

However, after being run through `parse()` and then `stringify()`, we have this:

```markdown
[`foo`][foo]

[`foo`]: http://example.com/
```

The link is now broken because it no longer matches the reference at the bottom. A typical markdown-to-HTML tool might render it like this:

```html
<p>[<code>foo</code>][foo]</p>
```

No link anymore and the brackets are all being included as part of the paragraph text.

**Comment by Trott** [comment]
`mdast-util-from-markdown` seems to generate the wrong `label` for the link, if I'm understanding it correctly.
