### ISSUE TITLE
Empty line added after modifying AST

### ISSUE THREAD

**Issue by coderaiser** [remarkjs/remark#897]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

Latest in AST explorer

### Link to runnable example

https://astexplorer.net/#/gist/e30bae0f09dbfafae733e24f78d1a172/136ce4a457f8f70c777a3853f394733ba7838c6a

### Steps to reproduce

Accessible by link

### Expected behavior

Empty line between  definitions not added

### Actual behavior

Added empty line between definitions

### Runtime

Other (please specify in steps to reproduce)

### Package manager

Other (please specify in steps to reproduce)

### OS

macOS

### Build and bundle tools

Other (please specify in steps to reproduce)

**Comment by wooorm** [comment]
Files are supposed to have a line ending at their end (you may have seen it in Git/GitHub as a red marker at ends of files). That’s why it’s there

**Comment by wooorm** [comment]
1:1-1:27: Expected corresponding JSX closing tag for `<GITHUB_USER>` (1:14-1:27)

**Comment by wooorm** [comment]
Oh wait, you mean definitions?! You can pass an option: https://github.com/syntax-tree/mdast-util-to-markdown#optionstightdefinitions.

**Comment by coderaiser** [comment]
@wooorm thank you! that works. But I have one more problem, after transform I have a space at the end of line:

```
# @putout/putout-formatter-dump [![NPM version][NPMIMGURL]][NPMURL]·<----- additional space after remove
```

Could you please help me with this?

By the way thank you for such a great tool :)! Everything is pretty simple and works in predictable way, very good `API`.

**Comment by coderaiser** [comment]
Looks like I'm understood:

![image](https://user-images.githubusercontent.com/1573141/141529738-7510d379-797a-4abc-868f-3ecd51a39a08.png)

The reason is `text` node, which should be removed as well.

@wooorm thanks a lot for quick answers, you awesome :)! Everything works like a charm so I close issue.

**Comment by wooorm** [comment]
Glad this helped! We’re working on improving docs btw. Making it easier for newcomers to find what they do or don’t need!

The extra space, when parsing, is ignored. When serializing, it isn’t. Because users could’ve added them explicitly with a `&#20;`. You can clean your AST after you’ve done transforming stuff yourself though maybe?

**Comment by coderaiser** [comment]
> The extra space, when parsing, is ignored. When serializing, it isn’t. Because users could’ve added them explicitly with a &#20;. You can clean your AST after you’ve done transforming stuff yourself though maybe?

Yes [it works great](https://github.com/coderaiser/putout/blob/master/packages/processor-markdown/lib/rules/remove-dependencies-status-badge.mjs) :), here is [results](https://github.com/coderaiser/putout/commit/f8103ae368c2bb114f690b3af6a083bf52e2ce4d).

**Comment by coderaiser** [comment]
> The extra space, when parsing, is ignored. 

So it's impossible to write a `rule` that will remove trailing whitespaces?

**Comment by wooorm** [comment]
That statement is incorrect.
*parsing* ignores it, meaning that one extra trailing space is insignificant per commonmark.
Two spaces turn into a hard break (same as `\\\n`).
You can definitely remove trailing whitespace in a rule: https://github.com/remarkjs/remark-strip-badges/blob/368d853d69e68d2f34f11979d72a3187176ed4e6/index.js#L39-L62.

**Comment by coderaiser** [comment]
But I can't see it's parsed in `AST` https://astexplorer.net/#/gist/e30bae0f09dbfafae733e24f78d1a172/68c8de550ce01a8710563188d539d5551b156d7b

**Comment by wooorm** [comment]
https://astexplorer.net/#/gist/31ef327fa9cab46c714cad68547bad84/e5c907ab937dd86964a644471c13f694c366097d

https://spec.commonmark.org/dingus/?text=aaa%26%23x20%3B%26%23x20%3B%26%23x20%3B%0Abbb%0A%0Aaaa%5C%0Abbbbbbbbb%0A%0Aaaa%20%20%20%5C%0Abbbbbbbbb
