### ISSUE TITLE
Changing the node.type eliminates the node from the tree

### ISSUE THREAD

**Issue by NullVoxPopuli** [remarkjs/remark#926]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

remark-parse@14+

### Link to runnable example

https://codesandbox.io/s/bitter-morning-8ftyb?file=/src/index.js

### Steps to reproduce

Note that the result shows `<h1></h1> <p></p> `

comment out the `node.type = 'html'` line, and the code comes back.

### Expected behavior

I expect the output of:
```
<h1>heading</h1> <p><MyComponent as |he|></p> 
```
(roughly, I'm not entirely sure),

### Actual behavior

text nodes with their type changed to .html are removed entirely.

### Runtime

Other (please specify in steps to reproduce)

### Package manager

Other (please specify in steps to reproduce)

### OS

Linux

### Build and bundle tools

Other (please specify in steps to reproduce)

**Comment by ChristianMurphy** [comment]
Raw HTML nodes generally need to be parsed to HAST with https://github.com/rehypejs/rehype-raw

**Comment by ChristianMurphy** [comment]
Or less ideal, allow dangerous HTML can be used https://github.com/remarkjs/remark-rehype#example-supporting-html-in-markdown-na%C3%AFvely

**Comment by NullVoxPopuli** [comment]
how do those solve my problem of disappearing nodes?

**Comment by ChristianMurphy** [comment]
When translating markdown to HTML (mdast to hast), remark rehype (and by extension remark html) removes raw/unsafe html nodes.
The above guides show how to preserve those nodes.
