### ISSUE TITLE
Backtics are missing if code blocks language is not defined

### ISSUE THREAD

**Issue by AndrejGajdos** [remarkjs/remark#941]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

react-stringify 10.0.2, unified 10.1.1

### Steps to reproduce

[codesandbox](https://codesandbox.io/s/beautiful-water-1j3fe?file=/src/App.js:0-1695)

### Expected behavior

The second code block without `lang` parameter is missing backticks:

```
{
    "stringified": "```javascript\nfunction $initHighlight(block, cls) {\n  return (\n    <div>\n      <web-component>test</web-component>\n    </div>\n  )\n}\nexport  $initHighlight;\n```\n\n    function $initHighlight(block, cls) {\n      return (\n        <div>\n          <web-component>test</web-component>\n        </div>\n      )\n    }\n    export  $initHighlight;\n"
}
```

The correct output would be:

```
{
    "stringified": "```javascript\nfunction $initHighlight(block, cls) {\n  return (\n    <div>\n      <web-component>test</web-component>\n    </div>\n  )\n}\nexport  $initHighlight;\n```\n\n    ```function $initHighlight(block, cls) {\n      return (\n        <div>\n          <web-component>test</web-component>\n        </div>\n      )\n    }\n    export  $initHighlight;```\n"
}
```

### Actual behavior

When code block is converted to string, it should be wrapped with backticks ```.

This is the input wuth two code blocks. The `lang` parameter is defined in the first one.

```
{
      type: "root",
      children: [
        {
          type: "code",
          lang: "javascript",
          meta: null,
          value:
            "function $initHighlight(block, cls) {\n  return (\n    <div>\n      <web-component>test</web-component>\n    </div>\n  )\n}\nexport  $initHighlight;"
        },
        {
          type: "code",
          lang: null,
          meta: null,
          value:
            "function $initHighlight(block, cls) {\n  return (\n    <div>\n      <web-component>test</web-component>\n    </div>\n  )\n}\nexport  $initHighlight;"
        }
      ]
    }
```

This is the result:

```
{
    "stringified": "```javascript\nfunction $initHighlight(block, cls) {\n  return (\n    <div>\n      <web-component>test</web-component>\n    </div>\n  )\n}\nexport  $initHighlight;\n```\n\n    function $initHighlight(block, cls) {\n      return (\n        <div>\n          <web-component>test</web-component>\n        </div>\n      )\n    }\n    export  $initHighlight;\n"
}
```

**Comment by wooorm** [comment]
You can configure remark: https://github.com/remarkjs/remark/tree/main/packages/remark-stringify#unifieduseremarkstringify-options.
