### ISSUE TITLE
Not escaping > in code block or span

### ISSUE THREAD

**Issue by akrawitz** [remarkjs/remark#955]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

unified v10.1.1, rehype-stringify v9.0.3, remark-parse v10.0.1, remark-rehype v10.1.0

### Link to runnable example

https://codesandbox.io/s/smoosh-grass-db4x2b

### Steps to reproduce

Please take a look at the codesandbox example linked above, which was adapted from the "remark and rehype" starter.

### Expected behavior

I think the "raw result" should look like:
 ~~~
<h1>heading</h1>
<p><code>&lt;p&gt;test&lt;/p&gt;</code></p>
<pre><code class="language-html">&lt;p&gt;another test&lt;/p&gt;
</code></pre>
~~~
or
 ~~~
<h1>heading</h1>
<p><code>&#x3C;p&#x3E;test&#x3C;/p&#x3E;</code></p>
<pre><code class="language-html">&#x3C;p&#x3E;another test&#x3C;/p&#x3E;
</code></pre>
~~~

### Actual behavior

Instead it looks like:
~~~
<h1>heading</h1>
<p><code>&#x3C;p>test&#x3C;/p></code></p>
<pre><code class="language-html">&#x3C;p>another test&#x3C;/p>
</code></pre>
~~~
Note that the greater-than signs (>) in the code blocks/spans are not being encoded.

Apologies in advance if this is the wrong place for this issue. I am not sure if the issue is in `remark` or `rehype`.

Thanks in advance for your help.

**Comment by ChristianMurphy** [comment]
@akrawitz could you expand on why additional escaping is needed?
Looking at the sandbox, the result renders the source in code block as expected.

**Comment by akrawitz** [comment]
My attention was brought to it due to a [spec-char-escape](https://htmlhint.com/docs/user-guide/rules/spec-char-escape) linting error from HTMLHint. But, of course, a linter rule may just be an opinionated recommendation.

I had assumed it looked ok when rendered because the browser was just doing a good job of handling it despite it being invalid.

I was under the (perhaps mistaken) impression that the less-than, greater-than, and ampersand characters should always be escaped in HTML content (e.g. https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Getting_started#entity_references_including_special_characters_in_html, https://www.w3.org/International/questions/qa-escapes#use, and https://www.w3.org/TR/html401/charset.html#h-5.3.2). But, having just looked at the current HTML spec, I'll admit that I'm not able to locate such a requirement.

In the interest of "better safe than sorry" I will continue to escape <, >, and & in HTML, but if in fact it is not necessary or desired, my apologies for submitting this as an issue, and please go ahead and close it.

**Comment by wooorm** [comment]
HTMLHint is wrong. It’s okay! There are many cases where `<` has to be encoded, a few where `&` has to be encoded, and `>` essentially never has to be encoded!
